src/objects/BP_Molecule__c.object
<CustomObject>
    <description>Junction Object between Business Plan &amp; Molecule</description>
    <fields>
        <fullName>RWE_Business_Planning__c</fullName>
        <label>RWE Business Planning</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipLabel>RWE BP Molecules</relationshipLabel>
        <relationshipName>RWE_BP_Molecules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RWE_Molecule__c</fullName>
        <label>RWE Molecule</label>
        <referenceTo>Molecule__c</referenceTo>
        <relationshipLabel>RWE BP Molecules</relationshipLabel>
        <relationshipName>RWE_BP_Molecules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RWE BP Molecule</label>
    <nameField>
        <displayFormat>BPM-{0000}</displayFormat>
        <label>BP_Molecule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE BP Molecules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BP_Proposed_TPO__c.object
<CustomObject>
    <description>Junction Object Between BP and TPO Location</description>
    <fields>
        <fullName>RWE_Business_Planning__c</fullName>
        <label>RWE Business Planning</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipLabel>Proposed TPOs</relationshipLabel>
        <relationshipName>RWE_BP_Proposed_TPOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RWE_TPO_Location__c</fullName>
        <label>RWE TPO Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TPO_Location__c.Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TPO_Location__c</referenceTo>
        <relationshipLabel>RWE BP Proposed TPOs</relationshipLabel>
        <relationshipName>RWE_BP_Proposed_TPOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RWE BP Proposed TPO</label>
    <nameField>
        <displayFormat>BPTPO-{0000}</displayFormat>
        <label>PANG BP Proposed TPO Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE BP Proposed TPOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BPRelated_Data_Asset__c.object
<CustomObject>
    <description>Related Data Asset junction object between Data Asset &amp; Business Planning objects</description>
    <fields>
        <fullName>RWD_Data_Asset__c</fullName>
        <label>RWD Data Asset</label>
        <referenceTo>Data_Asset__c</referenceTo>
        <relationshipName>RWE_BPRelated_Data_Assets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RWE_Business_Planning__c</fullName>
        <label>RWE Business Planning</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipName>RWE_Related_Data_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RWE Related Data Asset(BP)</label>
    <nameField>
        <displayFormat>BP-DA-{00000}</displayFormat>
        <label>Related Data Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE Related Data Assets(BP)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Business_Planning__c.object
<CustomObject>
    <fields>
        <fullName>BPType__c</fullName>
        <description>Business Plan classification</description>
        <inlineHelpText>Business Plan classification</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Study</fullName>
                    <color>#0B6FCE</color>
                    <label>Study</label>
                </value>
                <value>
                    <fullName>Research Project</fullName>
                    <color>#78C953</color>
                    <label>Research Project</label>
                </value>
                <value>
                    <fullName>Non-Research Project</fullName>
                    <color>#E27001</color>
                    <label>Non-Research Project</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GPORWE_Functional_Area__c</fullName>
        <label>Sub-Function</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Executing_Function__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Biomedicines</fullName>
                    <color>#0B6FCE</color>
                    <label>Biomedicines</label>
                </value>
                <value>
                    <fullName>Canada</fullName>
                    <color>#78C953</color>
                    <label>Canada</label>
                </value>
                <value>
                    <fullName>China</fullName>
                    <color>#E27001</color>
                    <label>China</label>
                </value>
                <value>
                    <fullName>COE</fullName>
                    <color>#A845DC</color>
                    <label>COE</label>
                </value>
                <value>
                    <fullName>Diabetes</fullName>
                    <color>#F3D904</color>
                    <label>Diabetes</label>
                </value>
                <value>
                    <fullName>France Hub</fullName>
                    <color>#A53711</color>
                    <label>France Hub</label>
                </value>
                <value>
                    <fullName>Germany Hub</fullName>
                    <color>#66E9BD</color>
                    <label>Germany Hub</label>
                </value>
                <value>
                    <fullName>HTA-CE</fullName>
                    <color>#0B24BE</color>
                    <label>HTA-CE</label>
                </value>
                <value>
                    <fullName>HTA-EMBU/J</fullName>
                    <color>#419249</color>
                    <label>HTA-EMBU/J</label>
                </value>
                <value>
                    <fullName>Italy Hub</fullName>
                    <color>#B6E32E</color>
                    <label>Italy Hub</label>
                </value>
                <value>
                    <fullName>Korea</fullName>
                    <color>#641CCF</color>
                    <label>Korea</label>
                </value>
                <value>
                    <fullName>LBM-AI/BMJ</fullName>
                    <color>#F96FB7</color>
                    <label>LBM-AI/BMJ</label>
                </value>
                <value>
                    <fullName>LBM-CV/URO</fullName>
                    <color>#2F5D85</color>
                    <label>LBM-CV/URO</label>
                </value>
                <value>
                    <fullName>LBM-NS</fullName>
                    <color>#AFCADF</color>
                    <label>LBM-NS</label>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                    <color>#8F6429</color>
                    <label>Oncology</label>
                </value>
                <value>
                    <fullName>PMO</fullName>
                    <color>#EFAE73</color>
                    <label>PMO</label>
                </value>
                <value>
                    <fullName>PRO</fullName>
                    <color>#57F17C</color>
                    <label>PRO</label>
                </value>
                <value>
                    <fullName>Spain Hub</fullName>
                    <color>#0B6FCE</color>
                    <label>Spain Hub</label>
                </value>
                <value>
                    <fullName>Taiwan</fullName>
                    <color>#78C953</color>
                    <label>Taiwan</label>
                </value>
                <value>
                    <fullName>UK Hub</fullName>
                    <color>#E27001</color>
                    <label>UK Hub</label>
                </value>
                <value>
                    <fullName>US Biomedicines</fullName>
                    <color>#A845DC</color>
                    <label>US Biomedicines</label>
                </value>
                <value>
                    <fullName>US Diabetes</fullName>
                    <color>#F3D904</color>
                    <label>US Diabetes</label>
                </value>
                <value>
                    <fullName>USHO</fullName>
                    <color>#A53711</color>
                    <label>USHO</label>
                </value>
                <value>
                    <fullName>US Oncology</fullName>
                    <color>#66E9BD</color>
                    <label>US Oncology</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <color>#0B24BE</color>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_the_Data_Asset_Known__c</fullName>
        <label>Is the Data Asset Known?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_TPO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Search either by Name or Capability. After selecting lookup, change search choice to &quot;All Fields&quot; to search on capabilities.
If TPO is not listed, search and select *Other* from the list.</inlineHelpText>
        <label>Selected TPO</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>TPO_Location__c.Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>$User.Username</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.SkipValidation__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Select &apos;All Fields&apos; in order to search by Capability or Location.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TPO_Location__c</referenceTo>
        <relationshipName>RWE_Business_Planning</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Planning</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study/Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Planning</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Inventory of countries paired with their respective region.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Data_Asset__c.object
<CustomObject>
    <description>Real World Data Inventory</description>
    <label>Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Molecule__c.object
<CustomObject>
    <label>Compound</label>
    <nameField>
        <label>Molecule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RWE_BP_Benefitting_Region__c.object
<CustomObject>
    <description>Junction between BP &amp; (Benefitting) Country</description>
    <fields>
        <fullName>RWE_Business_Planning__c</fullName>
        <label>RWE Business Planning</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipName>RWE_BP_Benefitting_Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RWE_Country__c</fullName>
        <label>RWE Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>RWE_BP_Benefitting_Regions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BP Benefitting Country</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>BP Benefitting Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BP Benefitting Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TPO_Location__c.object
<CustomObject>
    <label>TPO Location</label>
    <nameField>
        <label>TPO Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPO Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateBPController.cls
/******************************************************************************************************************************************
 * Class Name   : CreateBPController
 * Description  : controller class for CreateBP page
 * Created By   : Deloitte Consulting
 *
 *****************************************************************************************************************************************/
Public with sharing class CreateBPController {
    public Business_Planning__c oBP {get; set;}
    public BP_Molecule__c oBPMolecule {get; set;}
    Public BP_Proposed_TPO__c oBPTPO {get;set;}
    public RWE_BP_Benefitting_Region__c oBPBenefitingCountry {get; set;}
    public list<BP_Molecule__c> lBPMolecules {get; set;}
    Public list<BP_Proposed_TPO__c> lBPTPOs {get;set;}
    public list<RWE_BP_Benefitting_Region__c> lBPBenefitingCountries {get; set;}
    public BPRelated_Data_Asset__c oRelatedDataAsset {get; set;}
    public list < BPRelated_Data_Asset__c > lRelatedDataAsset {get; set;}
    public boolean isError {get; set;}
    public boolean isMoleculeError {get; set;}
    Public boolean isProposedTPO {get;set;}
    public boolean isBPBnftCError {get; set;}
    public boolean isRelatedDataAssetError {get; set;}

    public id genericID {get; set;}
    public id currentRecordID;
    public string currentBPType {get; set;}

    //Loading the Constructor
    public CreateBPController(ApexPages.StandardController controller) {
        currentBPType = ApexPages.currentPage().getParameters().get('BPType');
        currentRecordID = ApexPages.currentPage().getParameters().get('id');

        isMoleculeError = false;
        isProposedTPO = false;
        isBPBnftCError = false;
        isRelatedDataAssetError = false;

        if (currentRecordID != Null) {
            //Querying Molecules, Benifiting countries and BP Conducting countries for the current BP
            oBPMolecule = new BP_Molecule__c();
            oBPTPO = new BP_Proposed_TPO__c();
            oBPBenefitingCountry = new RWE_BP_Benefitting_Region__c();
            oRelatedDataAsset = new BPRelated_Data_Asset__c();
            lBPMolecules = new list <BP_Molecule__c> ();
            lBPTPOs = new list<BP_Proposed_TPO__c>();
            lBPBenefitingCountries = new list <RWE_BP_Benefitting_Region__c> ();
            lRelatedDataAsset = new list < BPRelated_Data_Asset__c > ();

            lBPBenefitingCountries = [select id, RWE_Country__c, RWE_Country__r.Name, RWE_Business_Planning__r.name from RWE_BP_Benefitting_Region__c Where RWE_Business_Planning__c = : currentRecordID];
            lBPMolecules = [select id, RWE_Molecule__c, RWE_Molecule__r.name, RWE_Business_Planning__r.name from BP_Molecule__c Where RWE_Business_Planning__c = : currentRecordID];
            lBPTPOs = [select id, RWE_TPO_Location__c, RWE_TPO_Location__r.name, RWE_Business_Planning__r.name from BP_Proposed_TPO__c Where RWE_Business_Planning__c = : currentRecordID];
            lRelatedDataAsset = [select id, RWD_Data_Asset__c, RWD_Data_Asset__r.name from BPRelated_Data_Asset__c Where RWE_Business_Planning__c = : currentRecordID];

            String SobjectApiName = 'Business_Planning__c';
            Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
            Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();

            String commaSeparatedFields = '';
            for (String fieldName : fieldMap.keyset()) {
                if (commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } else {
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }

            string query = 'select ' + commaSeparatedFields + ' from ' + SobjectApiName + ' where id =\'' + currentRecordID + '\' limit 1';
            oBP = Database.query(query);
            if (oBP.BPType__c == 'Research Project') {
                currentBPType = 'Research_BP';
            } else if (oBP.BPType__c == 'Non-Research Project') {
                currentBPType = 'Non_Research_BP';
            } else {
                currentBPType = 'Study_BP';
            }

        }

        else {
            oBP = new Business_Planning__c();
            if (currentBPType == 'Research_BP') {
                oBP.BPType__c = 'Research Project';
            } else if (currentBPType == 'Non_Research_BP') {
                oBP.BPType__c = 'Non-Research Project';
            } else {
                oBP.BPType__c = 'Study';
            }
        }
    }

    /*
     * @Method Name                    :  save
     * @Description                    :  Method to Save the Business Plan record
     * @Return Type                    :  PageReference
     * @Parameters                     :  None
     */
    public PageReference save() {

        list<BPRelated_Data_Asset__c > lBPRelatedDataAssets = new list<BPRelated_Data_Asset__c >();
        lBPRelatedDataAssets = [select id from BPRelated_Data_Asset__c Where RWE_Business_Planning__c = :currentRecordID];
           If(oBP.Is_the_Data_Asset_Known__c == 'Yes' && lBPRelatedDataAssets.size() == 0 ) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please add Related Data Assets to your Business Planning.');
                ApexPages.addMessage(myMsg);
                isError = TRUE;
                return null;
            }
                
        pagereference pageref;
        try {
            if (oBP.BPType__c == 'Research Project') {
                currentBPType = 'Research_BP';
            } else if (oBP.BPType__c == 'Non-Research Project') {
                currentBPType = 'Non_Research_BP';
            } else {
                currentBPType = 'Study_BP';
            }
            upsert oBP oBP.id;


            if (currentRecordID == NULL) {
                pageref = new pagereference('/apex/CreateBP?id=' + oBP.id + '&BPType=' + currentBPType + '&isEdit=true&AutoDistribute=true');

            } else {
                pageref = new pagereference('/apex/CreateBP?id=' + oBP.id + '&BPType=' + currentBPType + '&isEdit=false');
            }

            /*Creating Estimates when the BP is created for the First Time
            If(ApexPages.currentPage().getParameters().get('AutoDistribute') == 'true') {
                BPAutoDistribute.PassBusinessEstimates(oBp);
            }*/
            pageref.setredirect(true);
        } catch (exception e) {
            String error = e.getdmlMessage(0);
            addError(error);
            isError = TRUE;
            return null;
        }
        return pageref;
    }


    /*
        * @Method Name                    :  AddMolecule
        * @Description                    :  Method to add a new BP Molecule
        * @Return Type                    :  void
        * @Parameters                     :  None
        */
    Public void AddMolecule() {
        if (currentRecordID != NULL) {
            try {
                oBPMolecule.RWE_Business_Planning__c = currentRecordID;
                insert oBPMolecule;
                lBPMolecules = [select id, RWE_Molecule__c, RWE_Molecule__r.name from BP_Molecule__c Where RWE_Business_Planning__c = : currentRecordID];
                oBPMolecule = new BP_Molecule__c();
            } catch (exception e) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'There was an error adding Molecule. Please contact your Administrator');
                ApexPages.addMessage(myMsg);
                isMoleculeError = true;
            }
        }
    }
   
    /*
     * @Method Name                    :  RemoveMolecule
     * @Description                    :  Method to remove a BP Molecule
     * @Return Type                    :  void
     * @Parameters                     :  None
     */

    Public void RemoveMolecule() {
        try {
            lBPMolecules = [select id, RWE_Molecule__c, RWE_Molecule__r.name from BP_Molecule__c Where RWE_Business_Planning__c = : currentRecordID];
            BP_Molecule__c oMol = [Select id from BP_Molecule__c where RWE_Business_Planning__c = : currentRecordID AND RWE_Molecule__c = : genericID];
            delete oMol;
            lBPMolecules = [select id, RWE_Molecule__c, RWE_Molecule__r.name from BP_Molecule__c Where RWE_Business_Planning__c = : currentRecordID];
        } catch (exception e) {
            addError(e.getmessage());
            isMoleculeError = true;
        }

    }

     /*
        * @Method Name                    :  AddTPO
        * @Description                    :  Method to add a new TPO Location
        * @Return Type                    :  void
        * @Parameters                     :  None
        */
    Public void AddTPO() {
        if (currentRecordID != NULL) {
            try {
                oBPTPO.RWE_Business_Planning__c = currentRecordID;
                insert oBPTPO;
                lBPTPOs = [select id, RWE_TPO_Location__c, RWE_TPO_Location__r.name from BP_Proposed_TPO__c Where RWE_Business_Planning__c = : currentRecordID];
                oBPTPO = new BP_Proposed_TPO__c();
            } catch (exception e) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'There was an error adding TPO. Please contact your Administrator');
                ApexPages.addMessage(myMsg);
                isProposedTPO = true;
            }
        }
    }
    /*
     * @Method Name                    :  RemoveBPTPO
     * @Description                    :  Method to remove a TPO Location
     * @Return Type                    :  void
     * @Parameters                     :  None
     */

    Public void RemoveBPTPO() {
        try {
            lBPTPOs = [select id, RWE_TPO_Location__c, RWE_TPO_Location__r.name from BP_Proposed_TPO__c Where RWE_Business_Planning__c = : currentRecordID];
            BP_Proposed_TPO__c oBPProTPO = [Select id from BP_Proposed_TPO__c where RWE_Business_Planning__c = : currentRecordID AND RWE_TPO_Location__c = : genericID];
            delete oBPProTPO;
            lBPTPOs = [select id, RWE_TPO_Location__c, RWE_TPO_Location__r.name from BP_Proposed_TPO__c Where RWE_Business_Planning__c = : currentRecordID];
        } catch (exception e) {
            addError(e.getmessage());
            isProposedTPO = true;
        }

    }
    
    /*
    * @Method Name                    :  AddBPBenefitingCountry
    * @Description                    :  Method to add a new Benefiting Country to a BP
    * @Return Type                    :  void
    * @Parameters                     :  None
    */
    Public void AddBPBenefitingCountry() {
        if (currentRecordID != NULL) {
            try {
                oBPBenefitingCountry.RWE_Business_Planning__c = currentRecordID;
                insert oBPBenefitingCountry;
                lBPBenefitingCountries = [select id, RWE_Country__c, RWE_Country__r.name from RWE_BP_Benefitting_Region__c Where RWE_Business_Planning__c = : currentRecordID];
                oBPBenefitingCountry = new RWE_BP_Benefitting_Region__c();
            } catch (exception e) {    
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'There was an error adding country. Please contact your Administrator');
                ApexPages.addMessage(myMsg);
                isBPBnftCError = true;
            }
        }
    }
    /*
     * @Method Name                    :  RemoveBPBenefitingCountry
     * @Description                    :  Method to remove a BP Benefiting Country
     * @Return Type                    :  void
     * @Parameters                     :  None
     */

    Public void RemoveBPBenefitingCountry() {
        try {
            lBPBenefitingCountries = [select id, RWE_Country__c, RWE_Country__r.name from RWE_BP_Benefitting_Region__c Where RWE_Business_Planning__c = : currentRecordID];
            RWE_BP_Benefitting_Region__c oBPBnftC = [Select id from RWE_BP_Benefitting_Region__c where RWE_Business_Planning__c = : currentRecordID AND RWE_Country__c = : genericID];
            delete oBPBnftC;
            lBPBenefitingCountries = [select id, RWE_Country__c, RWE_Country__r.name from RWE_BP_Benefitting_Region__c Where RWE_Business_Planning__c = : currentRecordID];
        } catch (exception e) {
            addError(e.getmessage());
            isBPBnftCError = true;
        }

    }

    /*
             * @Method Name                    :  AddRelatedDataAsset
             * @Description                    :  Method to add a new BP Related Data Asset
             * @Return Type                    :  void
             * @Parameters                     :  None
             */
    Public void AddRelatedDataAsset() {
        if (currentRecordID != NULL) {
            try {
                oRelatedDataAsset.RWE_Business_Planning__c = currentRecordID;
                insert oRelatedDataAsset;
                lRelatedDataAsset = [select id, RWD_Data_Asset__c, RWD_Data_Asset__r.name from BPRelated_Data_Asset__c Where RWE_Business_Planning__c = : currentRecordID];
                oRelatedDataAsset = new BPRelated_Data_Asset__c();
            } catch (exception e) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'There was an error adding Data Asset. Please Contact your Administrator ');
                ApexPages.addMessage(myMsg);
                isRelatedDataAssetError = true;
            }
        }
    }
    /*
     * @Method Name                    :  RemoveRelatedDataAsset
     * @Description                    :  Method to remove a BP Related Data Asset
     * @Return Type                    :  void
     * @Parameters                     :  None
     */

    Public void RemoveRelatedDataAsset() {
        try {

            lRelatedDataAsset = [select id, RWD_Data_Asset__c, RWD_Data_Asset__r.name from BPRelated_Data_Asset__c Where RWE_Business_Planning__c = : currentRecordID];

            BPRelated_Data_Asset__c oRelDataAsset = [Select id from BPRelated_Data_Asset__c where RWE_Business_Planning__c = : currentRecordID AND RWD_Data_Asset__c = : genericID];
            delete oRelDataAsset;

            lRelatedDataAsset = [select id, RWD_Data_Asset__c, RWD_Data_Asset__r.name from BPRelated_Data_Asset__c Where RWE_Business_Planning__c = : currentRecordID];

        } catch (exception e) {
            addError(e.getmessage());
            isRelatedDataAssetError = true;
        }

    }

    /*
     * @Method Name                    :  addError
     * @Description                    :  Method for adding apex error
     * @Return Type                    :  void
     * @Parameters                     :  string
     */
    public void addError(string s) {
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, s);
        ApexPages.addMessage(myMsg);
    }


    /*
     * @Method Name                    :  ResetGPORWE
     * @Description                    :  Method for Resetting GPORWE_Functional_Area__c field
     * @Return Type                    :  void
     * @Parameters                     :  none
     */
    public void ResetGPORWE() {
        oBP.GPORWE_Functional_Area__c = NULL;
    }

    /*
     * @Method Name                    :  EditRecord
     * @Description                    :  Method for editing and existing BP record
     * @Return Type                    :  PageReference
     * @Parameters                     :  None
     */
    public PageReference EditRecord() {
        pagereference pageref = new pagereference('/apex/CreateBP?id=' + currentRecordID + '&BPType=' + currentBPType + '&isEdit=true');
        pageref.setredirect(true);
        return pageref;
    }


}