src/objects/Business_Planning__c.object
<CustomObject>
    <label>Business Planning</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study/Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Planning</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Business_Planning_Estimate__c.object
<CustomObject>
    <fields>
        <fullName>Business_Planning_ID__c</fullName>
        <label>Business Planning ID</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipName>RWE_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Plan Forecast</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Forecast ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Plan Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BusinessForecast_TriggerHandler.cls
/******************************************************************************************************************************************
 * Class Name   : BusinessForecast_TriggerHandler
 * Description  : Handler Class for BP Forecast Object
 * Created By   : Deloitte Consulting
 *
 *****************************************************************************************************************************************/
Public with sharing class BusinessForecast_TriggerHandler {

    /*
     * @Method Name                    :  preventDelete
     * @Description                    :  Method to Preventing deleting of locked forecast records 
     * @Return Type                    :  void
     * @Parameters                     :  List < Business_Planning__c>
     */

    Public static void preventDelete(List < Business_Planning_Estimate__c > lEstimates) {
        Map<Id,Boolean> mBps = new Map<Id,Boolean>();
        Set<Id> sBpIds = new Set<Id>();
        For(Business_Planning_Estimate__c oEstimate: lEstimates){
            sBpIds.add(oEstimate.Business_Planning_ID__c);            
        }
    }
}