src/objects/Business_Planning__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Contracted_Budget__c</fullName>
        <label>Actual Contracted Budget</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_budget_estimate_for_each_item__c</fullName>
        <inlineHelpText>Enter the estimated cost of the study/project.  See the related Budget Estimate Guidance for further information on typical study costs.</inlineHelpText>
        <label>Budget Estimate</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>Enter a descriptive title for the item (e.g. one that might be used for a journal article)</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business Planning</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study/Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Planning</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Business_Planning_Estimate__c.object
<CustomObject>
    <fields>
        <fullName>Business_Planning_ID__c</fullName>
        <label>Business Planning ID</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipName>RWE_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimate_Amount__c</fullName>
        <label>Estimated Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimate_Date__c</fullName>
        <label>Estimated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <formula>CASE(MONTH(  Estimate_Date__c ), 
1, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q1&quot; , 
2, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q1&quot;, 
3, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q1&quot;, 
4, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q2&quot;, 
5, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q2&quot;, 
6, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q2&quot;, 
7, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q3&quot;, 
8, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q3&quot;, 
9, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q3&quot;, 
10, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q4&quot;, 
11, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q4&quot;, 
12, TEXT(YEAR(Estimate_Date__c))&amp;&quot;-Q4&quot;, 
&quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Quarter</label>
        <type>Text</type>
    </fields>
    <label>Business Plan Forecast</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Forecast ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Plan Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operational_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Actual_amount__c</fullName>
        <label>Actual Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Acutal_Date_of_payment__c</fullName>
        <label>Actual Date of Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Business_Planning_ID__c</fullName>
        <label>Business Planning ID</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipName>RWE_Business_Planning_Financials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contracted_Amount__c</fullName>
        <label>Contracted Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contracted_Date_of_Payment__c</fullName>
        <label>Contracted Date of Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimate_amount__c</fullName>
        <label>Forecast Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Date_of_payment__c</fullName>
        <label>Forecast Date of Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HCP_ID__c</fullName>
        <defaultValue>&quot;N/A&quot;</defaultValue>
        <label>HCP ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_Category__c</fullName>
        <label>Milestone Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Payment</fullName>
                </value>
                <value>
                    <fullName>Kickoff</fullName>
                </value>
                <value>
                    <fullName>Protocol Draft</fullName>
                </value>
                <value>
                    <fullName>Protocol Final</fullName>
                </value>
                <value>
                    <fullName>IRB/ERB Approval</fullName>
                </value>
                <value>
                    <fullName>Consent Forms</fullName>
                </value>
                <value>
                    <fullName>HCP Professional Services</fullName>
                </value>
                <value>
                    <fullName>HCP Consulting</fullName>
                </value>
                <value>
                    <fullName>HCP Payment Other</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>TFLs</fullName>
                </value>
                <value>
                    <fullName>Data Collection</fullName>
                </value>
                <value>
                    <fullName>Data Analysis</fullName>
                </value>
                <value>
                    <fullName>Draft Deliverable</fullName>
                </value>
                <value>
                    <fullName>Final Deliverable</fullName>
                </value>
                <value>
                    <fullName>Medical Writing</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Project Planning</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Pass Thru</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quarter_Actuals__c</fullName>
        <formula>CASE(MONTH(  Acutal_Date_of_payment__c ), 
1, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q1&quot; , 
2, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q1&quot;, 
3, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q1&quot;, 
4, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q2&quot;, 
5, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q2&quot;, 
6, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q2&quot;, 
7, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q3&quot;, 
8, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q3&quot;, 
9, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q3&quot;, 
10, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q4&quot;, 
11, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q4&quot;, 
12, TEXT(YEAR(Acutal_Date_of_payment__c ))&amp;&quot;-Q4&quot;, 
&quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quarter (Actuals)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quarter_Contracted__c</fullName>
        <formula>CASE(MONTH( Contracted_Date_of_Payment__c), 
1, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q1&quot; , 
2, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q1&quot;, 
3, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q1&quot;, 
4, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q2&quot;, 
5, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q2&quot;, 
6, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q2&quot;, 
7, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q3&quot;, 
8, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q3&quot;, 
9, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q3&quot;, 
10, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q4&quot;, 
11, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q4&quot;, 
12, TEXT(YEAR(Contracted_Date_of_Payment__c))&amp;&quot;-Q4&quot;, 
&quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quarter (Contracted)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quarter_Estimate__c</fullName>
        <formula>CASE(MONTH( Estimated_Date_of_payment__c ), 
1, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q1&quot;, 
2, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q1&quot;, 
3, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q1&quot;, 
4, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q2&quot;, 
5, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q2&quot;, 
6, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q2&quot;, 
7, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q3&quot;, 
8, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q3&quot;, 
9, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q3&quot;, 
10, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q4&quot;, 
11, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q4&quot;, 
12, TEXT(YEAR(Estimated_Date_of_payment__c ))&amp;&quot;-Q4&quot;, 
&quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quarter (Forecast)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Milestone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variance_Comments__c</fullName>
        <label>Variance Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Variance_Reason__c</fullName>
        <label>Variance Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strategic in our control</fullName>
                </value>
                <value>
                    <fullName>Strategic out of our control</fullName>
                </value>
                <value>
                    <fullName>Operational in our control</fullName>
                </value>
                <value>
                    <fullName>Operational out of our control</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variance__c</fullName>
        <description>difference between the contracted amount and the actual amount (Actual Amount - Contracted Amount)</description>
        <formula>Actual_amount__c-Contracted_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Actual</label>
    <nameField>
        <displayFormat>FN-{0000}</displayFormat>
        <label>Forecast Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EditBPForecastsController.cls
/******************************************************************************************************************************************
 * Class Name   : EditBPForecastsController
 * Description  : Class to Edit Business Planning Forecasts & Operational Forecasts of a BP.
 * Created By   : Deloitte Consulting
 *
 *****************************************************************************************************************************************/
Public with sharing class EditBPForecastsController {


    Public Business_Planning__c oBusinessPlanning {get; set;}
    Public List <Business_Planning_Estimate__c> lBPForecasts {get; set;}
    Public List <Operational_Tracking__c> lOperationalForecasts {get; set;}
    Public Decimal dConversionRate {get; set;}
    Public string sISOCode {get; set;}
    Public List < SelectOption > lChoice {get; set;}
    Public string sChoice {get; set;}
    Public decimal sumBPFEstimate {get; set;}
    Public decimal sumOPFActual {get; set;}
    Public decimal sumOPFEstimate {get; set;}
    Public decimal sumOPFContracted {get; set;}
    Public Boolean IsError {get; set;}


    //Initialising the Controller
    Public EditBPForecastsController () {
        /* List<CurrencyType> lCurrency = new List<CurrencyType>([SELECT IsoCode, ConversionRate FROM CurrencyType where IsoCode = : userinfo.getDefaultCurrency()]);
        sISOCode = lCurrency[0].IsoCode;
        dConversionRate = lCurrency[0].ConversionRate; */
        IsError = FALSE;
        ID currentBPID = Apexpages.currentpage().getparameters().get('id');
        lChoice = new List < SelectOption > { new SelectOption( 'BPF', 'Business Plan Forecasts'), new Selectoption('OPF', 'Operational Forecasts')};
        if (Apexpages.currentpage().getparameters().get('type') != NULL) {
            schoice = Apexpages.currentpage().getparameters().get('type');
        } else {
            schoice = 'OPF';
        }
        if (currentBPID != null) {
            oBusinessPlanning = new Business_Planning__c();
            oBusinessPlanning = [Select id, /*CurrencyIsoCode,*/ Name, Actual_Contracted_Budget__c, Initial_budget_estimate_for_each_item__c from Business_Planning__c where Id = :currentBPID];
            DisplayForecasts();
        } else {
            IsError = TRUE;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Business Planning record ID not mentioned in the URL.'));
        }

    }

    /*
     * @Method Name                    :  DisplayForecasts
     * @Description                    :  This Method Queries the Child Related list records of the BP to display
     * @Return Type                    :  void
     * @Parameters                     :  None
     */
    public void DisplayForecasts() {
    lBPForecasts = new List <Business_Planning_Estimate__c>();
    lOperationalForecasts = new List <Operational_Tracking__c>();
        if (sChoice == 'BPF') {
           
                lBPForecasts = [select id, Name, /*CurrencyIsoCode,*/ Business_Planning_ID__c, /*Business_Planning_ID__r.CurrencyIsoCode, */Business_Planning_ID__r.Initial_budget_estimate_for_each_item__c, Estimate_Amount__c, Estimate_Date__c,
                                Quarter__c from Business_Planning_Estimate__c where Business_Planning_ID__c = :oBusinessPlanning.id order by Quarter__c];

                List<Business_Planning_Estimate__c> lBPForecastsConverted = new List<Business_Planning_Estimate__c>();
                lBPForecastsConverted = [Select convertCurrency(Estimate_Amount__c) from Business_Planning_Estimate__c where Business_Planning_ID__c = :oBusinessPlanning.id order by Quarter__c];
                sumBPFEstimate = 0;
                For(Business_Planning_Estimate__c oForecasts : lBPForecastsConverted){
                    If(oForecasts.Estimate_Amount__c != NULL){
                        sumBPFEstimate = sumBPFEstimate + oForecasts.Estimate_Amount__c;
                    }   
                }
            
            
        } else if (sChoice == 'OPF') {
            lOperationalForecasts = [select id, Milestone_Category__c, Title__c, HCP_ID__c, /*CurrencyIsoCode,*/ Name, Actual_amount__c, Acutal_Date_of_payment__c, Business_Planning_ID__c, /*Business_Planning_ID__r.CurrencyIsoCode, */Business_Planning_ID__r.Initial_budget_estimate_for_each_item__c,
                                     Business_Planning_ID__r.Actual_Contracted_Budget__c, Contracted_Amount__c, Contracted_Date_of_Payment__c, Estimate_amount__c, Estimated_Date_of_payment__c,
                                     Quarter_Actuals__c, Quarter_Contracted__c, Quarter_Estimate__c, Variance__c, Variance_Comments__c, Variance_Reason__c
                                     from Operational_Tracking__c where Business_Planning_ID__c = :oBusinessPlanning.id order by Quarter_Estimate__c ];
    
            List<Operational_Tracking__c> lOperationalForecastsConverted = new List<Operational_Tracking__c>();
            lOperationalForecastsConverted = [select convertCurrency(Actual_amount__c),convertCurrency(Contracted_Amount__c),convertCurrency(Estimate_amount__c)
                                     from Operational_Tracking__c where Business_Planning_ID__c = :oBusinessPlanning.id order by Quarter_Estimate__c ];

            sumOPFEstimate = 0;
            For(Operational_Tracking__c oTracking : lOperationalForecastsConverted){
                If(oTracking.Estimate_amount__c != NULL){
                    sumOPFEstimate = sumOPFEstimate + oTracking.Estimate_amount__c;
                }   
            }
            
            sumOPFActual = 0;
            For(Operational_Tracking__c oTracking : lOperationalForecastsConverted){
                If(oTracking.Actual_amount__c!= NULL){
                    sumOPFActual = sumOPFActual + oTracking.Actual_amount__c;
                }   
            }
            
            sumOPFContracted = 0;
            For(Operational_Tracking__c oTracking : lOperationalForecastsConverted){
                If(oTracking.Contracted_Amount__c!= NULL){
                    sumOPFContracted = sumOPFContracted + oTracking.Contracted_Amount__c;
                }   
            }
        }
    }
    
     /*
     * @Method Name                    :  addError
     * @Description                    :  Method for adding apex error
     * @Return Type                    :  void
     * @Parameters                     :  string
     */
    public void addError(string s) {
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, s);
        ApexPages.addMessage(myMsg);
    }
    

    /*
     * @Method Name                    :  UpdateForecasts
     * @Description                    :  This Method Updates the respective Child Related list records of BP
     * @Return Type                    :  void
     * @Parameters                     :  None
     */
    public void UpdateForecasts() {
        try{
        if (sChoice == 'BPF') {
            if (lBPForecasts != null) {
                update lBPForecasts;
            }
        } else if (sChoice == 'OPF') {
            if (lOperationalForecasts != null) {
                update lOperationalForecasts;
            }
        }
        DisplayForecasts();
        } catch (exception e) {
            String error = e.getdmlMessage(0);
            addError(error);
            isError = TRUE;
        }
    }
}