src/objects/Business_Planning__c.object
<CustomObject>
    <fields>
        <fullName>Business_Planning_Approval_Status__c</fullName>
        <label>Business Planning Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Discussion</fullName>
                    <color>#0B6FCE</color>
                    <label>In Discussion</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                    <color>#78C953</color>
                    <label>Ready for Approval</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                    <color>#E27001</color>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <color>#A845DC</color>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Approved/Reprioritize</fullName>
                    <color>#F3D904</color>
                    <label>Approved/Reprioritize</label>
                </value>
                <value>
                    <fullName>In-Waiting</fullName>
                    <color>#A53711</color>
                    <label>In-Waiting</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <color>#66E9BD</color>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#0B24BE</color>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Submitted for BP Approval</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Submitted for BP session</fullName>
                </value>
                <value>
                    <fullName>BP Review Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsEmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubmit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSubmit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Prevents any changes to the item. Item must be frozen before changing to &quot;Ready for Approval&quot;</inlineHelpText>
        <label>Freeze</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Add the Project Manager or facilitator that supports your area.  Their name will be added to the study team by adding it to this field.</inlineHelpText>
        <label>PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Business_Plannings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Planning</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study/Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Planning</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BPFieldChanges.cls
Public class BPFieldChanges{
    
    Public Set<PermissionSetAssignment> UserPermission = new Set<PermissionSetAssignment>();

    public BPFieldChanges(ApexPages.StandardController controller) {
        UserPermission = new Set<PermissionSetAssignment>([SELECT PermissionSet.Name FROM PermissionSetAssignment WHERE AssigneeId = :Userinfo.getUserId()]);
    }

    
    Public pageReference changeStatusOnSubmit(){
        Id UserId = UserInfo.getUserId();  
        Id BpID = ApexPages.currentPage().getParameters().get('Id');
        boolean isBpAdmin = false;  
        
        For(PermissionSetAssignment pa : UserPermission){
            if(pa.PermissionSet.Name == 'Business_Admin'){
                isBpAdmin = true;
            }
        }
        
        Business_Planning__c bp = new Business_Planning__c();
        bp = [Select id,Business_Planning_Approval_Status__c,OwnerId,PM__c From Business_Planning__c where Id=:BpID Limit 1];
        
        If(bp.Business_Planning_Approval_Status__c =='In Process'){
            bp.Business_Planning_Approval_Status__c ='Submitted for BP Approval';
            bp.IsSubmit__c = true;
           // bp.IsEmail__c=true;
            update bp;
        }else if(isBpAdmin && bp.Business_Planning_Approval_Status__c =='In Review'){
            bp.Business_Planning_Approval_Status__c ='Submitted for BP session';
            bp.IsSubmit__c = true;
            //bp.IsEmail__c=true;
            update bp;
            
        }else if(isBpAdmin && bp.Business_Planning_Approval_Status__c =='BP review in process'){
            List<Business_Planning__c> lBp = new List<Business_Planning__c>();
            bp.Business_Planning_Approval_Status__c = 'BP Review Period';
            //bp.IsEmail__c=false;
            update bp;
            
            lBp.add(bp);
            
            ApexPages.StandardSetController sc = new ApexPages.StandardSetController(lBp);        
            SubmitBPApproval submitBp = new SubmitBPApproval(sc);
            submitBp.Submit();
            //bp.Lock__c=true;
        }
        
        return new pageReference('/'+BpID);
    }
    
}