src/objects/Business_Planning__c.object
<CustomObject>
    <fields>
        <fullName>Business_Planning_Approval_Status__c</fullName>
        <label>Business Planning Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Discussion</fullName>
                    <color>#0B6FCE</color>
                    <label>In Discussion</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                    <color>#78C953</color>
                    <label>Ready for Approval</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                    <color>#E27001</color>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <color>#A845DC</color>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Approved/Reprioritize</fullName>
                    <color>#F3D904</color>
                    <label>Approved/Reprioritize</label>
                </value>
                <value>
                    <fullName>In-Waiting</fullName>
                    <color>#A53711</color>
                    <label>In-Waiting</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <color>#66E9BD</color>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#0B24BE</color>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Submitted for BP Approval</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Submitted for BP session</fullName>
                </value>
                <value>
                    <fullName>BP Review Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Add the Project Manager or facilitator that supports your area.  Their name will be added to the study team by adding it to this field.</inlineHelpText>
        <label>PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Business_Plannings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Planning</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study/Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Planning</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubmitBPApproval.cls
/****************************************************************************************************************************************** 
 * Class Name   : SubmitBPApproval 
 * Description  : Class to Submit BP Items for Approval from List View
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with sharing class SubmitBPApproval {
    Private ApexPages.StandardSetController standardController;
    Public Boolean bIsBPAdmin {
        get;
        set;
    }
    Public List < wPlanning > lwPlanning {
        get;
        set;
    }
    Public Integer ErrorCount;
    Public String sRetUrl;

    Public SubmitBPApproval(ApexPages.StandardSetController standardController) {
        this.standardController = standardController;
        ErrorCount = 0;
        sRetUrl = ApexPages.currentPage().getParameters().get('retURL');
        
        //Allowing only Admins to Access the Functionality of Submitting the BP Items for Approvals. 
        List < PermissionSetAssignment > lPermissionsetCheck = [SELECT Id, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = : userinfo.getuserID() and(PermissionSet.name like: '%Business_Admi%'
            OR PermissionSet.name like: '%RWE_Pangaea_Support%'
            OR PermissionSet.name like: '%RWE_Admin%')];
        if (lPermissionsetCheck.size() > 0) {
            bIsBPAdmin = true;
        }

        if(!Test.isRunningTest()){
        
           /* standardController.addFields(
            new list < string > {
                'Business_Planning_Approval_Status__c',
                'PM__c'
            }
            );*/
        
        }

        lwPlanning = new List < wPlanning > ();

    }
    
     /* 
     * @Method Name                    :  Submit
     * @Description                    :  Method to Submit Bp Items which match the criteria
     * @Return Type                    :  String
     * @Parameters                     :  None
     */

    Public String Submit() {

        If(bIsBPAdmin == TRUE) {
            List < Business_Planning__c > lPlanning = new List < Business_Planning__c > ();

            lPlanning = (List < Business_Planning__c > ) standardController.getSelected();

            If(lPlanning.IsEmpty()) {
                lPlanning = (List < Business_Planning__c > ) standardController.getRecords();
            }
            Set < Id > sInstanceId = new Set < Id > ();

            //Getting a list of records which are already in Approval Process
            List < ProcessInstance > lInstance = [Select TargetObjectId, Status from ProcessInstance where TargetObjectId IN: lPlanning AND Status != 'Rejected' AND Status != 'Removed'];
            For(ProcessInstance oInstance: lInstance) {
                sInstanceId.add(oInstance.TargetObjectId);
            }

            // Create an approval request for the BP
            List<Approval.ProcessSubmitRequest> lrequests = new List<Approval.ProcessSubmitRequest>();
            for (Business_Planning__c oBusiness: lPlanning) {
                if (oBusiness.Business_Planning_Approval_Status__c == 'BP Review Period' && !sInstanceId.contains(oBusiness.Id) && bIsBPAdmin == TRUE) {
                    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                    req.setComments('Request Submitted for Approval');
                    req.setObjectId(oBusiness.Id);

                    // Submit the approval request for the BP
                    lrequests.add(req);
                }
                Else If(sInstanceId.contains(oBusiness.Id)) {
                    lwPlanning.add(new wPlanning(oBusiness, 'Record is Already in the Approval Process'));
                    ErrorCount++;
                }
                Else {
                    lwPlanning.add(new wPlanning(oBusiness, 'Cannot Submit for Approval. Criteria Not Met.'));
                    ErrorCount++;
                }
            }
            Approval.ProcessResult[] processResults = null;
            processResults = Approval.process(lrequests, false);
            for (Business_Planning__c oBusiness: lPlanning) {
                for(Integer i=0;i<processResults.size();i++){
                    if(processResults[i].getEntityId() == oBusiness.Id){
                        if(processResults[i].isSuccess()){
                            lwPlanning.add(new wPlanning(oBusiness, 'Record Successfully Submitted for Approval'));    
                        }
                        else{
                            lwPlanning.add(new wPlanning(oBusiness, 'There was an Error Submitting the Record for Approval. Please Contact your Administrator.'));
                        }
                    }
                }
            }
            If(ErrorCount == 0) {
                return sRetUrl;
            }
            Else {
                return null;
            }
        }
        Else {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: Only Administrators can Submit Business Planning Items for Approval.');
            ApexPages.addMessage(myMsg);
            return null;
        }
    }
    
    /* 
     * @Method Name                    :  Back
     * @Description                    :  Method to Navigate back to the List View
     * @Return Type                    :  String
     * @Parameters                     :  None
     */
    

    Public String Back() {
        return sRetUrl;
    }

    //Wrapper Class to Hold the BP Items and its errors messages.

    Public Class wPlanning {
        Public Business_Planning__c oPlanning {
            get;
            set;
        }
        Public String sMsg {
            get;
            set;
        }
        Public wPlanning(Business_Planning__c P, String M) {
            oPlanning = P;
            sMsg = M;
        }
    }
}