src/objects/Business_Planning__c.object
<CustomObject>
    <label>Business Planning</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study/Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Planning</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Business_Planning_Estimate__c.object
<CustomObject>
    <fields>
        <fullName>Business_Planning_ID__c</fullName>
        <label>Business Planning ID</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipName>RWE_Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimate_Amount__c</fullName>
        <label>Estimated Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimate_Date__c</fullName>
        <label>Estimated Date</label>
        <type>Date</type>
    </fields>
    <label>Business Plan Forecast</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Forecast ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Plan Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLBL_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date and time this error occurred</description>
        <inlineHelpText>The date and time this error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message produced by this error</description>
        <inlineHelpText>The error message produced by this error</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The running user for this error</description>
        <inlineHelpText>The running user for this error</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GLBL_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>The system stack trace for this error, if one exists</description>
        <inlineHelpText>The system stack trace for this error, if one exists</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operational_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Business_Planning_ID__c</fullName>
        <label>Business Planning ID</label>
        <referenceTo>Business_Planning__c</referenceTo>
        <relationshipName>RWE_Business_Planning_Financials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimate_amount__c</fullName>
        <label>Forecast Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Date_of_payment__c</fullName>
        <label>Forecast Date of Payment</label>
        <type>Date</type>
    </fields>
    <label>Actual</label>
    <nameField>
        <displayFormat>FN-{0000}</displayFormat>
        <label>Forecast Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BPCreateOperationalForecasts.cls
/****************************************************************************************************************************************** 
 * Class Name   : BPCreateOperationalForecasts
 * Description  : Class for Creating Operational Forecasts Records from Estimates
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with Sharing Class BPCreateOperationalForecasts {
    Public Id BusinessPlanningId;
    Public Boolean IsError{get;set;}
    //Loading the Constructor
    Public BPCreateOperationalForecasts() {
        BusinessPlanningId = ApexPages.currentPage().getParameters().get('id');
        IsError = FALSE;
    }

    /* 
     * @Method Name                    :  CreateOperationalForecast
     * @Description                    :  Method to call the PassOperationalForecast method and return back to orginal record
     * @Return Type                    :  PageReference
     * @Parameters                     :  None
     */

    Public PageReference CreateOperationalForecast() {
        PassOperationalForecast(BusinessPlanningId);
        PageReference BpUrl = new PageReference('/' +BusinessPlanningId);
        If(IsError == FALSE){
            return BpUrl;
        }
        Else{
            return null;
        }
    }


    /* 
     * @Method Name                    :  PassOperationalForecast
     * @Description                    :  Method to Copy Estimates to Operational Forecast
     * @Return Type                    :  Business_Planning__c 
     * @Parameters                     :  None
     */

    Public void PassOperationalForecast(Id oBp) {
        Try{
            List < Business_Planning_Estimate__c > lPlanningEstimates = new List < Business_Planning_Estimate__c > ();
            lPlanningEstimates = [Select Id, Estimate_Amount__c, Estimate_Date__c, Business_Planning_ID__c from Business_Planning_Estimate__c where Business_Planning_ID__c = : oBp];
    
            List < Operational_Tracking__c > lTracking = new List < Operational_Tracking__c > ();
            lTracking = [Select Id, Business_Planning_ID__c from Operational_Tracking__c where Business_Planning_ID__c = : oBp];
            Delete lTracking;
            lTracking = new List < Operational_Tracking__c > ();
    
            For(Business_Planning_Estimate__c oEstimate: lPlanningEstimates) {
                Operational_Tracking__c oTracking = new Operational_Tracking__c();
                oTracking.Estimated_Date_of_payment__c = oEstimate.Estimate_Date__c;
                oTracking.Estimate_amount__c = oEstimate.Estimate_Amount__c;
                oTracking.Business_Planning_ID__c  = oBp;
                lTracking.add(oTracking);
            }
    
            Insert lTracking;
        }
        
        Catch (exception e) {
            GLBL_Error_Log__c errLog = new GLBL_Error_Log__c(Error_Datetime__c = DateTime.Now(), Error_Message__c = e.getMessage(), Running_User__c = UserInfo.getUserId(), Stack_Trace__c = e.getStackTraceString());
            insert errlog;
            IsError = TRUE;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'There was an error Inserting Operational Forecast Records. Please contact your Administrator'));
        }

    }
}