src/objects/Business_Planning__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>Enter the date that effort begins on the study/project.</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approver_Comment__c</fullName>
        <description>This field is created to store the Approver Comments</description>
        <label>Approver Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Business_Planning_Approval_Status__c</fullName>
        <label>Business Planning Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Discussion</fullName>
                    <color>#0B6FCE</color>
                    <label>In Discussion</label>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                    <color>#78C953</color>
                    <label>Ready for Approval</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                    <color>#E27001</color>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <color>#A845DC</color>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Approved/Reprioritize</fullName>
                    <color>#F3D904</color>
                    <label>Approved/Reprioritize</label>
                </value>
                <value>
                    <fullName>In-Waiting</fullName>
                    <color>#A53711</color>
                    <label>In-Waiting</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <color>#66E9BD</color>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#0B24BE</color>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Submitted for BP Approval</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Submitted for BP session</fullName>
                </value>
                <value>
                    <fullName>BP Review Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_End_Date__c</fullName>
        <inlineHelpText>The approximate date that you think the study will be completed.  May also use the target date for certain deliverables if required for submission, critical chain etc.</inlineHelpText>
        <label>Anticipated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Start_Date__c</fullName>
        <inlineHelpText>Choose the date that effort is anticipated to begin on the study/project (this is NOT the expected contracting date)</inlineHelpText>
        <label>Anticipated Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Anticipated_Start_Date__c</fullName>
        <label>Initial Anticipated Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approved?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Prevents any changes to the item. Item must be frozen before changing to &quot;Ready for Approval&quot;</inlineHelpText>
        <label>Freeze</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to approved Study/Project record</inlineHelpText>
        <label>Study</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Business Planning</relationshipLabel>
        <relationshipName>RWE_Business_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Local_Identifier__c</fullName>
        <inlineHelpText>Include any local identifiers used specifically for a function or area. i.e. the BCM ID</inlineHelpText>
        <label>Unique Local Identifier</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Business Planning</label>
    <nameField>
        <displayFormat>{YYYY}-{0000}</displayFormat>
        <label>Study/Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Planning</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CloneBPController.cls
/****************************************************************************************************************************************** 
 * Class Name   : CloneBPController
 * Description  : Clones the Business Plan record only
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
Public with Sharing Class CloneBPController 
{
    Public Business_Planning__c oBPDetails {get;set;}
    List < String > sBPFields = new List < String > ();   
    
    //Loading the constructor
    public CloneBPController(ApexPages.StandardController controller) 
    {
        oBPDetails = new Business_Planning__c();
        Map < String, Schema.SObjectField > schemaFieldMap = Schema.SObjectType.Business_Planning__c.fields.getMap();               
            for (String fieldName: schemaFieldMap.keySet()) 
            {
                sBPFields.add(fieldName);
            }
            if(!test.isRunningTest())
            { 
                controller.addfields(sBPFields);
            }
        //Fetching the Current Record
        oBPDetails = (Business_Planning__c) controller.getrecord();
        
    }
    
    
/* 
* @Method Name                    :  CloneBP
* @Description                    :  This method clones the BP and its related records
* @Return Type                    :  pagereference
* @Parameters                     :  None
*/ 
    Public PageReference CloneBP() {
    
        //Cloning the Master BP Record 
        try
        {
        Business_Planning__c oBPClone = oBPDetails.clone(false,false,false,false);
        
        oBPClone.Business_Planning_Approval_Status__c='In Discussion';
        oBPClone.Lock__c = FALSE;
        oBPClone.Study__c = NULL;
        oBPClone.OwnerId = UserInfo.getUserId();
        oBPClone.Unique_Local_Identifier__c = '';
        oBPClone.Is_Approved__c=FALSE;
        oBPClone.Estimated_Start_Date__c = null;
        oBPClone.Estimated_End_Date__c = null;
        oBPClone.Initial_Anticipated_Start_Date__c = null;
        oBPClone.Approver_Comment__c = null;
        oBPClone.Actual_Start_Date__c = null;
        
        insert oBPClone;
        
        //Redirecting to the newly cloned BP record
        if(ApexPages.currentPage().getParameters().get('isVFClone')!=NULL)
            {
            PageReference pageRef = new PageReference('/apex/CreateBP?id='+oBPClone.id+'&isEdit=true');
            return pageRef;
            }
        else
            {
                PageReference pageRef = new PageReference('/'+oBPClone.id);
                return pageRef;
            }
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error, e.getmessage()));
            return null;
        }
        
    }

}