src/objects/DRDP_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Display__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tab_Sequence__c</fullName>
        <label>Tab Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>DRDP Configuration</label>
    <nameField>
        <label>DRDP Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRDP Configurations</pluralLabel>
    <recordTypes>
        <fullName>Tabs</fullName>
        <active>true</active>
        <label>Tabs</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SR2IndexController.cls
Public class SR2IndexController{

    Public List<DRDP_Configuration__c> lHomeTabs{get;set;}
    Public String HomeHeader1{get;set;}
    Public String HomeHeader2{get;set;}
    
    
    Public SR2IndexController(){
        GetHeaderImage();
        HomeTabs();
    }
    
    Public Void GetHeaderImage(){
        HomeHeader1 = '/servlet/servlet.FileDownload?file=';
        HomeHeader2 = '/servlet/servlet.FileDownload?file=';
        
        List< document > documentList=[select id,name from document where Name IN ('DRDP Home Header Client logo','DRDP Home Header logo')];
        For(Document d:documentList)
        {
           if(d.Name == 'DRDP Home Header logo'){
               HomeHeader1 = HomeHeader1 +d.id;
           }else if(d.Name == 'DRDP Home Header Client logo'){
               HomeHeader2 = HomeHeader2 + d.id;
           }
        }
    }
    
    Public void HomeTabs(){
        lHomeTabs = new List<DRDP_Configuration__c>([Select Value__c,URL__c,Tab_Sequence__c,Display__c from DRDP_Configuration__c where Display__c=true AND RecordType.Name = 'Tabs' ORDER BY Tab_Sequence__c]);
    }
}