src/objects/DRDW_Bdg_LI_Data_load__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>DRDW_Cost_Center__c</fullName>
        <label>DRDW Cost Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Bdg LI Data loads</relationshipLabel>
        <relationshipName>DRDW_Bdg_LI_Data_loads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Bdg LI Data load</label>
    <nameField>
        <displayFormat>BLID-{0000}</displayFormat>
        <label>Custom Object Label Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Bdg LI Data loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Line Items</relationshipLabel>
        <relationshipName>DRDW_Budget_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cost_center__c</fullName>
        <formula>Related_To__r.Cost_Center__r.Name</formula>
        <label>cost center</label>
        <type>Text</type>
    </fields>
    <label>DRDW Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Master__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Center</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Cannot Create BudgetLineItem for Inactive CostCenter</errorMessage>
            <filterItems>
                <field>DRDW_Cost_Center__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Cost_Center__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Milestone_1__c</fullName>
        <label>Payment Milestone 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_2__c</fullName>
        <label>Payment Milestone 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_3__c</fullName>
        <label>Payment Milestone 3</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_4__c</fullName>
        <label>Payment Milestone 4</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_1__c</fullName>
        <label>Planned Amount for Milestone 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_2__c</fullName>
        <label>Planned Amount for Milestone 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_3__c</fullName>
        <label>Planned Amount for Milestone 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_4__c</fullName>
        <label>Planned Amount for Milestone 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Idea_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Assessment_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Generation_Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Business_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Business Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_F_X_Forecast__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total F&quot;X&quot; Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Budget Master</label>
    <nameField>
        <displayFormat>BGT-{0000}</displayFormat>
        <label>DRDW Budget Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Cost_Center__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Details__c</fullName>
        <label>Additional Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Center</label>
        <referenceTo>DRDW_Cost_Center__c</referenceTo>
        <relationshipLabel>DRDW Cost Centers</relationshipLabel>
        <relationshipName>DRDW_Cost_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Cost Center</label>
    <nameField>
        <label>Cost Center</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRDW Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DRDW_SaveBudgetLine.cls
@isTest
private class Test_DRDW_SaveBudgetLine {
    static testmethod void createBudget(){
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) { 
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');         
            insert lprojects;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
                Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
                Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=System.today(),sapid__c='51082926053');
            DRDW_Budget_Line_Item__c oLineItem1 = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100520312',Posting_Date__c=System.today(),sapid__c='51082932533');
            insert new List<sObject>{oLineItem1,oLineItem};

            DRDW_Bdg_LI_Data_load__c oDataLoad = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '8600075',PO__c='4100437669',Actual_Amount__c=2000.00,Posting_Date__c=System.today().addMonths(-1),PO_Description__c='Review of AHC2224920 reports',Vendor__c='RYC GMBH',sapid__c='5108292605',Posting_row__c='3',Project_Idea__c='test');
            DRDW_Bdg_LI_Data_load__c oDataLoad1  = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '8600075',PO__c='4100520312',Actual_Amount__c=9600.00,Posting_Date__c=System.today().addMonths(1),PO_Description__c='EK_MPI_Expert Statement Cardiologist',Vendor__c='MPI RESEARCH INC',sapid__c='5108293253',Posting_row__c='3',Project_Idea__c='test');
            DRDW_Bdg_LI_Data_load__c oDataLoad2  = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '860075',PO__c='41005202',Actual_Amount__c=9600.00,Posting_Date__c=System.today().addMonths(1),PO_Description__c='EK_MPI_Expert Statement Cardiologist',Vendor__c='MPI RESEARCH INC',sapid__c='5108122123',Posting_row__c='3',Project_Idea__c='test');
            insert new List<sObject>{oDataLoad1,oDataLoad,oDataLoad2};

            DRDW_SaveBudgetLine controller = new DRDW_SaveBudgetLine();
            test.startTest();
            controller.showData();
            controller.RecId=oDataLoad2.id;
            controller.savebdg();
            controller.RecId=oDataLoad2.id;
            controller.updateLists();
            controller.RecId=oDataLoad1.id;
            controller.updateLists();
            System.assertNotEquals(null, oDataLoad1.Id, 'error');
            test.stopTest();
        }
    }   

    static testmethod void createBudget2(){
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) { 
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');         
            insert lprojects;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
                Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
                Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=System.today(),sapid__c='51082926053');
            DRDW_Budget_Line_Item__c oLineItem1 = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100520312',Posting_Date__c=System.today(),sapid__c='51082932533');
            insert new List<sObject>{oLineItem1,oLineItem};

            DRDW_Bdg_LI_Data_load__c oDataLoad = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '8600075',PO__c='4100437669',Actual_Amount__c=2000.00,Posting_Date__c=System.today().addMonths(-1),PO_Description__c='Review of AHC2224920 reports',Vendor__c='RYC GMBH',sapid__c='5108292605',Posting_row__c='3',Project_Idea__c='test');
            DRDW_Bdg_LI_Data_load__c oDataLoad1  = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '8600075',PO__c='4100520312',Actual_Amount__c=9600.00,Posting_Date__c=System.today().addMonths(1),PO_Description__c='EK_MPI_Expert Statement Cardiologist',Vendor__c='MPI RESEARCH INC',sapid__c='5108293253',Posting_row__c='3',Project_Idea__c='test');
            DRDW_Bdg_LI_Data_load__c oDataLoad2  = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '860075',PO__c='41005202',Actual_Amount__c=9600.00,Posting_Date__c=System.today().addMonths(1),PO_Description__c='EK_MPI_Expert Statement Cardiologist',Vendor__c='MPI RESEARCH INC',sapid__c='5108122123',Posting_row__c='3',Project_Idea__c='test');
            insert new List<sObject>{oDataLoad1,oDataLoad,oDataLoad2};

            DRDW_SaveBudgetLine controller = new DRDW_SaveBudgetLine();
            test.startTest();
            controller.showData();
            controller.RecId=oDataLoad2.id;
            controller.saveandLockNew();
            controller.RecId=oDataLoad1.id;
            controller.SaveUpdatebdg();
            controller.recId=oDataLoad.Id;
            controller.DeleteoldBdg();
            System.assertNotEquals(null, oDataLoad1.Id, 'error');
            test.stopTest();
        }
    }   

    static testmethod void createBudget3(){
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) { 
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');         
            insert lprojects;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
                Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
                Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=System.today(),sapid__c='51082926053');
            DRDW_Budget_Line_Item__c oLineItem1 = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100520312',Posting_Date__c=System.today(),sapid__c='51082932533');
            insert new List<sObject>{oLineItem1,oLineItem};

            DRDW_Bdg_LI_Data_load__c oDataLoad = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '8600075',PO__c='4100437669',Actual_Amount__c=2000.00,Posting_Date__c=System.today().addMonths(-1),PO_Description__c='Review of AHC2224920 reports',Vendor__c='RYC GMBH',sapid__c='5108292605',Posting_row__c='3',Project_Idea__c='test');
            DRDW_Bdg_LI_Data_load__c oDataLoad1  = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '8600075',PO__c='4100520312',Actual_Amount__c=9600.00,Posting_Date__c=System.today().addMonths(1),PO_Description__c='EK_MPI_Expert Statement Cardiologist',Vendor__c='MPI RESEARCH INC',sapid__c='5108293253',Posting_row__c='3',Project_Idea__c='test');
            DRDW_Bdg_LI_Data_load__c oDataLoad2  = new DRDW_Bdg_LI_Data_load__c(Related_To__c=oBudgetMaster.id,DRDW_Cost_Center__c = '860075',PO__c='41005202',Actual_Amount__c=9600.00,Posting_Date__c=System.today().addMonths(1),PO_Description__c='EK_MPI_Expert Statement Cardiologist',Vendor__c='MPI RESEARCH INC',sapid__c='5108122123',Posting_row__c='3',Project_Idea__c='test');
            insert new List<sObject>{oDataLoad1,oDataLoad,oDataLoad2};

            DRDW_SaveBudgetLine controller = new DRDW_SaveBudgetLine();
            test.startTest();
            controller.showData();
            controller.RecId=oDataLoad2.id;
            controller.updateLists();
            controller.showData();
            controller.RecId=oDataLoad1.id;
            controller.SaveUpdatebdg();
            controller.RecId=oDataLoad.id;
            controller.oldsaveNlock();
            controller.recId=oDataLoad2.id;
            controller.DeleteBdgNew();
            System.assertNotEquals(null, oDataLoad1.Id, 'error');
            test.stopTest();
        }
    }   
}