src/objects/DRDW_Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Line Items</relationshipLabel>
        <relationshipName>DRDW_Budget_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cost_center__c</fullName>
        <formula>Related_To__r.Cost_Center__r.Name</formula>
        <label>cost center</label>
        <type>Text</type>
    </fields>
    <label>DRDW Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Master__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Center</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Cannot Create BudgetLineItem for Inactive CostCenter</errorMessage>
            <filterItems>
                <field>DRDW_Cost_Center__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Cost_Center__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Milestone_1__c</fullName>
        <label>Payment Milestone 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_2__c</fullName>
        <label>Payment Milestone 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_3__c</fullName>
        <label>Payment Milestone 3</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_1__c</fullName>
        <label>Planned Amount for Milestone 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_2__c</fullName>
        <label>Planned Amount for Milestone 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_3__c</fullName>
        <label>Planned Amount for Milestone 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_4__c</fullName>
        <label>Planned Amount for Milestone 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Idea_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Assessment_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Generation_Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Business_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Business Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_F_X_Forecast__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total F&quot;X&quot; Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>DRDW Budget Master</label>
    <nameField>
        <displayFormat>BGT-{0000}</displayFormat>
        <label>DRDW Budget Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Business_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Business Plan</description>
        <label>Business Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DRDW_Budget_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DRDW Budget Master</description>
        <label>DRDW Budget Master</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Summaries</relationshipLabel>
        <relationshipName>DRDW_Budget_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_X_Forecast__c</fullName>
        <defaultValue>0</defaultValue>
        <label>F&quot;X&quot; Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>DRDW Budget Summary</label>
    <nameField>
        <displayFormat>Summary-{0000}</displayFormat>
        <label>DRDW Budget Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Cost_Center__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Details__c</fullName>
        <label>Additional Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Center</label>
        <referenceTo>DRDW_Cost_Center__c</referenceTo>
        <relationshipLabel>DRDW Cost Centers</relationshipLabel>
        <relationshipName>DRDW_Cost_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Cost Center</label>
    <nameField>
        <label>Cost Center</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRDW Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DRDW_CreateBudgetLineItem.cls
@isTest
private class Test_DRDW_CreateBudgetLineItem {
    static testMethod void testwithBudget() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;

            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
                Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
                Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results');
            insert oBudgetMaster;

            DRDW_Budget_Summary__c oBudSum = new DRDW_Budget_Summary__c(CurrencyIsoCode='EUR',F_X_Forecast__c=12.30,Year__c='2023',Quarter__c='2',Business_Plan__c=122.00,DRDW_Budget_Master__c=oBudgetMaster.Id,PO__c='TBD');
            insert oBudSum;

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='12121',Posting_Date__c=System.today());
            insert oLineItem;

            DRDW_Budget_Summary_Detail__c oBudSumDetail = new DRDW_Budget_Summary_Detail__c(DRDW_Budget_Summary__c=oBudSum.Id,Year__c='2018',Quarter__c='2',Month__c='Jan',Species__c='TBD');
            insert oBudSumDetail;
            System.assertNotEquals(null,oBudSumDetail,'error'); 
            PageReference pageRef = new pageReference('/apex/DRDW_CreateBudgetLineItem?Id='+oLineItem.id+'&isEdit=false&BudgetId='+oBudgetMaster.Id);         
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(oLineItem);
            DRDW_CreateBudgetLineItem controller = new DRDW_CreateBudgetLineItem(sc);
            test.startTest();  
            controller.save();
            controller.deleteRecord();
            controller.edit();
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stoptest();
        }
    }
    
    static testMethod void testwithBudget2() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;

            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
                Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
                Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results');
            insert oBudgetMaster;

            DRDW_Budget_Summary__c oBudSum = new DRDW_Budget_Summary__c(CurrencyIsoCode='EUR',F_X_Forecast__c=12.30,Year__c='2023',Quarter__c='2',Business_Plan__c=122.00,DRDW_Budget_Master__c=oBudgetMaster.Id,PO__c='TBD');
            insert oBudSum;

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='12121',Posting_Date__c=System.today());
            insert oLineItem;

            DRDW_Budget_Summary_Detail__c oBudSumDetail = new DRDW_Budget_Summary_Detail__c(DRDW_Budget_Summary__c=oBudSum.Id,Year__c='2018',Quarter__c='2',Month__c='Jan',Species__c='TBD');
            insert oBudSumDetail;
            System.assertNotEquals(null,oBudSumDetail,'error'); 
            PageReference pageRef = new pageReference('/apex/DRDW_CreateBudgetLineItem?Id='+oLineItem.id+'&isEdit=false&BudgetId='+oBudgetMaster.Id);         
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(oLineItem);
            DRDW_CreateBudgetLineItem controller = new DRDW_CreateBudgetLineItem(sc);
            test.startTest();  
            controller.save();
            controller.deleteRecord();
            controller.edit();
            
            oCostCen.Status__c ='Inactive';
            update oCostCen;
            controller.save();
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stoptest();
        }
    }   

    static testMethod void testwithoutBudget() {        
        User finAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(finAdm.id,'DRDW_Financial_User');
        System.runAs(finAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');         
            insert lprojects;

            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
                Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
                Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results');
            insert oBudgetMaster;

            DRDW_Budget_Summary__c oBudSum = new DRDW_Budget_Summary__c(CurrencyIsoCode='EUR',F_X_Forecast__c=12.30,Year__c='2023',Quarter__c='2',Business_Plan__c=122.00,DRDW_Budget_Master__c=oBudgetMaster.Id,PO__c='TBD');
            insert oBudSum;

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=finAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='12121',Posting_Date__c=System.today());
            insert oLineItem;

            DRDW_Budget_Summary_Detail__c oBudSumDetail = new DRDW_Budget_Summary_Detail__c(DRDW_Budget_Summary__c=oBudSum.Id,Year__c='2018',Quarter__c='2',Month__c='Jan',Species__c='TBD');
            insert oBudSumDetail;
            System.assertNotEquals(null,oBudSumDetail,'error'); 
            PageReference pageRef = new pageReference('/apex/DRDW_CreateBudgetSummaryDetail?BudgetId='+oBudgetMaster.Id);         
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(oLineItem);
            DRDW_CreateBudgetLineItem controller = new DRDW_CreateBudgetLineItem(sc);
            test.startTest(); 
            controller.isEval = true;
            controller.save();
            controller.deleteRecord();
            controller.edit();
            System.assertNotEquals(null,finAdm.Id,'error');
            test.stoptest();
            
        }
    }   
}