src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Related_Idea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Evaluation Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipName>Capabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Commercial Operations</fullName>
                </value>
                <value>
                    <fullName>CMC</fullName>
                </value>
                <value>
                    <fullName>Legal &amp; Compliance</fullName>
                </value>
                <value>
                    <fullName>Regulatory</fullName>
                </value>
                <value>
                    <fullName>Corporate Finance</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                    <label>Corporate</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <isActive>false</isActive>
                    <label>Finance</label>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                    <label>Manufacturing</label>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                    <isActive>false</isActive>
                    <label>R&amp;D</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Risk__c.object
<CustomObject>
    <label>DRDW Risk</label>
    <nameField>
        <displayFormat>RSK-{0000}</displayFormat>
        <label>Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_DRDW_Research_TriggerHandler.cls
@isTest
private class Test_DRDW_Research_TriggerHandler{
  static testMethod void testwithResource() {  
        DRDW_Project__c oProject = new DRDW_Project__c();
                      
         User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Financial_User');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Idea Project');     
             lProjects[0].Business_Unit__c = 'Business Development';      
            insert lprojects;
            List<DRDW_Project__c> lIdea = DRDW_TestDataFactory.returnProjects(1,'Idea');
            insert lIdea;
            lprojects[0].Related_Idea__c=lIdea[0].Id;
            lprojects[0].CSF_Decision_to_Generate_DTG_Planned__c = system.today().addDays(2);
            lprojects[0].Decision_to_Evaluate_DTE__c = system.today();
            lprojects[0].EPCTM_DTG_DTE_for_Biopharma__c = 23;
            lprojects[0].Molecule_Classification__c = 'Small Molecule';
            lProjects[0].Business_Unit__c = 'Nutritionals';                                  
            List<DRDW_Risk__c> lRisks = DRDW_TestDataFactory.returnRisks(1,lprojects[0].id);      
            insert lRisks;      
            Test.startTest();
            system.assertNotEquals(lProjects,null); 
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            update lprojects[0];
            delete lProjects[0];
            DRDW_Research_TriggerHandler.getObjectRecordTypeId(DRDW_Project__c.SObjectType,'Generation Project');
            Test.stopTest();
        }
        
        
    }
}