src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Samples_to_collect_new__c</fullName>
        <label>Study Schedule Activities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Do_you_know_your_Activities__c</fullName>
        <label>Do you know your Activities?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GO_Preferred_Start_Date__c</fullName>
        <label>GO Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lab_Testing_Required__c</fullName>
        <label>Lab Testing Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned DTG date on the Project if an Evaluation Project, the Planned DTA date on the Project if a Generation Project, the Planned DP1 date on the Project if an Assessment Project.It is editable</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <description>DTE date on the Project if an Evaluation Project, the DTG date on the Project if a Generation Project, the DTA date on the Project if an Assessment Project. It is editable</description>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <description>Actual End Date</description>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned End Date</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <inlineHelpText>Decision to Evaluate (DTE):</inlineHelpText>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
  <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <description>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</description>
        <inlineHelpText>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</inlineHelpText>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLBL_Global_List_of_Values__c.object
<CustomObject>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>Enter the date that effort begins on the research study/ research project.</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_DRDW_CreateERLRequestCtrl.cls
@isTest
private class Test_DRDW_CreateERLRequestCtrl {
    static testMethod void testPositive() {        
        User finUsr = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(finUsr.id,'DRDW_Financial_User');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_FG_Bacteriology');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_BU_CA_Parasitology');
        System.runAs(finUsr) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(1,'Generation Project');                   
            insert lprojects;
            System.assert(lprojects.size()==1);

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Do_you_know_your_Activities__c='Yes',GO_Preferred_Start_Date__c=System.today()+2,Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',samples_to_collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+15,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId());
            insert ocapReq;
          
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].DRDW_Request__c=ocapReq.id; 
            lCapab[0].Proposed_Start_Date__c=System.today();
            lCapab[0].Planned_End_Date__c=System.today() +10;
            lCapab[1].Planned_End_Date__c=System.today() +13;
            lCapab[0].Title__c='Test';
            lCapab[1].Title__c='Test Idea';
            lCapab[1].DRDW_Request__c=ocapReq.id; 
            insert lCapab;

            GLBL_Global_List_of_Values__c oglov = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov1 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov2 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov3 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            insert new List<sObject>{oglov,oglov1,oglov2,oglov3};

            PageReference pageRef = new pageReference('/apex/DRDW_CreateERLRequest?Id='+ocapReq.Id+'&projid='+lprojects[0].id);
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(ocapReq);
            DRDW_CreateERLRequestCtrl controller = new DRDW_CreateERLRequestCtrl(sc);
            test.startTest();
            controller.copyField();
            controller.ActivityLink();
            controller.showActivity();
            controller.index=1;
            controller.saveActivities();
            controller.save();
            controller.cancelRecord();
            controller.showActivityOrSubmit();
            controller.oRequest.Do_you_know_your_Activities__c = 'No';
            controller.showActivityOrSubmit();
            controller.EditActivities();
            controller.addActivityRow();
            controller.oRequest.Do_you_know_your_Activities__c = 'Yes';
            controller.SendEmailNotifications();
            controller.oRequest.Do_you_know_your_Activities__c = 'No';
            controller.SendEmailNotifications();
            test.stopTest();
            controller.Edit();
            controller.oRequest.Do_you_know_your_Activities__c='Yes';
            controller.cancelRecord();
            controller.index=1;
            controller.subActivityRow();
            controller.DeleteRecord();
            controller.oRequest = null;
            controller.cancelRecord();
        }
    }

    static testMethod void testNegative() {        
        User studMgr = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(studMgr.id,'DRDW_Study_Managers');
        DRDW_TestDataFactory.assignGroup(studMgr.id,'DRDW_FG_Bacteriology');
        DRDW_TestDataFactory.assignGroup(studMgr.id,'DRDW_BU_CA_Parasitology');
        System.runAs(studMgr) {
            List<DRDW_Project__c> lprojInsert = new List<DRDW_Project__c>();
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(1,'Assessment Project');
            lprojects[0].Decision_To_Assess_DTA__c=System.today();
            lprojects[0].DP1_Planned_Date__c=System.today()+8;
            lprojInsert.addAll(lprojects); 
            List<DRDW_Project__c> lprojects1 = DRDW_TestDataFactory.returnProjects(1,'Idea Project');   
            lprojects1[0].Decision_to_Evaluate_DTE__c=System.today();
            lprojects1[0].CSF_Decision_to_Generate_DTG_Planned__c=System.today()+8;
            lprojInsert.addAll(lprojects1);              
            insert lprojInsert;
            System.assert(lprojInsert.size()==2);

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Do_you_know_your_Activities__c='Yes',GO_Preferred_Start_Date__c=System.today()+2,Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',samples_to_collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today()+16,Actual_End_Date__c=System.today()+15,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId(),Planned_End_Date__c=System.today()+10,Planned_Start_Date__c=System.today()+15);
            insert ocapReq;
          
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].DRDW_Request__c=ocapReq.id; 
            lCapab[0].Proposed_Start_Date__c=System.today();
            lCapab[0].Planned_End_Date__c=System.today() +16;
            lCapab[1].Planned_End_Date__c=System.today() +13;
            lCapab[0].Actual_Start_Date__c=System.today()+17;
            lCapab[0].Actual_End_Date__c=System.today()+2;
            lCapab[0].Title__c='Test';
            lCapab[1].Title__c='Test Idea';
            lCapab[1].DRDW_Request__c=ocapReq.id;             

            GLBL_Global_List_of_Values__c oglov = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov1 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov2 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov3 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            insert new List<sObject>{oglov,oglov1,oglov2,oglov3};

            PageReference pageRef = new pageReference('/apex/DRDW_CreateERLRequest?projid='+lprojects[0].id);
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(ocapReq);
            DRDW_CreateERLRequestCtrl controller = new DRDW_CreateERLRequestCtrl(sc);  
            DRDW_CreateERLRequestCtrl.ActivityWrapper oActivity = new DRDW_CreateERLRequestCtrl.ActivityWrapper(0,true,true,true,lCapab[0]);
            DRDW_CreateERLRequestCtrl.ActivityWrapper oActivity1 = new DRDW_CreateERLRequestCtrl.ActivityWrapper(0,true,true,true,lCapab[1]);
            controller.lactivityWrapper = new List<DRDW_CreateERLRequestCtrl.ActivityWrapper>();
            controller.lactivityWrapper.add(oActivity);
            controller.lactivityWrapper.add(oActivity1);
            controller.index=0;
            controller.saveActivities();
            controller.oRequest.Planned_Start_Date__c=System.today()-10;  
            controller.save();   

            PageReference pageRef1 = new pageReference('/apex/DRDW_CreateERLRequest?projid='+lprojects1[0].id);
            Test.setCurrentPage(pageRef1);
            ApexPages.StandardController sc1 = new ApexPages.StandardController(ocapReq);
            DRDW_CreateERLRequestCtrl controller1 = new DRDW_CreateERLRequestCtrl(sc1);            
        }
    }
    
    static testMethod void testPositive2() {        
        User finUsr = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(finUsr.id,'DRDW_Financial_User');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_FG_Bacteriology');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_BU_CA_Parasitology');
        System.runAs(finUsr) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(1,'Idea Project');                   
            insert lprojects;
            System.assert(lprojects.size()==1);

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Do_you_know_your_Activities__c='Yes',GO_Preferred_Start_Date__c=System.today()+2,Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',samples_to_collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+15,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId());
            insert ocapReq;
          
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].DRDW_Request__c=ocapReq.id; 
            lCapab[0].Proposed_Start_Date__c=System.today();
            lCapab[0].Planned_End_Date__c=System.today() +10;
            lCapab[1].Planned_End_Date__c=System.today() +13;
            lCapab[0].Title__c='Test';
            lCapab[1].Title__c='Test Idea';
            lCapab[1].DRDW_Request__c=ocapReq.id; 
            insert lCapab;

            GLBL_Global_List_of_Values__c oglov = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov1 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov2 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov3 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            insert new List<sObject>{oglov,oglov1,oglov2,oglov3};

            PageReference pageRef = new pageReference('/apex/DRDW_CreateERLRequest?Id='+ocapReq.Id+'&projid='+lprojects[0].id);
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(ocapReq);
            DRDW_CreateERLRequestCtrl controller = new DRDW_CreateERLRequestCtrl(sc);
            test.startTest();
            controller.copyField();
            controller.ActivityLink();
            controller.showActivity();
            controller.index=1;
            controller.saveActivities();
            controller.save();
            controller.cancelRecord();
            controller.showActivityOrSubmit();
            controller.oRequest.Do_you_know_your_Activities__c = 'No';
            controller.showActivityOrSubmit();
            controller.EditActivities();
            controller.addActivityRow();
            controller.oRequest.Do_you_know_your_Activities__c = 'Yes';
            controller.SendEmailNotifications();
            controller.oRequest.Do_you_know_your_Activities__c = 'No';
            controller.SendEmailNotifications();
            test.stopTest();
            controller.Edit();
            controller.oRequest.Do_you_know_your_Activities__c='Yes';
            controller.cancelRecord();
            controller.index=1;
            controller.subActivityRow();
            controller.DeleteRecord();
            controller.oRequest = null;
            controller.cancelRecord();
        }
    }
    
    static testMethod void testPositive3() {        
        User finUsr = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(finUsr.id,'DRDW_Financial_User');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_FG_Bacteriology');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_BU_CA_Parasitology');
        System.runAs(finUsr) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(1,'Assessment Project');                   
            insert lprojects;
            System.assert(lprojects.size()==1);

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Do_you_know_your_Activities__c='Yes',GO_Preferred_Start_Date__c=System.today()+2,Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',samples_to_collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+15,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId());
            insert ocapReq;
          
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].DRDW_Request__c=ocapReq.id; 
            lCapab[0].Proposed_Start_Date__c=System.today();
            lCapab[0].Planned_End_Date__c=System.today() +10;
            lCapab[1].Planned_End_Date__c=System.today() +13;
            lCapab[0].Title__c='Test';
            lCapab[1].Title__c='Test Idea';
            lCapab[1].DRDW_Request__c=ocapReq.id; 
            insert lCapab;

            GLBL_Global_List_of_Values__c oglov = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov1 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov2 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov3 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            insert new List<sObject>{oglov,oglov1,oglov2,oglov3};

            PageReference pageRef = new pageReference('/apex/DRDW_CreateERLRequest?Id='+ocapReq.Id+'&projid='+lprojects[0].id);
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(ocapReq);
            DRDW_CreateERLRequestCtrl controller = new DRDW_CreateERLRequestCtrl(sc);
            test.startTest();
            controller.copyField();
            controller.ActivityLink();
            controller.showActivity();
            controller.index=1;
            controller.saveActivities();
            controller.save();
            controller.cancelRecord();
            controller.showActivityOrSubmit();
            controller.oRequest.Do_you_know_your_Activities__c = 'No';
            controller.showActivityOrSubmit();
            controller.EditActivities();
            controller.addActivityRow();
            controller.oRequest.Do_you_know_your_Activities__c = 'Yes';
            controller.SendEmailNotifications();
            controller.oRequest.Do_you_know_your_Activities__c = 'No';
            controller.SendEmailNotifications();
            test.stopTest();
            controller.Edit();
            controller.oRequest.Do_you_know_your_Activities__c='Yes';
            controller.cancelRecord();
            controller.index=1;
            controller.subActivityRow();
            controller.DeleteRecord();
            controller.showActivityOrSubmit();
            controller.oRequest = null;
            controller.cancelRecord();
            
            
        }
    }
    
     static testMethod void testPositive4() {        
        User finUsr = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(finUsr.id,'DRDW_Financial_User');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_FG_Bacteriology');
        DRDW_TestDataFactory.assignGroup(finUsr.id,'DRDW_BU_CA_Parasitology');
        System.runAs(finUsr) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(1,'Assessment Project');                   
            insert lprojects;
            System.assert(lprojects.size()==1);

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Do_you_know_your_Activities__c='Yes',GO_Preferred_Start_Date__c=System.today()+2,Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',samples_to_collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+15,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId());
            insert ocapReq;
          
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].DRDW_Request__c=ocapReq.id; 
            lCapab[0].Proposed_Start_Date__c=System.today();
            lCapab[0].Planned_End_Date__c=System.today() +10;
            lCapab[1].Planned_End_Date__c=System.today() +13;
            lCapab[0].Title__c='Test';
            lCapab[1].Title__c='Test Idea';
            lCapab[1].DRDW_Request__c=ocapReq.id; 
            insert lCapab;

            GLBL_Global_List_of_Values__c oglov = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov1 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov2 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            GLBL_Global_List_of_Values__c oglov3 = new GLBL_Global_List_of_Values__c(name='Test',Active__c=true,RecordTypeId=Schema.SObjectType.GLBL_Global_List_of_Values__c.getRecordTypeInfosByName().get('Elanco Capability Area').getRecordTypeId());
            insert new List<sObject>{oglov,oglov1,oglov2,oglov3};

            PageReference pageRef = new pageReference('/apex/DRDW_CreateERLRequest?Id='+ocapReq.Id+'&projid='+lprojects[0].id);
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(ocapReq);
            DRDW_CreateERLRequestCtrl controller = new DRDW_CreateERLRequestCtrl(sc);
            test.startTest();
            PageReference pageRef2 = new pageReference('/apex/DRDW_CreateERLRequest?Id='+ocapReq.Id);
            Test.setCurrentPage(pageRef2);
            DRDW_CreateERLRequestCtrl controller1 = new DRDW_CreateERLRequestCtrl(sc);
            PageReference pageRef3 = new pageReference('/apex/DRDW_CreateERLRequest');
            Test.setCurrentPage(pageRef3);
            DRDW_CreateERLRequestCtrl controller2 = new DRDW_CreateERLRequestCtrl(sc);
            test.stopTest();
            
        }
    }
}