src/objects/DRDW_Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Line Items</relationshipLabel>
        <relationshipName>DRDW_Budget_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cost_center__c</fullName>
        <formula>Related_To__r.Cost_Center__r.Name</formula>
        <label>cost center</label>
        <type>Text</type>
    </fields>
    <label>DRDW Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Master__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Center</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Cannot Create BudgetLineItem for Inactive CostCenter</errorMessage>
            <filterItems>
                <field>DRDW_Cost_Center__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Cost_Center__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Milestone_1__c</fullName>
        <label>Payment Milestone 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_2__c</fullName>
        <label>Payment Milestone 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_3__c</fullName>
        <label>Payment Milestone 3</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Milestone_4__c</fullName>
        <label>Payment Milestone 4</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upon signature of contract (no more than 50%)</fullName>
                </value>
                <value>
                    <fullName>Initiation of contract</fullName>
                </value>
                <value>
                    <fullName>Start of live phase</fullName>
                </value>
                <value>
                    <fullName>End of live phase</fullName>
                </value>
                <value>
                    <fullName>Draft Report</fullName>
                </value>
                <value>
                    <fullName>Final Report</fullName>
                </value>
                <value>
                    <fullName>Upon receipt of results</fullName>
                </value>
                <value>
                    <fullName>Upon shipment of material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_1__c</fullName>
        <label>Planned Amount for Milestone 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_2__c</fullName>
        <label>Planned Amount for Milestone 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_3__c</fullName>
        <label>Planned Amount for Milestone 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Amount_for_Milestone_4__c</fullName>
        <label>Planned Amount for Milestone 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Idea_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Assessment_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Generation_Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Business_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Business Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_F_X_Forecast__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total F&quot;X&quot; Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>DRDW Budget Master</label>
    <nameField>
        <displayFormat>BGT-{0000}</displayFormat>
        <label>DRDW Budget Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Summary__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Budget_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DRDW Budget Master</description>
        <label>DRDW Budget Master</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Summaries</relationshipLabel>
        <relationshipName>DRDW_Budget_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Budget Summary</label>
    <nameField>
        <displayFormat>Summary-{0000}</displayFormat>
        <label>DRDW Budget Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Cost_Center__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Details__c</fullName>
        <label>Additional Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Center</label>
        <referenceTo>DRDW_Cost_Center__c</referenceTo>
        <relationshipLabel>DRDW Cost Centers</relationshipLabel>
        <relationshipName>DRDW_Cost_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Cost Center</label>
    <nameField>
        <label>Cost Center</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRDW Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DRDW_BudgetLineItemTriggerHandler.cls
@isTest
private class Test_DRDW_BudgetLineItemTriggerHandler {
    public static Date Jan = Date.newInstance(System.today().Year(), 1, 17);
    public static Date Feb = Date.newInstance(System.today().Year(), 2, 17);
    public static Date March =  Date.newInstance(System.today().Year(), 3, 17);
    public static Date April =  Date.newInstance(System.today().Year(), 4, 17);
    public static Date May =  Date.newInstance(System.today().Year(), 5, 17);
    public static Date June =  Date.newInstance(System.today().Year(), 6, 17);
    public static Date July =  Date.newInstance(System.today().Year(), 7, 17);
    public static Date August =  Date.newInstance(System.today().Year(), 8, 17);
    public static Date September =  Date.newInstance(System.today().Year(), 9, 17);
    public static Date October =  Date.newInstance(System.today().Year(), 10, 17);
    public static Date November = Date.newInstance(System.today().Year(), 11, 17);
    public static Date December =  Date.newInstance(System.today().Year(), 12, 17);
    static testMethod void testwithBudget() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;

            Test.setCreatedDate(oBudgetMaster.Id, DateTime.newInstance(2012,12,12));  
            test.startTest();

            Integer tempqrtr = Jan.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }

            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=Jan,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error'); 
            test.stopTest();

            DRDW_budgetLineItemTriggerHandler.getCurrentMonths('1');
            DRDW_budgetLineItemTriggerHandler.getCurrentMonths('2');
            DRDW_budgetLineItemTriggerHandler.getCurrentMonths('3');
            DRDW_budgetLineItemTriggerHandler.getCurrentMonths('4');

            delete oLineItem;
        }
    }       

    static testMethod void testwithBudget2() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;

            Test.setCreatedDate(oBudgetMaster.Id, DateTime.newInstance(2012,12,12));  
            test.startTest();

            Integer tempqrtr = Feb.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }

            

            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);

            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=Feb,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error'); 
            test.stopTest();
            delete oLineItem;            
        }
    }   
    static testMethod void testwithBudget3() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = March.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=March,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error'); 
            test.stopTest();
            delete oLineItem;            
        }
    }  

    static testMethod void testwithBudget4() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = April.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=April,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error'); 
            test.stopTest();
            delete oLineItem;            
        }
    }       

    static testMethod void testwithBudget5() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;        
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = May.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=May,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error'); 
            test.stopTest();
            delete oLineItem;            
        }
    }       

    static testMethod void testwithBudget6() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;

            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = June.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=June,sapid__c='51082926053');
            insert oLineItem;
           System.assertNotEquals(null,busAdm.Id,'error');
            test.stopTest();
            delete oLineItem;            
        }
    }       
    static testMethod void testwithBudget7() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = July.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=July,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stopTest();
            delete oLineItem;            
        }
    }       
    static testMethod void testwithBudget8() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = August.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=August,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stopTest();
            delete oLineItem;            
        }
    }       
    static testMethod void testwithBudget9() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = September.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=September,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stopTest();
            delete oLineItem;            
        }
    }       
    static testMethod void testwithBudget10() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = October.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=October,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stopTest();
            delete oLineItem;            
        }
    }       
    static testMethod void testwithBudget11() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = November.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=November,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stopTest();
            delete oLineItem;            
        }
    }       
    static testMethod void testwithBudget12() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {            
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');         
            insert lprojects;
            System.assert(lprojects.size()==2);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 
            DRDW_Budget_Master__c oBudgetMaster = new DRDW_Budget_Master__c(CurrencyIsoCode='EUR',Total_F_X_Forecast__c=100.00,Total_Business_Plan__c=500.00,Cost_Center__c=oCostCen.Id,Planned_Amount_for_Milestone_1__c=1000.00,
            Planned_Amount_for_Milestone_2__c=1000.00,Planned_Amount_for_Milestone_3__c=1000.00,Planned_Amount_for_Milestone_4__c=1000.00,
            Payment_Milestone_1__c='Initiation of contract',Related_To__c=lprojects[0].Id,Payment_Milestone_2__c='Start of live phase',Payment_Milestone_3__c='End of live phase',Payment_Milestone_4__c='Upon receipt of results',PO__c='41004376612',Vendor__c='TBD');
            insert oBudgetMaster;
            test.startTest();
            Integer tempqrtr = December.month();
            String quarter;
            if(tempqrtr > 0 && tempqrtr < 4){
                quarter = '1';
            }else if(tempqrtr > 3 && tempqrtr < 7){
                quarter = '2';
            }else if(tempqrtr > 6 && tempqrtr < 10){
                quarter = '3';
            }else if(tempqrtr > 9 && tempqrtr < 13){
                quarter = '4';
            }
            
            Database.delete([Select Id,Name,Quarter__c,Year__c from DRDW_Budget_Summary__c where Quarter__c=:quarter]);
            DRDW_Budget_Line_Item__c oLineItem = new DRDW_Budget_Line_Item__c(Save_And_Lock__c=false,Related_To__c=oBudgetMaster.Id,Scientist_Owner__c=busAdm.Id,Vendor__c='TBD',Actual_Amount__c=123,PO__c='4100437669',Posting_Date__c=December,sapid__c='51082926053');
            insert oLineItem;
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stopTest();
            delete oLineItem;            
        }
    }      
}