src/objects/DRDW_Assign_Resource__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Activity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>DRDW_Capability__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Request Activity</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Capability__c.DRDW_Request__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>ERL</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Capability__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Study Activity</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Capability__c.DRDW_Request__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>GO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Assign Resources</relationshipLabel>
        <relationshipName>DRDW_Assign_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Assign Resources</relationshipLabel>
        <relationshipName>DRDW_Assign_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Animal Care</fullName>
                </value>
                <value>
                    <fullName>FD Laboratory</fullName>
                </value>
                <value>
                    <fullName>FD Study Management</fullName>
                </value>
                <value>
                    <fullName>FD Veterinary Support</fullName>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Assign Resource</label>
    <nameField>
        <displayFormat>AssRes-{0000}</displayFormat>
        <label>DRDW Assign Res</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Assign Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Calender_Per_Roaster__c.object
<CustomObject>
    <description>To capture per day per roaster hours allocated</description>
    <label>DRDW Calender Per Roaster</label>
    <nameField>
        <displayFormat>CALR-{000000}</displayFormat>
        <label>DRDW Calender Per Roaster Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Calender Per Roasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Lab_Testing_Required__c</fullName>
        <label>Lab Testing Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_Study_End_Date__c</fullName>
        <label>Planned Study End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Study_Start_Date__c</fullName>
        <inlineHelpText>Study Day 0 Equals Frist Dosing</inlineHelpText>
        <label>Planned Study Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <label>Study Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Type__c</fullName>
        <label>Study Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serology</fullName>
                </value>
                <value>
                    <fullName>Safety</fullName>
                </value>
                <value>
                    <fullName>Efficacy</fullName>
                </value>
                <value>
                    <fullName>CMD</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
                <value>
                    <fullName>POP</fullName>
                </value>
                <value>
                    <fullName>RTV</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Activity</label>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Events</relationshipLabel>
        <relationshipName>DRDW_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <label>Study Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Type__c</fullName>
        <formula>TEXT(DRDW_Activity__r.DRDW_Request__r.Study_Type__c)</formula>
        <label>Study Type</label>
        <type>Text</type>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Event_Days__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DRDW_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Resource</label>
        <referenceTo>DRDW_Resource__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Event Days</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>DRDW Event Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Event Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Resource__c.object
<CustomObject>
    <label>DRDW Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_DRDW_RequestTriggerHandler.cls
@isTest(seeAllData=False)
public class Test_DRDW_RequestTriggerHandler {

    Static testmethod void testRequestInsertUpdate(){
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
            DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
            System.runAs(busAdm) { 
                List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Idea Project');         
                insert lprojects;
                List< DRDW_Cap_Request__c > lstReq = new List<DRDW_Cap_Request__c >();
                    DRDW_Cap_Request__c oReq = new DRDW_Cap_Request__c();
                    oReq.Study_Title__c = 'Test Title';
                    oReq.Study_Type__c = 'RTV';
                    oReq.Project__c = lprojects[0].id;
                    oReq.Planned_Study_Start_Date__c = System.today();
                    oReq.Planned_Study_End_Date__c = System.today();
                    oReq.RecordTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId();
                    lstReq.add(oReq);
                insert lstReq;
                DRDW_Resource__c oResource = new DRDW_Resource__c();
                insert oResource;
                List<DRDW_Capability__c > lstActivity = new List<DRDW_Capability__c >();
                    DRDW_Capability__c oActivity = new DRDW_Capability__c();
                    oActivity.DRDW_Request__c = lstReq[0].id;
                lstActivity.add(oActivity);
                oActivity.RecordTypeId = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Study Activity').getRecordTypeId();
                
                insert lstActivity;
                list<DRDW_Event__c> lstEvent = new List<DRDW_Event__c>();
                DRDW_Event__c oEvent = new DRDW_Event__c();
                oEvent.DRDW_Activity__c = lstActivity[0].id;
                lstEvent.add(oEvent);
                insert lstEvent;
                DRDW_Assign_Resource__c oAssnRes = new DRDW_Assign_Resource__c();
                    oAssnRes.Group__c = 'FD Laboratory';
                    oAssnRes.DRDW_Event__c = lstEvent[0].id;
                    
                insert oAssnRes;
                List<DRDW_Calender_Per_Roaster__c> lstCalPrRoaster = new List<DRDW_Calender_Per_Roaster__c>();
                insert lstCalPrRoaster;
                List<DRDW_Event_Days__c> lstEventDays = new List<DRDW_Event_Days__c>();
                insert lstEventDays;
                lstReq[0].Study_Title__c = 'Updated Test Title';
                lstReq[0].Lab_Testing_Required__c='Lab Fecal: Other';
                update lstReq;
            }
            System.assertNotEquals(null,busAdm.Id,'error');
    }
    Static testmethod void testRequestDelete(){
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
            DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
            System.runAs(busAdm) { 
                List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Idea Project');         
                insert lprojects;
                List< DRDW_Cap_Request__c > lstReq = new List<DRDW_Cap_Request__c >();
                    DRDW_Cap_Request__c oReq = new DRDW_Cap_Request__c();
                    oReq.Study_Title__c = 'Test Title';
                    oReq.Study_Type__c = 'RTV';
                    oReq.Project__c = lprojects[0].id;
                    oReq.Planned_Study_Start_Date__c = System.today();
                    oReq.Planned_Study_End_Date__c = System.today();
                    oReq.RecordTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId();
                    lstReq.add(oReq);
                insert lstReq;
                DRDW_Resource__c oResource = new DRDW_Resource__c();
                insert oResource;
                List<DRDW_Capability__c > lstActivity = new List<DRDW_Capability__c >();
                    DRDW_Capability__c oActivity = new DRDW_Capability__c();
                    oActivity.DRDW_Request__c = lstReq[0].id;
                    oActivity.RecordTypeId = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Study Activity').getRecordTypeId();
                lstActivity.add(oActivity);
                insert lstActivity;
                list<DRDW_Event__c> lstEvent = new List<DRDW_Event__c>();
                DRDW_Event__c oEvent = new DRDW_Event__c();
                oEvent.DRDW_Activity__c = lstActivity[0].id;
                lstEvent.add(oEvent);
                insert lstEvent;
                DRDW_Assign_Resource__c oAssnRes = new DRDW_Assign_Resource__c();
                    oAssnRes.Group__c = 'FD Laboratory';
                    oAssnRes.DRDW_Event__c = lstEvent[0].id;
                    
                insert oAssnRes;
                
                DRDW_RequestTriggerHandler handler = new DRDW_RequestTriggerHandler();
                handler.UpdateReqActivity(lstReq);
                
                List<DRDW_Calender_Per_Roaster__c> lstCalPrRoaster = new List<DRDW_Calender_Per_Roaster__c>();
                insert lstCalPrRoaster;
                List<DRDW_Event_Days__c> lstEventDays = new List<DRDW_Event_Days__c>();
                insert lstEventDays;
                delete lstReq;
                
            }
            System.assertNotEquals(null,busAdm.Id,'error');
    }
}