src/objects/DRDW_Cost_Center__c.object
<CustomObject>
    <label>DRDW Cost Center</label>
    <nameField>
        <label>Cost Center</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRDW Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_ND_Budget_Detail__c.object
<CustomObject>
    <description>This object contains details related to Non-Discretionary Budget Detail</description>
    <fields>
        <fullName>DRDW_Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Cost Center</label>
        <referenceTo>DRDW_Cost_Center__c</referenceTo>
        <relationshipLabel>DRDW ND Budget Detail</relationshipLabel>
        <relationshipName>DRDW_ND_Budget_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DRDW_ND_Budget_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW ND Budget Master</label>
        <referenceTo>DRDW_ND_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW ND Budget Detail</relationshipLabel>
        <relationshipName>DRDW_ND_Budget_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>TEXT(DRDW_ND_Budget_Master__r.Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>DRDW ND Budget Detail</label>
    <nameField>
        <displayFormat>ND-{0000}</displayFormat>
        <label>DRDW ND Budget Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW ND Budget Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_ND_Budget_Master__c.object
<CustomObject>
    <description>This object contain details related to Non Discretionary Budget Master</description>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW ND Budget Master</label>
    <nameField>
        <displayFormat>ND-{0000}</displayFormat>
        <label>Non Discretionary Budget Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW ND Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_NDBD_Category__c.object
<CustomObject>
    <description>This object contains details related to Non-Discretionary Budget Detail Category</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C&amp;B</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Dep/Amort</fullName>
                </value>
                <value>
                    <fullName>Alloc</fullName>
                </value>
                <value>
                    <fullName>Cnslt</fullName>
                </value>
                <value>
                    <fullName>TTM</fullName>
                </value>
                <value>
                    <fullName>Supplies</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DRDW_ND_Budget_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW ND Budget Detail</label>
        <referenceTo>DRDW_ND_Budget_Detail__c</referenceTo>
        <relationshipLabel>DRDW NDBD Category</relationshipLabel>
        <relationshipName>DRDW_NDBD_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Non_Discretionary_Year_Total__c</fullName>
        <formula>ROUND(Q1__c  +  Q2__c  +  Q3__c  +  Q4__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non-Discretionary Year Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q4__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW NDBD Category</label>
    <nameField>
        <displayFormat>ND-{0000}</displayFormat>
        <label>DRDW NDBD Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW NDBD Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_NDBM_Category__c.object
<CustomObject>
    <description>This Object Contain details related to Non-Discretionary Budget Master Category</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alloc</fullName>
                </value>
                <value>
                    <fullName>C&amp;B</fullName>
                </value>
                <value>
                    <fullName>Cnslt</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Dep/Amort</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Supplies</fullName>
                </value>
                <value>
                    <fullName>TTM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DRDW_ND_Budget_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW ND Budget Master</label>
        <referenceTo>DRDW_ND_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW NDBM Category</relationshipLabel>
        <relationshipName>DRDW_NDBM_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Non_Discretionary_Year_Total__c</fullName>
        <formula>ROUND(Q1__c  +  Q2__c  +  Q3__c  +  Q4__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non-Discretionary Year Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q4__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW NDBM Category</label>
    <nameField>
        <displayFormat>ND-{0000}</displayFormat>
        <label>Non-Discretionary Budget Master Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW NDBM Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_CreateNDBudgetMaster.cls
Public without sharing Class DRDW_CreateNDBudgetMaster{ 
    
    Public DRDW_ND_Budget_Master__c obmCat {get;set;}
    Public Id currentRecordID {get; set;}
    Public Boolean isAdmin{get;set;}
    Public Boolean isAccess{get;set;}
    Public Boolean isLeader{get;set;}
    Public Boolean isFin{get;set;}
    public List<DRDW_ND_Budget_Detail__c> lDetails{get;set;}
    Public List<DRDW_NDBM_Category__c> lCategory{get;set;}
     public id LinkID {get; set;}
      public id LinkID1 {get; set;}
    
    Public DRDW_CreateNDBudgetMaster(ApexPages.StandardController controller){
        obmCat = (DRDW_ND_Budget_Master__c)controller.getRecord();
        currentRecordID = ApexPages.currentPage().getParameters().get('id');
      
        
      if(currentRecordID != null){
      
            String SobjectApiName = 'DRDW_ND_Budget_Master__c';
            Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
            Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();

            String commaSeparatedFields = '';
            for (String fieldName : fieldMap.keyset()) {
                if (commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } else {
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }

           string query = 'select ' + commaSeparatedFields + ' from ' + SobjectApiName + ' where id =\'' + currentRecordID + '\' limit 1';
           obmCat = Database.query(query);
            
           lDetails = [select id,Name,Year__c,DRDW_Cost_Center__r.Name,DRDW_Cost_Center__c from DRDW_ND_Budget_Detail__c where year__c =: obmCat.Year__c and DRDW_ND_Budget_Master__c =:obmCat.id];
           lCategory = [select id,Name,Category__c,Non_Discretionary_Year_Total__c,Q1__c,Q2__c,Q3__c,Q4__c from DRDW_NDBM_Category__c where Year__c =: obmCat.Year__c and DRDW_ND_Budget_Master__c =: obmCat.id];
        
           
           }
           else{
                obmCat.Year__c = String.valueOf(system.today().Year()); 
           }
           
        system.debug('&&&&&&&'+UserInfo.getUserId());   
       isAdmin = getUserPermission(UserInfo.getUserId());
       isFin = getUserPermissionFin(UserInfo.getUserId());
       SObjectType sObjectType = Schema.getGlobalDescribe().get('DRDW_NDBM_Category__c');
       isAccess = HasAccess(UserInfo.getUserId(), obmCat.Id);
       isLeader = getUserPermissionLeader(UserInfo.getUserId()); 
        
    }
    
    /*
     * @Method Name                    :  Save
     * @Description                    :  Method to Save the record
     * @Return Type                    :  None
     * @Parameters                     :  None
     */  
    
    Public PageReference save(){
    
        List<DRDW_ND_Budget_Master__c> lNDBMaster = new List<DRDW_ND_Budget_Master__c>();
        lNDBMaster = [select id,Year__c from DRDW_ND_Budget_Master__c];
        
        Set<String> SetCategory = new Set<String>();
        for(DRDW_ND_Budget_Master__c c:lNDBMaster){
        
            SetCategory.add(c.Year__c);
        }       
        
             if(SetCategory.contains(obmCat.Year__c)){
        
            ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR, 'A record for the selected Year already exists.');
            ApexPages.addMessage(myMsg1);
            return null;
        } 
        
        obmCat.CurrencyIsoCode = Label.DRDW_Currency_Label;
        
        insert obmCat;
            
        List<DRDW_Cost_Center__c> lCostCenters = new List<DRDW_Cost_Center__c>();
        lCostCenters = [select id from DRDW_Cost_Center__c];
        
        List<DRDW_ND_Budget_Detail__c> lDetails = new List<DRDW_ND_Budget_Detail__c>();
        
        
        if(!lCostCenters.isEmpty()){
            
            for(DRDW_Cost_Center__c c:lCostCenters){
                DRDW_ND_Budget_Detail__c detail = new DRDW_ND_Budget_Detail__c();
                detail.DRDW_Cost_Center__c = c.id;
                detail.DRDW_ND_Budget_Master__c = obmCat.id;
                detail.CurrencyIsoCode = Label.DRDW_Currency_Label;
                lDetails.add(detail);
                
            }
            
            if(!lDetails.isEmpty()){
                insert lDetails;
            }
        }
        
        Schema.DescribeFieldResult fieldResult = DRDW_NDBM_Category__c.Category__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        List<DRDW_NDBM_Category__c> lMcategory = new List<DRDW_NDBM_Category__c>();
        List<DRDW_NDBD_Category__c> lDcategory = new List<DRDW_NDBD_Category__c>();
        
        for(Schema.PicklistEntry f:ple){
        DRDW_NDBM_Category__c c = new DRDW_NDBM_Category__c();
        c.Category__c = f.getValue();
        c.Year__c = obmCat.Year__c;
        c.DRDW_ND_Budget_Master__c = obmCat.id;
        c.CurrencyIsoCode = Label.DRDW_Currency_Label;
        lMcategory.add(c);
        
        }
        
         if(!lMcategory.isEmpty()){
                insert lMcategory;
        }
        
        for(DRDW_ND_Budget_Detail__c detail:lDetails){
        for(Schema.PicklistEntry f:ple){
        DRDW_NDBD_Category__c c = new DRDW_NDBD_Category__c();
        c.Category__c = f.getValue();
        c.Year__c = obmCat.Year__c;
      
        c.DRDW_ND_Budget_Detail__c = detail.id;
        c.CurrencyIsoCode = Label.DRDW_Currency_Label;
        lDcategory.add(c);
        
        }
        }
        
        if(!lDcategory.isEmpty()){
                insert lDcategory;
        }
        
        PageReference pageref = new PageReference('/apex/DRDW_CreateNDBudgetMaster?id='+obmCat.Id+'&isEdit=false');
          pageref.setredirect(true);
          return pageref;
    }
    
    /*
     * @Method Name                    :  Edit
     * @Description                    :  Method to Edit the record
     * @Return Type                    :  None
     * @Parameters                     :  None
     */  
    
    Public PageReference edit(){
        PageReference pageref = new PageReference('/apex/DRDW_CreateNDBudgetMaster?id='+currentRecordID+'&isEdit=true');
          pageref.setredirect(true);
          return pageref;
    }
    
    public void DeleteRecord(){
    
    }
    
    
    Public Boolean getUserPermissionFin(Id UserID){
        List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserID AND PermissionSet.Name = 'DRDW_Financial_User']);
        Set<Id> lUserId = new Set<Id>();
        If(!lPermission.isEmpty()){
            For(PermissionSetAssignment p : lPermission){
                lUserId.add(p.Assignee.Id);
            }
        }
        If(lUserId.Contains(UserID)){
            return true;
        }
        
        return false;
    }  
    
    Public Boolean getUserPermissionLeader(Id UserID){
        List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserID AND (PermissionSet.Name = 'DRDW_Leadership_User' OR PermissionSet.Name = 'DRDW_Senior_Leadership_User') ]);
        Set<Id> lUserId = new Set<Id>();
        If(!lPermission.isEmpty()){
            For(PermissionSetAssignment p : lPermission){
                lUserId.add(p.Assignee.Id);
            }
        }
        If(lUserId.Contains(UserID)){
            return true;
        }
        
        return false;
    }  
    
    Public Boolean getUserPermission(Id UserID){
        List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserID AND PermissionSet.Name = 'DRDW_Business_Admin']);
        Set<Id> lUserId = new Set<Id>();
        If(!lPermission.isEmpty()){
            For(PermissionSetAssignment p : lPermission){
                lUserId.add(p.Assignee.Id);
            }
        }
        If(lUserId.Contains(UserID)){
            return true;
        }
        
        return false;
    }   
    
    /*
     * @Method Name                    :  HasAccess
     * @Description                    :  Method to check if the logged in user has access to the record
     * @Return Type                    :  Boolean
     * @Parameters                     :  User ID, Record ID
     */
    
    public boolean HasAccess(Id UserID, Id RecID){
        List<UserRecordAccess> lst = [SELECT RecordId FROM UserRecordAccess WHERE UserId = :UserID AND RecordId = :RecID AND HasEditAccess = true];
        if(!lst.isEmpty() && lst != null){
        system.debug('inside list'+lst);
        return true;
        }else {return false;}
    }
    
        public PageReference DetailLink(){
        pagereference pageref = new pagereference('/apex/DRDW_CreateNDBudgetDetail?id='+LinkID+'&isEdit=false');
        pageref.setredirect(true);
        return pageref;
    }
    
        public PageReference CategoryLink(){
        pagereference pageref = new pagereference('/apex/DRDW_CreateNDBudgetCategory?id='+LinkID1+'&isEdit=false');
        pageref.setredirect(true);
        return pageref;
    }
    
     Public PageReference AddCategory() {
        
        PageReference pageref = new PageReference('/apex/DRDW_CreateNDBudgetCategory?parentid='+currentRecordID);
        pageref.setredirect(true);
        return pageref;
        
    }   
    
    public Void updateMCategory(){
    
        update lCategory;
        lCategory = [select id,Name,Category__c,Non_Discretionary_Year_Total__c,Q1__c,Q2__c,Q3__c,Q4__c from DRDW_NDBM_Category__c where Year__c =: obmCat.Year__c and DRDW_ND_Budget_Master__c =: obmCat.id];
        
    }
    
     public Void ResetMCategory(){
    
        
        lCategory = [select id,Name,Category__c,Non_Discretionary_Year_Total__c,Q1__c,Q2__c,Q3__c,Q4__c from DRDW_NDBM_Category__c where Year__c =: obmCat.Year__c and DRDW_ND_Budget_Master__c =: obmCat.id];
        
    }
    
}