src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Lab_Testing_Required__c</fullName>
        <label>Lab Testing Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
	<fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samples to Collect</fullName>
                </value>
                <value>
                    <fullName>Lab Work Required</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency_UI__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>validation that I can only enter numeric, comma, or negative sign</description>
        <label>Frequency Backend</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Go_Sub_Activities__c</fullName>
        <label>GO Sub-Activities</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
	 <fields>
        <fullName>Order__c</fullName>
        <formula>CASE( Event_Type__c, &apos;Obtain Animals&apos;, 1, &apos;Animal Arrival&apos;, 2,&apos;Select Animals&apos;,3,&apos;Randomize Animals&apos;,4,&apos;Acclimation&apos;,5,&apos;Drug Administration&apos;,6,&apos;Pre challenge&apos;,7,&apos;Challenge&apos;,8,&apos;Post Challenge&apos;,9,&apos;Vaccination&apos;,10,&apos;Immunization&apos;,11,&apos;Clinical Observations&apos;,12,&apos;Health Observation(s)&apos;,13,&apos;Blood Sample Collection&apos;,14,&apos;Tissue Sample Collection&apos;,15,&apos;Rectal temperatures&apos;,16,&apos;Fasting&apos;,17,&apos;Swabs&apos;,18,&apos;Fecal Sample&apos;,19,&apos;Ultrasound&apos;,20,&apos;Xrays&apos;,21,&apos;Measure Shedding&apos;,22,&apos;Abscess Exudate/Culture&apos;,23,&apos;Implants&apos;,24,&apos;Scoring&apos;,25,&apos;Euthanize&apos;,26,&apos;Necropsy&apos;,27,&apos;Final Study Day&apos;,28,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Commercial Operations</fullName>
                </value>
                <value>
                    <fullName>CMC</fullName>
                </value>
                <value>
                    <fullName>Legal &amp; Compliance</fullName>
                </value>
                <value>
                    <fullName>Regulatory</fullName>
                </value>
                <value>
                    <fullName>Corporate Finance</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                    <label>Corporate</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <isActive>false</isActive>
                    <label>Finance</label>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                    <label>Manufacturing</label>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                    <isActive>false</isActive>
                    <label>R&amp;D</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_StudyScheduleBuilder.cls
public class DRDW_StudyScheduleBuilder {
    Public DRDW_Cap_Request__c oRequest{get;set;}
    Public Id requestRecordID {get; set;}
    public List<DRDW_Event__c> lEvents{get;set;}
    public List<eventWrapper> leventWrapper{get;set;}
    Public Integer index{get;set;}
    public DRDW_Capability__c oActivity{get;set;}
    Public List<SelectOption> lStudyevents{get;set;}
    Public List<SelectOption> lSubEvents{get; set;}
    Public set<String> PSAssignedResource{get;set;} 
    Public Boolean isAccess{get;set;}    
    
    public DRDW_StudyScheduleBuilder(){
        requestRecordID = ApexPages.currentPage().getParameters().get('reqId');
        if(requestRecordID!=null){
             String SobjectApiName = 'DRDW_Cap_Request__c';           
            Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
            Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
            String commaSeparatedFields = '';
            for (String fieldName : fieldMap.keyset()) {
                if (commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } else {
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }
            string query = 'select ' + commaSeparatedFields + ', Project__r.Business_Unit__c'  +' from ' + SobjectApiName + ' where id =\'' + requestRecordID + '\' limit 1';
            oRequest = Database.query(query);
            lStudyevents = new List<SelectOption>();
             For(GLBL_Global_List_of_Values__c oglbl : [Select Name,RecordType.developerName from GLBL_Global_List_of_Values__c where Active__c = True AND RecordType.DeveloperName = 'DRDW_Samples_To_Collect' order by name ASC]){
            System.debug('GLBL values'+oglbl.Name);
            lStudyevents.add(new SelectOption(oglbl.Name,oglbl.Name));
            }
            /*Schema.DescribeFieldResult describeResult = DRDW_Cap_Request__c.Lab_Testing_required__c.getDescribe();
            // get the picklist values from this describe result
            List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();
            // list of options to be returned to the VF page
            lSubEvents = new List<SelectOption>();
            for (Schema.PicklistEntry pEntry : entries) {
                if (pEntry.isActive()) {
                    lSubEvents.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
                }
            } */  
            lSubEvents = new List<SelectOption>();
            For(GLBL_Global_List_of_Values__c oglbl : [Select Name,RecordType.developerName from GLBL_Global_List_of_Values__c where Active__c = True AND RecordType.DeveloperName = 'DRDW_Elanco_Go_sub_Activity' order by name ASC]){
                System.debug('GLBL values'+oglbl.Name);
                lSubEvents.add(new SelectOption(oglbl.Name,oglbl.Name));
            }          
            oActivity = [select id from DRDW_Capability__c where DRDW_Request__c =: oRequest.id];
            leventWrapper = new List<eventWrapper>();
            generateWrapper(oActivity.Id);            
            AddEventRow();
            permissionSetAssignedResource();
            if(PSAssignedResource.contains('DRDW_GO_User')|| PSAssignedResource.contains('DRDW_Business_Admin') || PSAssignedResource.contains('DRDW_Financial_User')) {
                isAccess = true;
            }
        }
    }
    
    public void generateWrapper(Id actId){
        lEvents = [select id,Event_type__c,Frequency__c,Frequency_UI__c,Go_Sub_Activities__c,Display_Order__c from DRDW_Event__c where DRDW_Activity__c =: actId order by Order__c ASC NULLS LAST];
        if(lEvents!=null){
            for(DRDW_Event__c eve:lEvents){
                 eventWrapper oeventWrapper = new eventWrapper(leventWrapper.size()+1,true,eve,false);
                 leventWrapper.add(oeventWrapper);
            }
        }
    }
    
    public void AddEventRow(){
        Integer count = 0; 
        for(eventWrapper oeventWrapper : leventWrapper){
            if(oeventWrapper.issaved){
                count = count + 1;
            }
        }
        if(leventWrapper.size()-count == 0){
           eventWrapper oeventWrapper = new eventWrapper(leventWrapper.size()+1,false,new DRDW_Event__c(),true);
           leventWrapper.add(oeventWrapper);
        }                 
    }
    
    Public void subEventRow(){
        for(eventWrapper oeventWrapper : leventWrapper){
            if(oeventWrapper.index == index){
                try{
                    if(oeventWrapper.issaved){
                        delete oeventWrapper.eventObject;
                        leventWrapper.remove(leventWrapper.indexOf(oeventWrapper));
                    }
                    else{
                        leventWrapper.remove(leventWrapper.indexOf(oeventWrapper));
                    }
                }catch(exception e){
                    addError(e.getmessage());
                }
                break;
            }        
        }
    }
    
    Public void editSubAct(){    
        for(eventWrapper oeventWrapper : leventWrapper){
                DRDW_Event__c  tempEventObject = oeventWrapper.eventObject;           
                if(oeventWrapper.index == index){
                    oeventWrapper.subActList = new List<String>();
                    if(oeventWrapper.eventObject.Go_Sub_Activities__c !=Null && oeventWrapper.eventObject.Go_Sub_Activities__c !='' ){
                       String subAct = oeventWrapper.eventObject.Go_Sub_Activities__c;
                        subAct = subAct.substring(1,subAct.length()-1);
                        For(String s : subAct.split(', ')){
                            system.debug('s'+s);
                            oeventWrapper.subActList.add(s);
                        }
                    }
                }                
          }   
    }
    
        Public void saveEvent(){
        for(eventWrapper oeventWrapper : leventWrapper){
            DRDW_Event__c  tempEventObject = oeventWrapper.eventObject;           
            if(oeventWrapper.index == index){
                boolean iserrored = false;
                if(tempEventObject.Event_Type__c == null || tempEventObject.Frequency_UI__c == null  ){
                    addError('Please enter manadtory values.');
                    iserrored = true;
                }                           
                if(iserrored){
                    break;
                }
                try{                    
                    oEventWrapper.eventObject.Type__c ='GO';
                    oEventWrapper.eventObject.DRDW_Activity__c = oActivity.id;
                    oEventWrapper.eventObject.Study_Title__c = oRequest.Study_Title__c;
                    oEventWrapper.eventObject.Status__c = 'Unassigned';
                    String picklist = '[';   
                    for(String s:oEventWrapper.subActList){
                        picklist = picklist + s +', ' ;
                    }   
                    if(picklist.length()>1)
                    picklist = picklist.substring(0, picklist.length()-1);
                    picklist = picklist.removeEnd(',') +']';                 
                    oEventWrapper.eventObject.Go_Sub_Activities__c = picklist;
                    upsert oEventWrapper.eventObject;                    
                    oEventWrapper.issaved = true;
                    oEventWrapper.isedit = false;       
                    leventWrapper.clear();
                    generateWrapper(oActivity.Id);
                                 
                }
                catch(exception e){
                    if(e.getmessage().contains('DUPLICATE_VALUE')){
                        addError('The activity with this title already exist.');
                    }
                    else{
                        addError(e.getmessage());
                    }
                }
                break;
            }
        }
    } 
    
     public void addError(string s) {
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, s);
        ApexPages.addMessage(myMsg);
    }  
    
     Public void permissionSetAssignedResource(){
        PSAssignedResource = new set<String>();
        List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserInfo.getUserId()]); 
        for(PermissionSetAssignment opermission : lPermission){             
            PSAssignedResource.add(opermission.PermissionSet.Name);         
        } 
    }  
    
     //Wrapper Structure for Summary Modal Popup Table
    Public class eventWrapper{      
        Public Boolean issaved{get;set;}      
        Public Integer index{get;set;}
        Public Boolean isEdit{get;set;}
        Public DRDW_Event__c eventObject{get;set;}
        Public List<String> subActList{get;set;}
        Public eventWrapper(Integer index,Boolean issaved,DRDW_Event__c eventObject,Boolean isEdit){            
            this.index = index;
            this.issaved = issaved;            
            this.eventObject = eventObject;
            this.isEdit = isEdit;
        }          
    }
}