src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>ERL</fullName>
        <active>true</active>
        <label>ERL</label>
    </recordTypes>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Activity</label>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Events</relationshipLabel>
        <relationshipName>DRDW_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Category__c</fullName>
        <label>Event Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sample</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Dates_7_Day_Res__c</fullName>
        <label>Event Dates 7 Day Res</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samples to Collect</fullName>
                </value>
                <value>
                    <fullName>Lab Work Required</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>validation that I can only enter numeric, comma, or negative sign</description>
        <label>Frequency Backend</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Event_Days__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DRDW_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Resource</label>
        <referenceTo>DRDW_Resource__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event Days</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>DRDW Event Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Event Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Analytical &amp; Assay Development</fullName>
                </value>
                <value>
                    <fullName>Bacteriology</fullName>
                </value>
                <value>
                    <fullName>BioProducts</fullName>
                </value>
                <value>
                    <fullName>Chemistry</fullName>
                </value>
                <value>
                    <fullName>DDS</fullName>
                </value>
                <value>
                    <fullName>Informatics</fullName>
                </value>
                <value>
                    <fullName>Parasitology</fullName>
                </value>
                <value>
                    <fullName>Target Enablement</fullName>
                </value>
                <value>
                    <fullName>Virology</fullName>
                </value>
                <value>
                    <fullName>FD Laboratory</fullName>
                </value>
                <value>
                    <fullName>Animal Care</fullName>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                </value>
                <value>
                    <fullName>FD Study Management</fullName>
                </value>
                <value>
                    <fullName>FD Veterinary Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hours_Available_Per_Day__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hours Available Per Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_per_Week__c</fullName>
        <label>Hours per Week</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Animal Caretaker</fullName>
                </value>
                <value>
                    <fullName>Clinical Associate</fullName>
                </value>
                <value>
                    <fullName>ERL Scientist</fullName>
                </value>
                <value>
                    <fullName>Functional Head</fullName>
                </value>
                <value>
                    <fullName>Laboratory Scientist</fullName>
                </value>
                <value>
                    <fullName>Study Manager</fullName>
                </value>
                <value>
                    <fullName>Study Monitor</fullName>
                </value>
                <value>
                    <fullName>Veterinarian</fullName>
                </value>
                <value>
                    <fullName>Vet Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DRDW_GOResourceViewCtrl.cls
@isTest
private class Test_DRDW_GOResourceViewCtrl {
    static testMethod void testwithBudget() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
            lprojects[0].Project_Name__c='Test';
            lprojects[1].Idea_Name__c='Test';       
            insert lprojects;
            System.debug([Select name from DRDW_Project__c where id =:lprojects[1].Id]);
            
             Id reqRecType = DRDW_TestDataFactory.getObjectRecordTypeId(DRDW_Cap_Request__c.SObjectType, 'GO');
            
            DRDW_Cap_Request__c oCapReq = new DRDW_Cap_Request__c(Project__c=lprojects[1].Id,Study_Manager__c=busAdm.Id,recordtypeid=reqRecType );
            insert oCapReq;
            
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilitieswithreq(1, 'Idea Capability',lprojects[0].id,oCapReq.Id);
            insert lCapab;
            
            DRDW_Event__c oEvent = new DRDW_Event__c(DRDW_Activity__c=lCapab[0].Id,Event_Category__c='Lab',Event_Type__c='Lab Work Required',Frequency__c='',Event_Dates_7_Day_Res__c='2018-03-01');
            insert oEvent;

            DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active',Days_Per_Week__c='7');
            insert oResource;

            DRDW_Event_Days__c oEvDay = new DRDW_Event_Days__c(Allocated_Hours__c=10.00,Date__c=System.today(),DRDW_Event__c=oEvent.Id,DRDW_Resource__c=oResource.Id,Type__c='GO');
            insert oEvDay;
            
            DRDW_Calender_Per_Roaster__c calPerRoaster = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster.Allocated_Date__c = System.today();
            calPerRoaster.Allocated_Hours__c = 8;
            calPerRoaster.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster;
            DRDW_Calender_Per_Roaster__c calPerRoaster1 = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster1.Allocated_Date__c = System.today().addDays(1);
            calPerRoaster1.Allocated_Hours__c = 8;
            calPerRoaster1.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster1;

            DRDW_GOResourceViewCtrl controller = new DRDW_GOResourceViewCtrl();
            controller.gogroup ='All';
            controller.executeWrapperGenerator();
            controller.executeWrapperGeneratorOnLoad();
            controller.executeWrapperGeneratorExport();
            controller.gogroup='Animal Care';
            controller.exportResource();
            controller.executeWrapperGenerator();
            
            System.assertNotEquals(null, calPerRoaster1.id, 'error');
        }
    }
}