src/objects/DRDW_Assign_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Area__c</fullName>
        <label>Activity Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Title__c</fullName>
        <label>Activity Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allocation_End_Date__c</fullName>
        <label>Allocation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Allocation_Start_Date__c</fullName>
        <label>Allocation Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DRDW_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Activity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>DRDW_Capability__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Request Activity</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Capability__c.DRDW_Request__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>ERL</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Capability__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Study Activity</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Capability__c.DRDW_Request__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>GO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Assign Resources</relationshipLabel>
        <relationshipName>DRDW_Assign_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Assign Resources</relationshipLabel>
        <relationshipName>DRDW_Assign_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DRDW_Resources__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Resource</label>
        <referenceTo>DRDW_Resource__c</referenceTo>
        <relationshipLabel>DRDW Assign Resources</relationshipLabel>
        <relationshipName>DRDW_Assign_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency Backend</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Go_Sub_Activities__c</fullName>
        <label>GO Sub-Activities</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Animal Care</fullName>
                </value>
                <value>
                    <fullName>FD Laboratory</fullName>
                </value>
                <value>
                    <fullName>FD Study Management</fullName>
                </value>
                <value>
                    <fullName>FD Veterinary Support</fullName>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hours_Per_Day__c</fullName>
        <label>Hours Per Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Task__c</fullName>
        <label>Other Task</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Assign Resource</label>
    <nameField>
        <displayFormat>AssRes-{0000}</displayFormat>
        <label>DRDW Assign Res</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Assign Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Activity</label>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Events</relationshipLabel>
        <relationshipName>DRDW_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Dates__c</fullName>
        <label>Event Dates</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>validation that I can only enter numeric, comma, or negative sign</description>
        <label>Frequency Backend</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Go_Sub_Activities__c</fullName>
        <label>GO Sub-Activities</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Partially Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Event_Days__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Go_Sub_Activities__c</fullName>
        <label>Go Sub Activities</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event Days</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>DRDW Event Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Event Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_Event_Controller.cls
public with sharing class DRDW_Event_Controller {
    public DRDW_Event__c oEvent{get;set;}
    public string currentRecordID{get;set;}
    public list<DRDW_Assign_Resource__c> lAssignedResources{get;set;}
    public string AssignedResourceId{get;set;}
    public boolean showRelatedList{get;set;}
    public boolean showRemoveButton{get;set;}
    public Set<String> sPermissionAssigned;
    public DRDW_Event_Controller (ApexPages.StandardController controller){
        currentRecordID = ApexPages.currentPage().getParameters().get('id');
        oEvent = (DRDW_Event__c)controller.getRecord();
        if(currentRecordID != null){
            String SobjectApiName = 'DRDW_Event__c';
            Map<String, Schema.SObjectType> schemaMap = schema.getGlobalDescribe();
            Map<String, Schema.SObjectField> fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
            String commaSeparatedFields = '';
            for(String fieldName : fieldMap.keyset()){
                if(commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } 
                else{
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }
            string query = 'select ' + commaSeparatedFields + ',DRDW_Activity__r.DRDW_Request__r.Name ' + ' from ' + SobjectApiName + ' where id =\'' + string.escapesinglequotes(currentRecordID) + '\' limit 1';
            oEvent = Database.query(query);           
            checkDataVisibility();
        }
    }
    
    /*
    * @Method Name                    :  DeleteRecord
    * @Description                    :  Method for deleting the record
    * @Return Type                    :  PageReference
    * @Parameters                     :  None
    */
    Public PageReference DeleteRecord(){
        try{        
            Database.delete([Select id from DRDW_Assign_Resource__c where Id=:AssignedResourceId]); 
       /*     List<DRDW_Event_Days__c> lEventdays = new List<DRDW_Event_Days__c>();   
            Map<Id,List<String>> mEventFrequency = new Map<Id,List<String>>();             
            lEventdays = [select id,Date__c,DRDW_Event__c,frequency__c,Go_Sub_Activities__c from DRDW_Event_Days__c where DRDW_Event__c =:currentRecordID];
            for(DRDW_Event_Days__c evtDay:lEventdays){
                if(!mEventFrequency.containsKey(evtDay.DRDW_Event__c)){
                    mEventFrequency.put(evtDay.DRDW_Event__c,new List<String>());
                }
                mEventFrequency.get(evtDay.DRDW_Event__c).add(evtDay.Frequency__c);
            }   
            Integer count=0;
            List<String> evtFrequency = oEvent.Frequency__c.split(',');
            if(mEventFrequency.get(oEvent.id)!=null){
            List<String> dayFrequency = mEventFrequency.get(oEvent.id);        
            for(String f:dayFrequency){
                if(evtFrequency.contains(f)){
                    count++;
                }
            }
            }
            if(count ==evtFrequency.size()){
                oEvent.Status__c = 'Assigned';
            }else if(count < evtFrequency.size() && count!=0){
                oEvent.Status__c = 'Partially Assigned';
            }else{
                oEvent.Status__c = 'Unassigned';
            }
            update oEvent;  */
            
             List<DRDW_Event__c> lEvents = new List<DRDW_Event__c>();
                  lEvents = [select id,Event_Dates__c,Status__c,frequency__c,Go_Sub_Activities__c,Type__c from DRDW_Event__c where Id =: currentRecordID and Type__c = 'GO'];
                  List<DRDW_Assign_Resource__c> lAssignRes = [select id,Go_Sub_Activities__c,DRDW_Event__c from DRDW_Assign_Resource__c where DRDW_Event__c in:lEvents];
                  
                  Map<Id,List<DRDW_Assign_Resource__c>> mapofeventResource = new  Map<Id,List<DRDW_Assign_Resource__c>>();
                  Map<Id,Set<String>> mapEventSub = new Map<Id,Set<String>>();
                  Map<Id,Set<String>> mapEventSubchild = new Map<Id,Set<String>>();
                  
                   if(lEvents.size()>0){
                        for(DRDW_Event__c eve:lEvents){
                            List<String> lsubact = new List<String>();
                            lsubact = eve.Go_Sub_Activities__c.replace('[','').replace(']','').split(', ');              
                            if(!mapEventSub.containskey(eve.id)){
                                Set<String> ssubact = new Set<String>();
                                mapEventSub.put(eve.id,ssubact);
                            }
                            mapEventSub.get(eve.id).addAll(lsubact);
                        }
                        
                        if(lAssignRes.size()>0){
                            for(DRDW_Assign_Resource__c oAssign:lAssignRes){
                                if(!mapEventSubchild.containskey(oAssign.DRDW_Event__c)){
                                    Set<String> ssubact = new Set<String>();
                                    mapEventSubchild.put(oAssign.DRDW_Event__c,ssubact);
                                }
                                mapEventSubchild.get(oAssign.DRDW_Event__c).add(oAssign.Go_Sub_Activities__c);
                            }
                        
                        
                        for(DRDW_Event__c eve:lEvents){
                            if(mapEventSubchild.get(eve.id).size()==mapEventSub.get(eve.id).size()){
                                eve.Status__c = 'Assigned';
                            }else{
                                eve.Status__c = 'Partially Assigned';
                            }
                        }
                        }else{
                            for(DRDW_Event__c eve:lEvents){
                                eve.Status__c = 'Unassigned';
                        }
                        }
                   }
                   
                update lEvents;            
                        
            PageReference pageref = new PageReference('/apex/DRDW_Event?id='+currentRecordID);
            pageref.setredirect(true);
            return pageref;
        }
        catch(exception e){
            addError(e.getmessage());
            return null;
        }
    }
    
    public void addError(string s) {
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, s);
        ApexPages.addMessage(myMsg);
    }
    
    public void checkDataVisibility(){
        showRelatedList =  false;
        showRemoveButton = false;
        sPermissionAssigned = new set<String>();
        List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserInfo.getUserId()]); 
        for(PermissionSetAssignment opermission : lPermission){             
            sPermissionAssigned.add(opermission.PermissionSet.Name);         
        } 
        if(sPermissionAssigned.contains('DRDW_GO_User') || sPermissionAssigned.contains('DRDW_Senior_Leadership_User') || sPermissionAssigned.contains('DRDW_Business_Admin')
                || sPermissionAssigned.contains('DRDW_Financial_User')) {
            showRelatedList =  true;
            showRemoveButton = true;
            if(sPermissionAssigned.contains('DRDW_Senior_Leadership_User')){
                showRemoveButton = false;
            }
            lAssignedResources = [Select Id,Name,Activity_Area__c,DRDW_Resources__r.Name__r.Name,Activity_Title__c,Allocation_End_Date__c,Allocation_Start_Date__c,DRDW_Event__c,Hours_Per_Day__c,Group__c,Other_Task__c,Task__c,Frequency_UI__c,Go_Sub_Activities__c from DRDW_Assign_Resource__c where DRDW_Event__c=:currentRecordID];
        }else{
            lAssignedResources = [Select Id,Name,Activity_Area__c,DRDW_Resources__r.Name__r.Name,Activity_Title__c,Allocation_End_Date__c,Allocation_Start_Date__c,DRDW_Event__c,Hours_Per_Day__c,Group__c,Other_Task__c,Task__c,Frequency_UI__c,Go_Sub_Activities__c from DRDW_Assign_Resource__c where DRDW_Event__c=:currentRecordID and DRDW_Resources__r.Name__c =: UserInfo.getUserId()];
            showRelatedList = true;
        }
    }   
}