src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned DTG date on the Project if an Evaluation Project, the Planned DTA date on the Project if a Generation Project, the Planned DP1 date on the Project if an Assessment Project.It is editable</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <description>DTE date on the Project if an Evaluation Project, the DTG date on the Project if a Generation Project, the DTA date on the Project if an Assessment Project. It is editable</description>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>ERL</fullName>
        <active>true</active>
        <label>ERL</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capability__c</fullName>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned End Date</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <inlineHelpText>Decision to Evaluate (DTE):</inlineHelpText>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
  <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <description>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</description>
        <inlineHelpText>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</inlineHelpText>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Activity</label>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Events</relationshipLabel>
        <relationshipName>DRDW_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Category__c</fullName>
        <label>Event Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sample</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samples to Collect</fullName>
                </value>
                <value>
                    <fullName>Lab Work Required</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>validation that I can only enter numeric, comma, or negative sign</description>
        <label>Frequency Backend</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Event_Days__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DRDW_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Resource</label>
        <referenceTo>DRDW_Resource__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event Days</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>DRDW Event Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Event Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DRDW_ERLProjectViewCtrl.cls
@isTest
private class Test_DRDW_ERLProjectViewCtrl {
  static testMethod void testwithBudget() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
          List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
          lprojects[0].Project_Name__c='Test';
          lprojects[1].Idea_Name__c='Test';       
            insert lprojects;
            System.debug([Select name from DRDW_Project__c where id =:lprojects[1].Id]);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;
            
          DRDW_Cap_Request__c oCapReq = new DRDW_Cap_Request__c(Project__c=lprojects[1].Id,Study_Manager__c=busAdm.Id);
          insert oCapReq;
          
           Id requestTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('ERL').getRecordTypeId();
            DRDW_Cap_Request__c oRequest = new DRDW_Cap_Request__c();
            oRequest.recordtypeid = requestTypeid;
            oRequest.Project__c=lprojects[0].id;
            insert oRequest;
            System.assertNotEquals(null,oRequest,'error');
            DRDW_Capability__c oCap = new DRDW_Capability__c();
            oCap.Planned_Start_Date__c = system.today();
            oCap.Planned_End_Date__c = system.today().addDays(3);
            oCap.Proposed_Start_Date__c= system.today();
            oCap.DRDW_Request__c = oRequest.id;
            insert oCap;                    
            
            DRDW_Capability__c oCap1 = new DRDW_Capability__c();
            oCap1.DRDW_Request__c = oRequest.id;
            insert oCap1;
            
             DRDW_Event__c oEvent = new DRDW_Event__c(DRDW_Activity__c=oCap.Id,Event_Category__c='Lab',Event_Type__c='Lab Work Required',Frequency__c='');
          insert oEvent;

          DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active');
          insert oResource;

          DRDW_Event_Days__c oEvDay = new DRDW_Event_Days__c(Allocated_Hours__c=10.00,Date__c=System.today(),DRDW_Event__c=oEvent.Id,DRDW_Resource__c=oResource.Id,Type__c='ERL');
          insert oEvDay;

          DRDW_ERLProjectViewCtrl controller = new DRDW_ERLProjectViewCtrl();
          controller.getStatusList();
          controller.executeWrapperGeneratorERL();
          controller.getActivityAreaList();
          controller.validateActivityArea();
          controller.initilizeAssignResource();
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today();
          controller.oAssignResource.Allocation_End_Date__c = system.today().addDays(4);
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          controller.assignResource();
          controller.getTotalAllocatedHours(system.today(),system.today().addDays(2),3.0);
          controller.initilizeActivity();
          controller.oActivity.DRDW_Request__c = oRequest.id;
          controller.oActivity.Capability__c = 'test';
          controller.oActivity.Capability_Area__c = 'test';
          controller.oActivity.Planned_Start_Date__c =system.today();
          controller.oActivity.Planned_End_Date__c = system.today().addDays(2);
          controller.oActivity.Title__c ='test';
          controller.saveActivity();
          controller.oActivity.Capability__c = null;
          controller.oActivity.Planned_Start_Date__c =system.today();
          controller.oActivity.Planned_End_Date__c = system.today().addDays(2);
          controller.oActivity.Title__c ='test';
          controller.saveActivity();
          controller.oActivity.Capability__c = 'test';
          controller.oActivity.Planned_Start_Date__c =system.today().addDays(2);
          controller.oActivity.Planned_End_Date__c = system.today();
          controller.oActivity.Title__c ='test';
          controller.saveActivity();          
          controller.export();
          
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today();
          controller.oAssignResource.Allocation_End_Date__c = system.today();
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          controller.selectedResource = oResource.id;
          controller.assignResource();
        }
    }
    
     static testMethod void testwithBudget1() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
          List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
          lprojects[0].Project_Name__c='Test';
          lprojects[1].Idea_Name__c='Test';       
            insert lprojects;
            System.debug([Select name from DRDW_Project__c where id =:lprojects[1].Id]);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

         


          DRDW_Cap_Request__c oCapReq = new DRDW_Cap_Request__c(Project__c=lprojects[1].Id,Study_Manager__c=busAdm.Id);
          insert oCapReq;
          
           Id requestTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('ERL').getRecordTypeId();
            DRDW_Cap_Request__c oRequest = new DRDW_Cap_Request__c();
            oRequest.recordtypeid = requestTypeid;
            oRequest.Project__c=lprojects[0].id;
            insert oRequest;
            System.assertNotEquals(null,oRequest,'error');
            DRDW_Capability__c oCap = new DRDW_Capability__c();
            oCap.Planned_Start_Date__c = system.today();
            oCap.Planned_End_Date__c = system.today().addDays(3);
            oCap.Proposed_Start_Date__c= system.today();
            oCap.Capability__c = 'API Characterization';
            oCap.Capability_Area__c = 'DDS';
            oCap.DRDW_Request__c = oRequest.id;
            insert oCap;                    
            
            DRDW_Capability__c oCap1 = new DRDW_Capability__c();
            oCap1.DRDW_Request__c = oRequest.id;
            insert oCap1;
            
          DRDW_Event__c oEvent = new DRDW_Event__c(DRDW_Activity__c=oCap.Id);
          insert oEvent;

          DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active');
          insert oResource;

          DRDW_Event_Days__c oEvDay = new DRDW_Event_Days__c(Allocated_Hours__c=10.00,Date__c=System.today(),DRDW_Event__c=oEvent.Id,DRDW_Resource__c=oResource.Id,Type__c='ERL');
          insert oEvDay;
          
          DRDW_Calender_Per_Roaster__c calPerRoaster = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster.Allocated_Date__c = System.today();
            calPerRoaster.Allocated_Hours__c = 8;
            calPerRoaster.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster;
            DRDW_Calender_Per_Roaster__c calPerRoaster1 = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster1.Allocated_Date__c = System.today().addDays(1);
            calPerRoaster1.Allocated_Hours__c = 8;
            calPerRoaster1.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster1;

          DRDW_ERLProjectViewCtrl controller = new DRDW_ERLProjectViewCtrl();
          controller.getStatusList();
          controller.activitStatus = 'Assigned';
          controller.executeWrapperGeneratorERL();
          controller.getActivityAreaList();
          controller.validateActivityArea();
          controller.initilizeAssignResource();
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today();
          controller.oAssignResource.Allocation_End_Date__c = system.today().addDays(4);
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          controller.assignResource();
          controller.getTotalAllocatedHours(system.today(),system.today().addDays(2),3.0);
          controller.initilizeActivity();
          controller.oActivity.DRDW_Request__c = oRequest.id;
          controller.oActivity.Capability__c = 'test';
          controller.oActivity.Capability_Area__c = 'test';
          controller.oActivity.Planned_Start_Date__c =system.today();
          controller.oActivity.Planned_End_Date__c = system.today().addDays(2);
          controller.oActivity.Title__c ='test';
          controller.saveActivity();          
          controller.export();
          
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today();
          controller.oAssignResource.Allocation_End_Date__c = system.today();
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          controller.selectedResource = oResource.id;
          controller.assignResource();
        }
    }
      static testMethod void testwithBudget2() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
          List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
          lprojects[0].Project_Name__c='Test';
          lprojects[1].Idea_Name__c='Test';       
            insert lprojects;
            System.debug([Select name from DRDW_Project__c where id =:lprojects[1].Id]);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

         


          DRDW_Cap_Request__c oCapReq = new DRDW_Cap_Request__c(Project__c=lprojects[1].Id,Study_Manager__c=busAdm.Id);
          insert oCapReq;
          
           Id requestTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('ERL').getRecordTypeId();
            DRDW_Cap_Request__c oRequest = new DRDW_Cap_Request__c();
            oRequest.recordtypeid = requestTypeid;
            oRequest.Project__c=lprojects[0].id;
            insert oRequest;
            System.assertNotEquals(null,oRequest,'error');
            DRDW_Capability__c oCap = new DRDW_Capability__c();
            oCap.Planned_Start_Date__c = system.today();
            oCap.Planned_End_Date__c = system.today().addDays(3);
            oCap.Proposed_Start_Date__c= system.today();
            oCap.Capability__c = 'API Characterization';
            oCap.Capability_Area__c = 'DDS';
            oCap.DRDW_Request__c = oRequest.id;
            insert oCap;                    
            
            DRDW_Capability__c oCap1 = new DRDW_Capability__c();
            oCap1.DRDW_Request__c = oRequest.id;
            insert oCap1;
            
          DRDW_Event__c oEvent = new DRDW_Event__c(DRDW_Activity__c=oCap.Id);
          insert oEvent;

          DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active');
          insert oResource;

          DRDW_Event_Days__c oEvDay = new DRDW_Event_Days__c(Allocated_Hours__c=10.00,Date__c=System.today(),DRDW_Event__c=oEvent.Id,DRDW_Resource__c=oResource.Id,Type__c='ERL');
          insert oEvDay;
          
          DRDW_Calender_Per_Roaster__c calPerRoaster = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster.Allocated_Date__c = System.today();
            calPerRoaster.Allocated_Hours__c = 8;
            calPerRoaster.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster;
            DRDW_Calender_Per_Roaster__c calPerRoaster1 = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster1.Allocated_Date__c = System.today().addDays(1);
            calPerRoaster1.Allocated_Hours__c = 8;
            calPerRoaster1.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster1;

          DRDW_ERLProjectViewCtrl controller = new DRDW_ERLProjectViewCtrl();
          Test.setCurrentPageReference(new PageReference('DRDW_ERLView'));
          System.currentPageReference().getParameters().put('resourceId', oResource.Id);
          controller.getStatusList();
          controller.activitStatus = 'Assigned';
          controller.executeWrapperGeneratorERL();
          controller.getActivityAreaList();
          controller.validateActivityArea();
          controller.initilizeAssignResource();
         
          
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today();
          controller.oAssignResource.Allocation_End_Date__c = system.today();
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          System.currentPageReference().getParameters().put('selectedResource', oResource.Id);
          controller.assignResource();
        }
    }
    
    static testMethod void testwithBudget3() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
          List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
          lprojects[0].Project_Name__c='Test';
          lprojects[1].Idea_Name__c='Test';       
            insert lprojects;
            System.debug([Select name from DRDW_Project__c where id =:lprojects[1].Id]);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

          DRDW_Cap_Request__c oCapReq = new DRDW_Cap_Request__c(Project__c=lprojects[1].Id,Study_Manager__c=busAdm.Id);
          insert oCapReq;
          
           Id requestTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('ERL').getRecordTypeId();
            DRDW_Cap_Request__c oRequest = new DRDW_Cap_Request__c();
            oRequest.recordtypeid = requestTypeid;
            oRequest.Project__c=lprojects[0].id;
            insert oRequest;
            System.assertNotEquals(null,oRequest,'error');
            DRDW_Capability__c oCap = new DRDW_Capability__c();
            oCap.Planned_Start_Date__c = system.today();
            oCap.Planned_End_Date__c = system.today().addDays(3);
            oCap.Proposed_Start_Date__c= system.today();
            oCap.Capability__c = 'API Characterization';
            oCap.Capability_Area__c = 'DDS';
            oCap.DRDW_Request__c = oRequest.id;
            insert oCap;                    
            
            DRDW_Capability__c oCap1 = new DRDW_Capability__c();
            oCap1.DRDW_Request__c = oRequest.id;
            insert oCap1;
            
          DRDW_Event__c oEvent = new DRDW_Event__c(DRDW_Activity__c=oCap.Id);
          insert oEvent;

          DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active');
          insert oResource;
                   
          DRDW_Calender_Per_Roaster__c calPerRoaster = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster.Allocated_Date__c = System.today();
            calPerRoaster.Allocated_Hours__c = 8;
            calPerRoaster.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster;
            DRDW_Calender_Per_Roaster__c calPerRoaster1 = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster1.Allocated_Date__c = System.today().addDays(1);
            calPerRoaster1.Allocated_Hours__c = 8;
            calPerRoaster1.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster1;

          DRDW_ERLProjectViewCtrl controller = new DRDW_ERLProjectViewCtrl();
          Test.setCurrentPageReference(new PageReference('DRDW_ERLView'));
          System.currentPageReference().getParameters().put('resourceId', oResource.Id);
          controller.getStatusList();
          controller.activitStatus = 'Assigned';
          controller.executeWrapperGeneratorERL();
          controller.getActivityAreaList();
          controller.validateActivityArea();
          controller.initilizeAssignResource();        
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c= system.today();
          controller.oAssignResource.Allocation_End_Date__c = system.today();
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          System.currentPageReference().getParameters().put('selectedResource', oResource.Id);
          controller.assignResource();
          
           controller.initilizeAssignResource();        
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today().addDays(2);
          controller.oAssignResource.Allocation_End_Date__c = system.today().addDays(2);
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          System.currentPageReference().getParameters().put('selectedResource', oResource.Id);
          controller.assignResource();
          
        }
    }
    
        static testMethod void testwithBudget4() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Project_Manager');
        System.runAs(busAdm) {
          List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
          lprojects[0].Project_Name__c='Test';
          lprojects[1].Idea_Name__c='Test';       
            insert lprojects;
            System.debug([Select name from DRDW_Project__c where id =:lprojects[1].Id]);
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Idea Capability',lprojects[0].id);
            insert lCapab;

          DRDW_Cap_Request__c oCapReq = new DRDW_Cap_Request__c(Project__c=lprojects[1].Id,Study_Manager__c=busAdm.Id);
          insert oCapReq;
          
           Id requestTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('ERL').getRecordTypeId();
            DRDW_Cap_Request__c oRequest = new DRDW_Cap_Request__c();
            oRequest.recordtypeid = requestTypeid;
            oRequest.Project__c=lprojects[0].id;
            insert oRequest;
            System.assertNotEquals(null,oRequest,'error');
            DRDW_Capability__c oCap = new DRDW_Capability__c();
            oCap.Planned_Start_Date__c = system.today();
            oCap.Planned_End_Date__c = system.today().addDays(3);
            oCap.Proposed_Start_Date__c= system.today();
            oCap.Capability__c = 'API Characterization';
            oCap.Capability_Area__c = 'DDS';
            oCap.DRDW_Request__c = oRequest.id;
            insert oCap;                    
            
            DRDW_Capability__c oCap1 = new DRDW_Capability__c();
            oCap1.DRDW_Request__c = oRequest.id;
            insert oCap1;
            
          DRDW_Event__c oEvent = new DRDW_Event__c(DRDW_Activity__c=oCap.Id);
          insert oEvent;

          DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active');
          insert oResource;
                   
          DRDW_Calender_Per_Roaster__c calPerRoaster = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster.Allocated_Date__c = System.today();
            calPerRoaster.Allocated_Hours__c = 8;
            calPerRoaster.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster;
            DRDW_Calender_Per_Roaster__c calPerRoaster1 = new DRDW_Calender_Per_Roaster__c();
            calPerRoaster1.Allocated_Date__c = System.today().addDays(1);
            calPerRoaster1.Allocated_Hours__c = 8;
            calPerRoaster1.DRDW_Roaster__c = oResource.id;
            insert calPerRoaster1;

          DRDW_ERLProjectViewCtrl controller = new DRDW_ERLProjectViewCtrl();
          Test.setCurrentPageReference(new PageReference('DRDW_ERLView'));
          System.currentPageReference().getParameters().put('resourceId', oResource.Id);
          controller.getStatusList();
          controller.activitStatus = 'Assigned';
          controller.executeWrapperGeneratorERL();
          controller.getActivityAreaList();
          controller.validateActivityArea();
          controller.initilizeAssignResource();        
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c= system.today();
          controller.oAssignResource.Allocation_End_Date__c = system.today();
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          System.currentPageReference().getParameters().put('selectedResource', oResource.Id);
          controller.assignResource();
          
           controller.initilizeAssignResource();        
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today().addDays(2);
          controller.oAssignResource.Allocation_End_Date__c = system.today().addDays(3);
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          System.currentPageReference().getParameters().put('selectedResource', oResource.Id);
          controller.assignResource();
          
          controller.initilizeAssignResource();        
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;         
          controller.oAssignResource.Allocation_End_Date__c = system.today().addDays(3);
          controller.oAssignResource.Hours_Per_Day__c = 9;          
          controller.next();
          
          controller.initilizeAssignResource();        
          controller.oAssignResource.DRDW_Activity__c = oCap.Id;
          controller.oAssignResource.Allocation_Start_Date__c=system.today().addDays(2);
          controller.oAssignResource.Allocation_End_Date__c = system.today().addDays(3);
          controller.oAssignResource.Hours_Per_Day__c = -1;          
          controller.next();
          
        }
    }
}