src/objects/DRDW_Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Line Items</relationshipLabel>
        <relationshipName>DRDW_Budget_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Master__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Name__c</fullName>
        <label>Activity Name Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capability Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>DRDW_Capability__c.Related_Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Related_To__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Idea_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Assessment_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Generation_Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendorr__c</fullName>
        <label>Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>project_name__c</fullName>
        <formula>Related_To__r.Name__c</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>DRDW Budget Master</label>
    <nameField>
        <displayFormat>BGT-{0000}</displayFormat>
        <label>DRDW Budget Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_CreateBudgetLineItem.cls
Public without sharing Class DRDW_CreateBudgetLineItem{ 
    Public Id currentRecordID {get; set;}
    Public Id BudgetMasterId {get;set;}
    Public Boolean isAdmin{get;set;}
    Public Boolean isFin{get;set;}
    Public DRDW_Budget_Line_Item__c oLineItem{get;set;}
    Public string ParentName {get; set;}
    public Id PrjId {get; set;}
    public boolean isGen {get; set;}
    public boolean isEval {get; set;}
    public boolean isAssess {get; set;}
    Public DRDW_CreateBudgetLineItem(ApexPages.StandardController controller){
        currentRecordID = ApexPages.currentPage().getParameters().get('id');
        BudgetMasterId = ApexPages.currentPage().getParameters().get('BudgetId');
        oLineItem = (DRDW_Budget_Line_Item__c)controller.getRecord();
        DRDW_Budget_Master__c oBudget = new DRDW_Budget_Master__c();
        if(currentRecordID != null){   
            String SobjectApiName = 'DRDW_Budget_Line_Item__c';
            Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
            Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
            String commaSeparatedFields = '';
            for (String fieldName : fieldMap.keyset()) {
                if (commaSeparatedFields == null || commaSeparatedFields == '') {
                    commaSeparatedFields = fieldName;
                } else {
                    commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
                }
            }
            string query = 'select ' + commaSeparatedFields + ', Related_To__r.Title__c, Related_To__r.Related_To__r.Project_Name__c, Related_To__r.Related_To__r.Idea_Name__c' + ' from ' + SobjectApiName + ' where id =\'' + currentRecordID + '\' limit 1';
            oLineItem = Database.query(query);

            BudgetMasterId = oLineItem.Related_To__c;
            oBudget = [select id,PO__c,Activity_Name__c,Title__c,Activity__c,Vendorr__c,Related_To__r.RecordType.Name,Related_To__c from DRDW_Budget_Master__c where id =: BudgetMasterId Limit 1];
            if(oBudget.Related_To__r.RecordType.Name == 'Idea Project'){
                isEval = true;
            }else if(oBudget.Related_To__r.RecordType.Name == 'Generation Project'){
                isGen = true;
            }else if(oBudget.Related_To__r.RecordType.Name == 'Assessment Project'){
                isAssess = true;
            }
        }
        else{
            oBudget = [select id,PO__c,Activity_Name__c,Title__c,Activity__c,Vendorr__c,Related_To__r.RecordType.Name,Related_To__c from DRDW_Budget_Master__c where id =: BudgetMasterId Limit 1];
            if(oBudget.Related_To__r.RecordType.Name == 'Idea Project'){
                isEval = true;
            }
            else if(oBudget.Related_To__r.RecordType.Name == 'Generation Project'){
                isGen = true;
            }
            else if(oBudget.Related_To__r.RecordType.Name == 'Assessment Project'){
                isAssess = true;
            }

            ParentName = oBudget.Title__c;
            PrjId = oBudget.Related_To__c;
            oLineItem.PO__c = oBudget.PO__c;       
            if(oBudget.Activity__c != NULL){
                oLineItem.Activity__c = oBudget.Title__c;
            }
            oLineItem.Vendor__c = oBudget.Vendorr__c;
            oLineItem.Related_To__c = BudgetMasterId;
        }
        isAdmin = getUserPermission(UserInfo.getUserId());
        isFin = getUserPermissionFin(UserInfo.getUserId());
    }


    /*
    * @Method Name                    :  Save
    * @Description                    :  Method to Save the record
    * @Return Type                    :  None
    * @Parameters                     :  None
    */  

    Public PageReference save(){
        try{
            upsert oLineItem;
            PageReference pageref = new PageReference('/apex/DRDW_CreateBudgetMaster?id='+BudgetMasterId+'&isEdit=false&section=#Budget_Line');
            pageref.setredirect(true);
            return pageref;
        }
        catch(Exception e){
            if(e.getmessage().contains('FIELD_FILTER_VALIDATION_EXCEPTION')){
                ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR, 'Cannot Create BudgetLineItem for Inactive CostCenter');
                ApexPages.addMessage(myMsg1);
                return null;
            }else {
                ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please check the posting date year, cannot be greater than current year and less than previous year');
                ApexPages.addMessage(myMsg1);
                return null;
            }
        }
    }

    /*
    * @Method Name                    :  Edit
    * @Description                    :  Method to Edit the record
    * @Return Type                    :  None
    * @Parameters                     :  None
    */  

    Public PageReference edit(){
        PageReference pageref = new PageReference('/apex/DRDW_CreateBudgetLineItem?id='+currentRecordID+'&isEdit=true');
        pageref.setredirect(true);
        return pageref;
    }

    Public PageReference DeleteRecord(){
        delete oLineItem;
        PageReference pageref = new PageReference('/apex/DRDW_CreateBudgetMaster?id='+budgetMasterId+'&isEdit=false');
        pageref.setredirect(true);
        return pageref;
    }


    Public Boolean getUserPermission(Id UserID){
        List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserID AND PermissionSet.Name = 'DRDW_Business_Admin']);
        Set<Id> lUserId = new Set<Id>();
        If(!lPermission.isEmpty()){
            For(PermissionSetAssignment p : lPermission){
                lUserId.add(p.Assignee.Id);
            }
        }
        If(lUserId.Contains(UserID)){
            return true;
        }
        return false;
    }   

    Public Boolean getUserPermissionFin(Id UserID){
        List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserID AND PermissionSet.Name = 'DRDW_Financial_User']);
        Set<Id> lUserId = new Set<Id>();
        If(!lPermission.isEmpty()){
            For(PermissionSetAssignment p : lPermission){
                lUserId.add(p.Assignee.Id);
            }
        }
        If(lUserId.Contains(UserID)){
            return true;
        }
        return false;
    }
}