src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned DTG date on the Project if an Evaluation Project, the Planned DTA date on the Project if a Generation Project, the Planned DP1 date on the Project if an Assessment Project.It is editable</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <description>DTE date on the Project if an Evaluation Project, the DTG date on the Project if a Generation Project, the DTA date on the Project if an Assessment Project. It is editable</description>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>ERL</fullName>
        <active>true</active>
        <label>ERL</label>
    </recordTypes>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned End Date</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <inlineHelpText>Decision to Evaluate (DTE):</inlineHelpText>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Activity</label>
        <referenceTo>DRDW_Capability__c</referenceTo>
        <relationshipLabel>DRDW Events</relationshipLabel>
        <relationshipName>DRDW_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Event_Days__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event Days</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>DRDW Event Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Event Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_ActivityERLFlow.cls
public class DRDW_ActivityERLFlow{
    // returns map of string(ERL,GO) and Activities
    public Static Map<String,List<DRDW_Capability__c>> getActivities(List<DRDW_Capability__c> oActivities){
        Id recordtype = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Request Activity').getRecordTypeId();
        Id erlid = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('ERL').getRecordTypeId();
        Id goid = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId();
        List<DRDW_Capability__c> erlList = new List<DRDW_Capability__c>();
        List<DRDW_Capability__c> goList = new List<DRDW_Capability__c>();
        Set<Id> reqSet = new Set<Id>();
        for(DRDW_Capability__c c:oActivities){
            if(c.RecordTypeId == recordtype && c.Type__c == 'ERL'){
                erlList.add(c); 
            }
            else if(c.RecordTypeId == recordtype && c.Type__c == 'GO'){
                goList.add(c);
            }
        }
        Map<String,List<DRDW_Capability__c>> mapOfActivities = new Map<String,List<DRDW_Capability__c>>();
        mapOfActivities.put('ERL',erlList);
        mapOfActivities.put('GO',goList);
        return mapOfActivities;
    }

    // Create ERL events for Activities
    public Static List<DRDW_Event__c> createERLEvent(List<DRDW_Capability__c> oActivities){
        List<DRDW_Event__c> lEvents = new List<DRDW_Event__c>();
        for(DRDW_Capability__c c:oActivities){
            DRDW_Event__c e = new DRDW_Event__c();
            e.DRDW_Activity__c = c.id;
            e.type__c = 'ERL';
            lEvents.add(e);
        }
        try{
            insert lEvents;
            return lEvents;
        }
        catch(Exception e){
            return null;
        }
    }

    //Create ERL EventDays
    public static void createERLEventDays(List<DRDW_Capability__c> oActivities,List<DRDW_Event__c> lEvents){
        Map<Id,DRDW_Capability__c> mapOfActivities = new Map<Id,DRDW_Capability__c>();
        DRDW_Event_Days__c eDays;
        List<DRDW_Event_Days__c> lEventdays = new List<DRDW_Event_Days__c>();
        DRDW_Capability__c cap;
        for(DRDW_Capability__c c:oActivities){          
            mapOfActivities.put(c.id,c);
        }
        for(DRDW_Event__c e:lEvents){
            if(mapOfActivities.get(e.DRDW_Activity__c)!=null){
                cap = mapOfActivities.get(e.DRDW_Activity__c);
                Date enddate = cap.Planned_End_Date__c;   
                for(Date startdate = cap.Planned_Start_Date__c;startdate<=enddate;startdate=startdate.addDays(1)){
                    eDays = new DRDW_Event_Days__c();
                    eDays.Date__c = startdate;
                    eDays.DRDW_Event__c = e.id;
                    eDays.Type__c = 'ERL';
                    lEventdays.add(eDays);
                }               
            }
        }
        try{
            insert lEventdays;          
        }
        catch(Exception e){
        }
    }   

    // Create ERL events for Activities
    public Static void deleteERLEvent(List<DRDW_Capability__c> oActivities){
        List<DRDW_Event__c> lEvents = [select id from DRDW_Event__c where DRDW_Activity__c in :oActivities];
        if(lEvents!=null){
            try{
                delete lEvents;
            }catch(Exception e){
                System.debug('Error'+e);
            }
        }
    }
}