src/objects/DRDW_Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Posting_Date__c</fullName>
        <label>Posting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <formula>CASE(Month( Posting_Date__c ),1,&quot;1&quot;,2,&quot;1&quot;,3,&quot;1&quot;,4,&quot;2&quot;,5,&quot;2&quot;,6,&quot;2&quot;,7,&quot;3&quot;,8,&quot;3&quot;,9,&quot;3&quot;,10,&quot;4&quot;,11,&quot;4&quot;,12,&quot;4&quot;,&quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Line Items</relationshipLabel>
        <relationshipName>DRDW_Budget_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Master__c.object
<CustomObject>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Idea_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Assessment_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Generation_Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Budget Master</label>
    <nameField>
        <displayFormat>BGT-{0000}</displayFormat>
        <label>DRDW Budget Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Summary__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Budget_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DRDW Budget Master</description>
        <label>DRDW Budget Master</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Summaries</relationshipLabel>
        <relationshipName>DRDW_Budget_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Q_Actual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q Actual (w/o Accrual)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Total_Actuals__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q Total Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Budget Summary</label>
    <nameField>
        <displayFormat>Summary-{0000}</displayFormat>
        <label>DRDW Budget Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Summary_Detail__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Budget_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Budget Summary</label>
        <referenceTo>DRDW_Budget_Summary__c</referenceTo>
        <relationshipLabel>DRDW Budget Summary Details</relationshipLabel>
        <relationshipName>DRDW_Budget_Summary_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>M_Actual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>M Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sept</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Budget Summary Detail</label>
    <nameField>
        <displayFormat>BSD-{0000}</displayFormat>
        <label>DRDW Budget Summary Detail  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Summary Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_CreateBudgetSummaryDetailController.cls
public with sharing class DRDW_CreateBudgetSummaryDetailController {

	public DRDW_Budget_Summary_Detail__c oBudgetSummaryDetail{get;set;}    
	public id currentRecordID{get;set;}
	public id budgetSummaryID{get;set;}    
	public string recType{get;set;}
	Public Boolean isAdmin{get;set;}
	public List<SelectOption> lImpactedPicklist{get;set;}
	Public List<SelectOption> lDetailPicklist{get;set;}
	Public Boolean isFinancial{get;set;}
	Public string ParentName {get; set;}
	Public Id BMid {get;set;}
	public Id PrjId {get; set;}
	public boolean isGen {get; set;}
	public boolean isEval {get; set;}
	public boolean isAssess {get; set;}

	public DRDW_CreateBudgetSummaryDetailController(ApexPages.StandardController controller) {

		oBudgetSummaryDetail = (DRDW_Budget_Summary_Detail__c)controller.getRecord();
		currentRecordID = ApexPages.currentPage().getParameters().get('id');
		budgetSummaryID = ApexPages.currentPage().getParameters().get('budgetSummaryID');
		isAdmin = getUserPermission(UserInfo.getUserId()); 
		isFinancial = getFinUserPermission(UserInfo.getUserId());
		//  oBudgetSummaryDetail.Year__c = String.valueOf(system.today().year());
		if(currentRecordID != null){
			String SobjectApiName = 'DRDW_Budget_Summary_Detail__c';
			Map < String, Schema.SObjectType > schemaMap = Schema.getGlobalDescribe();
			Map < String, Schema.SObjectField > fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
			String commaSeparatedFields = '';
			for (String fieldName : fieldMap.keyset()) {
				if (commaSeparatedFields == null || commaSeparatedFields == '') {
					commaSeparatedFields = fieldName;
				} else {
					commaSeparatedFields = commaSeparatedFields + ', ' + fieldName;
				}
			}
			string query = 'select ' + commaSeparatedFields + ',DRDW_Budget_Summary__r.DRDW_Budget_Master__c,DRDW_Budget_Summary__r.DRDW_Budget_Master__r.Title__c,DRDW_Budget_Summary__r.DRDW_Budget_Master__r.Related_To__r.RecordType.Name,DRDW_Budget_Summary__r.DRDW_Budget_Master__r.Related_To__c' +' from ' + SobjectApiName + ' where id =\'' + currentRecordID + '\' limit 1';
			oBudgetSummaryDetail = Database.query(query);
			if(oBudgetSummaryDetail.DRDW_Budget_Summary__r.DRDW_Budget_Master__r.Related_To__r.RecordType.Name == 'Idea Project'){
				isEval = true;
			}
			else if(oBudgetSummaryDetail.DRDW_Budget_Summary__r.DRDW_Budget_Master__r.Related_To__r.RecordType.Name  == 'Generation Project'){
				isGen = true;
			}
			else if(oBudgetSummaryDetail.DRDW_Budget_Summary__r.DRDW_Budget_Master__r.Related_To__r.RecordType.Name  == 'Assessment Project'){
				isAssess = true;
			}
			System.debug('Fetch record types'+isGen+isAssess+isEval);
			budgetSummaryID = oBudgetSummaryDetail.DRDW_Budget_Summary__c;
		}
		else {
			oBudgetSummaryDetail.DRDW_Budget_Summary__c = budgetSummaryID; 
			DRDW_Budget_Summary__c parentRec = [select id, DRDW_Budget_Master__c,DRDW_Budget_Master__r.Title__c,DRDW_Budget_Master__r.Related_To__r.RecordType.Name,DRDW_Budget_Master__r.Related_To__c from DRDW_Budget_Summary__c where Id=: budgetSummaryID limit 1];
			if(parentRec.DRDW_Budget_Master__r.Related_To__r.RecordType.Name == 'Idea Project'){
				isEval = true;
			}
			else if(parentRec.DRDW_Budget_Master__r.Related_To__r.RecordType.Name  == 'Generation Project'){
				isGen = true;
			}
			else if(parentRec.DRDW_Budget_Master__r.Related_To__r.RecordType.Name  == 'Assessment Project'){
				isAssess = true;
			}
			System.debug('Fetch record types'+isGen+isAssess+isEval);
			PrjId = parentRec.DRDW_Budget_Master__r.Related_To__c;
			ParentName = parentRec.DRDW_Budget_Master__r.Title__c;
			BMid = parentRec.DRDW_Budget_Master__c;
		}
	}

	/*
    * @Method Name                    :  saveExperiment
    * @Description                    :  Method to save Existing Experiment
    * @Return Type                    :  void
    * @Parameters                     :  None
    */
	public PageReference saveBudgetSummary(){
		pagereference pageref;
		try{
			/*if(oRisk.Name == ''){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please enter a value for the mandatory fields'));    
            }*/
			oBudgetSummaryDetail.DRDW_Budget_Summary__c = budgetSummaryID;
			upsert oBudgetSummaryDetail;                
			pageref = new pagereference('/apex/DRDW_CreateBudgetSummaryinfo?id=' + budgetSummaryID +'&isEdit=false&section=#Budget_summary_detail_child');
			pageref.setredirect(true); 
			return pageref;
		}
		catch(Exception e){
			if(e.getmessage().contains('DUPLICATE_VALUE')){
				addError('The Summary detail record for this quarter already exists. Please check and try again');
				return null;
			}
			else {
				addError(e.getmessage());
				return null;
			}
		}
	}

	/*
    * @Method Name                    :  EditRecord
    * @Description                    :  Method for editing and existing record
    * @Return Type                    :  PageReference
    * @Parameters                     :  None
    */
	public PageReference EditRecord() {
		pagereference pageref;
		pageref = new pagereference('/apex/DRDW_CreateBudgetSummaryDetail?id=' + currentRecordID + '&isEdit=true');
		pageref.setredirect(true);        
		return pageref; 
	} 

	public void addError(string s) {
		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, s);
		ApexPages.addMessage(myMsg);
	}

	/*
    * @Method Name                    :  Cancel Record
    * @Description                    :  Method for editing and existing record
    * @Return Type                    :  PageReference
    * @Parameters                     :  None
    */
	public PageReference CancelRecord() {
		pagereference pageref;
		pageref = new pagereference('/apex/DRDW_CreateBudgetSummaryinfo?id=' + budgetSummaryID + '&isEdit=false');
		pageref.setredirect(true);
		return pageref; 
	} 

	Public PageReference DeleteRecord(){
		Map<String,Integer> months = new Map<String,Integer>();   
		months.put('Jan',1);
		months.put('Feb',2);
		months.put('March',3);
		months.put('April',4);
		months.put('May',5);
		months.put('June',6);
		months.put('July',7);
		months.put('Aug',8);
		months.put('Sept',9);
		months.put('Oct',10);
		months.put('Nov',11);
		months.put('Dec',12);
		DRDW_Budget_Summary_Detail__c detail = [select id,DRDW_Budget_Summary__r.DRDW_Budget_Master__c,DRDW_Budget_Summary__c,M_Actual__c from DRDW_Budget_Summary_Detail__c where id =:oBudgetSummaryDetail.id];    

		Id masterid = detail.DRDW_Budget_Summary__r.DRDW_Budget_Master__c;

		List<DRDW_Budget_Line_Item__c> bLineitems = [select id from DRDW_Budget_Line_Item__c where Related_To__c =:masterid and Quarter__c =:oBudgetSummaryDetail.Quarter__c and CALENDAR_MONTH(Posting_Date__c) =: months.get(oBudgetSummaryDetail.Month__c) ];

		system.debug('bline-----'+bLineitems);

		DRDW_Budget_Summary__c oSummary = [Select id,Q_Total_Actuals__c,Q_Actual__c from DRDW_Budget_Summary__c where id=:detail.DRDW_Budget_Summary__c limit 1];

		oSummary.Q_Total_Actuals__c= oSummary.Q_Total_Actuals__c- detail.M_Actual__c;   

		delete oBudgetSummaryDetail;
		delete bLineitems;
		update oSummary;
		pagereference pageref;
		pageref = new pagereference('/apex/DRDW_CreateBudgetSummaryinfo?id=' + budgetSummaryID);
		pageref.setredirect(true);
		return pageref;
	}

	Public Boolean getUserPermission(Id UserID){
		List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserID AND PermissionSet.Name = 'DRDW_Business_Admin']);
		Set<Id> lUserId = new Set<Id>();
		If(!lPermission.isEmpty()){
			For(PermissionSetAssignment p : lPermission){
				lUserId.add(p.Assignee.Id);
			}
		}
		If(lUserId.Contains(UserID)){
			return true;
		}

		return false;
	} 

	Public Boolean getFinUserPermission(Id UserID){
		List<PermissionSetAssignment> lPermission = new List<PermissionSetAssignment>([select Assignee.Id,PermissionSet.Name from PermissionSetAssignment where Assignee.Id=:UserID AND PermissionSet.Name ='DRDW_Financial_User']);
		Set<Id> lUserId = new Set<Id>();
		If(!lPermission.isEmpty()){
			For(PermissionSetAssignment p : lPermission){
				lUserId.add(p.Assignee.Id);
			}
		}
		If(lUserId.Contains(UserID)){
			return true;
		}

		return false;
	}   


}