src/objects/DRDW_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Display__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>DRDW Configuration</label>
    <nameField>
        <label>DRDP Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRDW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DRDW_HomePage.cls
@isTest
private class Test_DRDW_HomePage {
    static testMethod void testPositive() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
            DRDW_Configuration__c oConfig;
            List<Document> lDocs = DRDW_TestDataFactory.createDocument(new List<String>{'DRDW Home Banner Image','DRDW Home Card1 image','DRDW Home Card2 image','DRDW Home Card3 image','DRDW Home Header Client logo','DRDW Home Header logo'});
            insert lDocs;
            List<String> lTabName = new List<String>{'Home Banner Title','Home Banner Discription','Home Card1 Text','Home Card2 Text','Home Card3 Text','Research','Admin'};
            List<DRDW_Configuration__c> lConfigs = new List<DRDW_Configuration__c>();
            for(integer i=0;i<lTabName.size();i++){
                oConfig = new DRDW_Configuration__c();
                oConfig.Display__c = true;
                oConfig.Name = lTabName[i];
                oConfig.Value__c = lTabName[i];
                oConfig.URL__c = '/apex/'+lTabName[i].split('&nbsp;')[0];  
                lConfigs.add(oConfig);          
            }
            insert lConfigs;

            test.startTest();
            PageReference pageRef = new pageReference('/apex/DRDW_HomePage?sfdcIFrameHost=true');    
            pageRef.getHeaders().put('USER-AGENT', 'Chrome');     
            Test.setCurrentPage(pageRef);
            DRDW_HomePage controller = new DRDW_HomePage();
            controller.SaveFeedback();
            DRDW_HomePage.isSF1();
            controller.searchWord='test';
            controller.populateGlobalURL();
            System.assertNotEquals(null,busAdm.Id,'error');
            test.stoptest();

        }
    }
}