src/objects/DRDW_Proj_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Capability</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipName>Proj_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Proj_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Capability Activity</label>
        <referenceTo>DRDW_Proj_Activity__c</referenceTo>
        <relationshipName>Proj_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>On-going</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Assigned</fullName>
                    <isActive>false</isActive>
                    <label>Not Assigned</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                    <isActive>false</isActive>
                    <label>Started</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability Activity</label>
    <nameField>
        <label>Capability Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capability Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DRDW_Proj_Activity__c.object
    <fields>
        <fullName>Percent_Complete__c</fullName>
        <label>% Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DRDW_Project__c.object
    <fields>
        <fullName>DRDW_Progress_Complete__c</fullName>
        <label>% Progress Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>

src/objects/Related_Capability_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Capability_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capability Activity</label>
        <referenceTo>DRDW_Proj_Activity__c</referenceTo>
        <relationshipName>Related_Capability_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dependency_Type__c</fullName>
        <description>Finish to start (FS)  -&gt; A FS B means &quot;activity A must finish before activity B can begin&quot;
Finish to finish (FF) -&gt; A FF B means &quot;activity A must finish before activity B can finish&quot;
Start to start (SS)    -&gt; A SS B means &quot;activity A must start before activity B can start&quot;
Start to finish (SF)   -&gt; A SF B means &quot;activity A must start before activity B finishes&quot;</description>
        <inlineHelpText>FS  -&gt; activity A must finish before activity B can begin
FF -&gt; activity A must finish before activity B can finish
SS -&gt; activity A must start before activity B can start
SF -&gt; activity A must start before activity B finishes</inlineHelpText>
        <label>Dependency Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Finish to start (FS)</fullName>
                </value>
                <value>
                    <fullName>Finish to finish (FF)</fullName>
                </value>
                <value>
                    <fullName>Start to start (SS)</fullName>
                </value>
                <value>
                    <fullName>Start to finish (SF)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependent_Capability_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Capability Activity</label>
        <referenceTo>DRDW_Proj_Activity__c</referenceTo>
        <relationshipName>Related_Capability_Activities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Dependency</label>
    <nameField>
        <displayFormat>CA-{000000000}</displayFormat>
        <label>Related Capability Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DependencyValidator_TriggerHandler.cls
Public class DependencyValidator_TriggerHandler{

    public Static void vaidateDependency(List<DRDW_Proj_Activity__c> newList, Map<Id,DRDW_Proj_Activity__c> newMap){
        List<Related_Capability_Activity__c> dependencies = new List<Related_Capability_Activity__c>();
    
    dependencies = [SELECT Id,Dependency_Type__c, 
                    Capability_Activity__c,
                    Capability_Activity__r.Name,
                    Capability_Activity__r.Status__c,
                    Dependent_Capability_Activity__r.Status__c,
                    Dependent_Capability_Activity__r.Name
                    FROM Related_Capability_Activity__c 
                    WHERE Dependent_Capability_Activity__c in :newList];
    
    Map<ID,String> errorMap = new Map<ID,String>();                                                 
    for(Related_Capability_Activity__c oRelated:dependencies){
        
        if(oRelated.Dependency_Type__c=='Finish to start (FS)'){
            if(oRelated.Capability_Activity__r.Status__c!='Completed' && (newMap.get(oRelated.Dependent_Capability_Activity__c).Status__c =='On-going' || newMap.get(oRelated.Dependent_Capability_Activity__c).Status__c =='Completed') ){
                if(!errorMap.containsKey(oRelated.Dependent_Capability_Activity__c)){
                    errorMap.put(oRelated.Dependent_Capability_Activity__c,'');
                }
                String er = errorMap.get(oRelated.Dependent_Capability_Activity__c);
                er = er + 'Cannot change status because of dependency type ( Finish to start (FS)) for dependent Activity '+oRelated.Capability_Activity__r.Name+' has not been completed yet \n';
                errorMap.put(oRelated.Dependent_Capability_Activity__c, er);
            }
        }else if(oRelated.Dependency_Type__c=='Finish to finish (FF)'){
            
            if(oRelated.Capability_Activity__r.Status__c!='Completed' && (newMap.get(oRelated.Dependent_Capability_Activity__c).Status__c =='Completed') ){
                if(!errorMap.containsKey(oRelated.Dependent_Capability_Activity__c)){
                    errorMap.put(oRelated.Dependent_Capability_Activity__c,'');
                }
                String er = errorMap.get(oRelated.Dependent_Capability_Activity__c);
                er = er + 'Cannot change status because of dependency type ( Finish to finish (FF)) for dependent Activity '+oRelated.Capability_Activity__r.Name+' has not been completed yet \n';
                errorMap.put(oRelated.Dependent_Capability_Activity__c, er);
            }
            
        }else if(oRelated.Dependency_Type__c=='Start to start (SS)'){
            
            if((oRelated.Capability_Activity__r.Status__c!='On-going' && oRelated.Capability_Activity__r.Status__c!='Completed') && (newMap.get(oRelated.Dependent_Capability_Activity__c).Status__c =='On-going' || newMap.get(oRelated.Dependent_Capability_Activity__c).Status__c =='Completed')){
                if(!errorMap.containsKey(oRelated.Dependent_Capability_Activity__c)){
                    errorMap.put(oRelated.Dependent_Capability_Activity__c,'');
                }
                String er = errorMap.get(oRelated.Dependent_Capability_Activity__c);
                er = er + 'Cannot change status because of dependency type ( Start to start (SS)) for dependent Activity '+oRelated.Capability_Activity__r.Name+' has not been Started yet \n';
                errorMap.put(oRelated.Dependent_Capability_Activity__c, er);
            }
            
        }else if(oRelated.Dependency_Type__c=='Start to finish (SF)'){
            
            if((oRelated.Capability_Activity__r.Status__c!='On-going' && oRelated.Capability_Activity__r.Status__c!='Completed') && (newMap.get(oRelated.Dependent_Capability_Activity__c).Status__c =='Completed')){
                if(!errorMap.containsKey(oRelated.Dependent_Capability_Activity__c)){
                    errorMap.put(oRelated.Dependent_Capability_Activity__c,'');
                }
                String er = errorMap.get(oRelated.Dependent_Capability_Activity__c);
                er = er + 'Cannot change status because of dependency type ( Start to finish (SF)) for dependent Activity '+oRelated.Capability_Activity__r.Name+' has not been Started yet \n';
                errorMap.put(oRelated.Dependent_Capability_Activity__c, er);
            }
            
        }
        
    }   
    
    for(DRDW_Proj_Activity__c act:newList){
        
        if(errorMap.containsKey(act.Id)){
            newMap.get(act.Id).addError(errorMap.get(act.Id));
        }
        
    }
    }
    
    public static void updateAveragePercentage(List<DRDW_Proj_Activity__c> newList , Map<Id,DRDW_Proj_Activity__c> newMap , Map<Id,DRDW_Proj_Activity__c> oldMap){
        set<Id> sParentActivityId = new set<Id>();
        List<DRDW_Project__c> lProjToBeUpdated = new List<DRDW_Project__c>();
        if(Trigger.isUpdate){
            for(DRDW_Proj_Activity__c oPA : newList){
                if(oldMap.get(oPA.Id).Percent_Complete__c != oPA.Percent_Complete__c)
                sParentActivityId.add(oPA.Parent_Project__c);
            }
        }
        
        if(Trigger.isInsert || Trigger.isDelete){
            for(DRDW_Proj_Activity__c oPA : newList){
                sParentActivityId.add(oPA.Parent_Project__c);
            }
        }
        
        if(!sParentActivityId.isEmpty()){
            for(DRDW_Project__c oProject : [select id,DRDW_Progress_Complete__c,(select id,Percent_Complete__c from Proj_Activities__r) from DRDW_Project__c where id IN: sParentActivityId]){
                Decimal percent = 0;
                for(DRDW_Proj_Activity__c oPA : oProject.Proj_Activities__r){
                    if(oPA.Percent_Complete__c != null)
                        percent += oPA.Percent_Complete__c;
                    else
                       percent += 0; 
                }
                if(oProject.Proj_Activities__r.size()>0){
                    percent = percent/oProject.Proj_Activities__r.size();
                    oProject.DRDW_Progress_Complete__c = percent;
                    sParentActivityId.remove(oProject.Id);
                    lProjToBeUpdated.add(oProject);
                }
            }
        }
        if(!sParentActivityId.isEmpty()){
            for(Id oProjId : sParentActivityId){
                DRDW_Project__c newProject = new DRDW_Project__c(Id = oProjId , DRDW_Progress_Complete__c = 0);
                lProjToBeUpdated.add(newProject);
            }
        }
        if(lProjToBeUpdated.size()>0){
            update lProjToBeUpdated;
        }
    }
}