src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Samples_to_collect_new__c</fullName>
        <label>Study Schedule Activities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GO_Preferred_Start_Date__c</fullName>
        <label>GO Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lab_Testing_Required__c</fullName>
        <label>Lab Testing Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Unassigned&quot;</defaultValue>
        <description>Stores status of request.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Partially Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <label>Study Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <description>Actual End Date</description>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Cost_Center__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Details__c</fullName>
        <label>Additional Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Cost Center</label>
    <nameField>
        <label>Cost Center</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRDW Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>Enter the date that effort begins on the research study/ research project.</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_DRDW_ViewGOActivityController.cls
@istest
private class Test_DRDW_ViewGOActivityController{
    static testMethod void testPositive() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        DRDW_TestDataFactory.assignGroup(busAdm.id,'DRDW_FG_Bacteriology');
        DRDW_TestDataFactory.assignGroup(busAdm.id,'DRDW_BU_Business_Development');
        System.runAs(busAdm) {   
            List<DRDW_Project__c> lAssessments = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');
            insert lAssessments;

            System.assert(lAssessments.size()==2);

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(GO_Preferred_Start_Date__c=System.today()+2,Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',samples_to_collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lAssessments[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+5,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId());
            insert ocapReq;
            
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Request Activity',lAssessments[0].id);
            lCapab[0].DRDW_Request__c=ocapReq.Id;
            insert lCapab;
            test.startTest();
            PageReference pagRef = new PageReference('/apex/DRDW_ViewGOActivity?id='+lCapab[0].Id+'&projId='+lAssessments[0].Id+'&reqId='+ocapReq.Id);
            Test.setCurrentPage(pagRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(lCapab[0]);
            DRDW_ViewGOActivityController controller = new DRDW_ViewGOActivityController(sc);
            controller.addError('Test');
            controller.genericID =lCapab[0].Id;
            controller.isbError = false;
            controller.isAdmin = false;
            controller.isFin = false;
            controller.isIdea = false;
            controller.isGeneration = false;
            System.assertNotEquals(null, ocapReq.Id, 'error');
            test.stopTest();
            
        }
    }

    static testMethod void testNegative() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        DRDW_TestDataFactory.assignGroup(busAdm.id,'DRDW_FG_Bacteriology');
        DRDW_TestDataFactory.assignGroup(busAdm.id,'DRDW_BU_Business_Development');
        System.runAs(busAdm) {   
            List<DRDW_Project__c> lAssessments = DRDW_TestDataFactory.returnProjects(2,'Assessment Project');
            insert lAssessments;

            System.assert(lAssessments.size()==2);

            DRDW_Cost_Center__c oCostCen = new DRDW_Cost_Center__c(Additional_Details__c='test',Functional_Area__c='test',Name='test',Status__c='Active');
            insert oCostCen; 

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Study_Title__c='test',GO_Preferred_Start_Date__c=System.today()+2,Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',samples_to_collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lAssessments[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+5,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId());
            insert ocapReq;
            
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(1, 'Request Activity',lAssessments[0].id);
            lCapab[0].DRDW_Request__c=ocapReq.Id;
            insert lCapab;
            test.startTest();
            PageReference pagRef = new PageReference('/apex/DRDW_ViewGOActivity?&projId='+lAssessments[0].Id+'&reqId='+ocapReq.Id);
            Test.setCurrentPage(pagRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(lCapab[0]);
            DRDW_ViewGOActivityController controller = new DRDW_ViewGOActivityController(sc);
            controller.addError('Test');
            System.assertNotEquals(null, ocapReq.Id, 'error');
            test.stopTest();
        }
    }
}