src/objects/DRDW_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Analytical &amp; Assay Development</fullName>
                </value>
                <value>
                    <fullName>Bacteriology</fullName>
                </value>
                <value>
                    <fullName>BioProducts</fullName>
                </value>
                <value>
                    <fullName>Chemistry</fullName>
                </value>
                <value>
                    <fullName>DDS</fullName>
                </value>
                <value>
                    <fullName>Informatics</fullName>
                </value>
                <value>
                    <fullName>Parasitology</fullName>
                </value>
                <value>
                    <fullName>Target Enablement</fullName>
                </value>
                <value>
                    <fullName>Virology</fullName>
                </value>
                <value>
                    <fullName>FD Laboratory</fullName>
                </value>
                <value>
                    <fullName>Animal Care</fullName>
                </value>
                <value>
                    <fullName>Study Execution</fullName>
                </value>
                <value>
                    <fullName>FD Study Management</fullName>
                </value>
                <value>
                    <fullName>FD Veterinary Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hours_Available_Per_Day__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hours Available Per Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_per_Week__c</fullName>
        <label>Hours per Week</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Animal Caretaker</fullName>
                </value>
                <value>
                    <fullName>Clinical Associate</fullName>
                </value>
                <value>
                    <fullName>ERL Scientist</fullName>
                </value>
                <value>
                    <fullName>Functional Head</fullName>
                </value>
                <value>
                    <fullName>Laboratory Scientist</fullName>
                </value>
                <value>
                    <fullName>Study Manager</fullName>
                </value>
                <value>
                    <fullName>Study Monitor</fullName>
                </value>
                <value>
                    <fullName>Veterinarian</fullName>
                </value>
                <value>
                    <fullName>Vet Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DRDW_ResourceList.cls
@isTest
private class Test_DRDW_ResourceList {
    static testmethod void testPostive(){
        User busAdm = DRDW_TestDataFactory.getTestingUser();
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');    
        User finUsr = DRDW_TestDataFactory.getTestingUser();
        DRDW_TestDataFactory.givePermissions(finUsr.id,'DRDW_Financial_User');    
        System.runAs(finUsr) {
            DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active');
            DRDW_Resource__c oResource1 = new DRDW_Resource__c(Name__c=finUsr.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active');
            insert new List<sObject>{oResource1,oResource};
            test.startTest();
            DRDW_ResourceList controller = new DRDW_ResourceList();             
            System.assert(controller.getlResourceRecordWrap().size()>0);
            controller.FetchDataForCriteria();
            controller.pagenumbers(2.00);
            controller.dResourcePageCount=2.00;
            controller.NextResourcePageSeries();
            controller.PreviousResourcePageSeries();
            controller.iPageNumber=1;
            controller.GoToResourcePageNumber();
            controller.sort();
            controller.sSearchWord='lastname';
            controller.query(string.escapeSingleQuotes('Name') + ' ' + string.escapeSingleQuotes('ASC NULLS FIRST'));
            System.assertNotEquals(null,finUsr.Id,'error'); 
            test.stoptest();
        }            
    }   
}