src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Samples_to_collect_new__c</fullName>
        <label>Study Schedule Activities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinalDateTobeConsidered__c</fullName>
        <label>FinalDateTobeConsidered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GO_Preferred_Start_Date__c</fullName>
        <label>GO Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lab_Testing_Required__c</fullName>
        <label>Lab Testing Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned DTG date on the Project if an Evaluation Project, the Planned DTA date on the Project if a Generation Project, the Planned DP1 date on the Project if an Assessment Project.It is editable</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <description>DTE date on the Project if an Evaluation Project, the DTG date on the Project if a Generation Project, the DTA date on the Project if an Assessment Project. It is editable</description>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Study_Start_Date__c</fullName>
        <inlineHelpText>Study Day 0 Equals Frist Dosing</inlineHelpText>
        <label>Planned Study Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preferred_Start_Date_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preferred Start Date Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a backend field, currently used for adding as the recipient for Go type of records</description>
        <label>Project PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_RPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a backend field, currently used for adding as the recipient for Go type of records</description>
        <label>Project RPL</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Unassigned&quot;</defaultValue>
        <description>Stores status of request.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Partially Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <label>Study Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <description>Actual End Date</description>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Capability_Area__c</fullName>
        <label>Activity Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capability__c</fullName>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <description>Planned End Date</description>
        <label>Planned End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <inlineHelpText>Decision to Evaluate (DTE):</inlineHelpText>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipName>Capabilities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Research_Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Research Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Capabilities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Category__c</fullName>
        <label>Event Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sample</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <formula>IF(DRDW_Activity__r.Related_Project__r.Idea_Name__c!=NULL,DRDW_Activity__r.Related_Project__r.Idea_Name__c,DRDW_Activity__r.Related_Project__r.Project_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <label>Study Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Capturing Title for GO Request</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>Enter the date that effort begins on the research study/ research project.</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DRDW_RequestTriggerHandler.cls
/****************************************************************************************************************************************** 
 * Class Name   : DRDW_RequestTriggerHandler 
 * Description  : Class to perform operations on Request
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
public class DRDW_RequestTriggerHandler {
    
    /*Public List<DRDW_Event__c> leventInsertFinal;
    Public List<DRDW_Event__c> leventDeleteFinal; 
    Public Map<Id,Id> mReqActivityId;*/

// Update user lookup values on Request once created
    Public void UserLookups(List<DRDW_Cap_Request__c> NewCapReqList){

      Set<ID> PrjIds = new Set<ID>();
    
      for(DRDW_Cap_Request__c oCapreq : NewCapReqList){
      PrjIds.add(oCapreq.Project__c);          
      }

      List<DRDW_Project__c> lstprjs = [Select Id, Name, RP_Project_Manager__c,Research_Project_Lead__c from DRDW_Project__c Where Id =: PrjIds];

      for(DRDW_Cap_Request__c oCapreq : NewCapReqList){
        for(DRDW_Project__c oPrj : lstprjs){
            if(oCapreq.Project__c == oPrj.Id){

              if(oPrj.RP_Project_Manager__c != null){
                      System.debug('Inside PM'+oPrj.RP_Project_Manager__c);
                        oCapreq.Project_PM__c = oPrj.RP_Project_Manager__c;

              }
              if(oPrj.Research_Project_Lead__c != null){
                      System.debug('Inside RPL'+oPrj.Research_Project_Lead__c);
                        oCapreq.Project_RPL__c = oPrj.Research_Project_Lead__c;

              }

            }
        }
      }
        
    }

     Public void UpdateReqActivity(List<DRDW_Cap_Request__c> NewCapReqList){
         id recordTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId();
         Map<id,List<DRDW_Cap_Request__c>> mReqActivity = new Map<id,List<DRDW_Cap_Request__c>>();
         List<DRDW_Capability__c> lcap = new list<DRDW_Capability__c>([select Title__c,Related_Project__c,DRDW_Request__c,Capability__c,Capability_Area__c,Actual_End_Date__c,Actual_Start_Date__c,Planned_End_Date__c,Planned_Start_Date__c from DRDW_Capability__c where DRDW_Request__c IN:NewCapReqList]);
         
         For(DRDW_Cap_Request__c req : NewCapReqList){
            if(mReqActivity.ContainsKey(req.Id)){
                mReqActivity.get(req.Id).add(req);
            }else{
                mReqActivity.put(req.Id,new List<DRDW_Cap_Request__c>{req});
            }
         }
         
         for(DRDW_Capability__c c : lcap){
             
         }
     }
     
     Public void OnBeforeDelete(List<DRDW_Cap_Request__c> NewCapReqList,Map<id,DRDW_Cap_Request__c> oldMap){
         List<DRDW_Capability__c> lActivity = new List<DRDW_Capability__c>([Select id from DRDW_Capability__c where DRDW_Request__c IN:NewCapReqList]);
         if(!lActivity.isEmpty()){
             delete lActivity;
         }
     }

     Public void UpdateFinalDatetobeConsidered(List<DRDW_Cap_Request__c> NewCapReqList){
     System.debug('Inside insert triggerhandler');

         for(DRDW_Cap_Request__c oCapreq : NewCapReqList){

            if(oCapreq.Preferred_Start_Date_Locked__c == true && oCapreq.GO_Preferred_Start_Date__c != null){
                System.debug('Inside Locked'+oCapreq.Preferred_Start_Date_Locked__c+oCapreq.GO_Preferred_Start_Date__c);
                oCapreq.FinalDateTobeConsidered__c = oCapreq.GO_Preferred_Start_Date__c;
            }else if(oCapreq.Preferred_Start_Date_Locked__c == false && oCapreq.Planned_Study_Start_Date__c != null){
                System.debug('Inside Locked'+oCapreq.Preferred_Start_Date_Locked__c+oCapreq.Planned_Study_Start_Date__c);
                oCapreq.FinalDateTobeConsidered__c = oCapreq.Planned_Study_Start_Date__c;
            }
         }

     }
     
    Public void OnAfterUpdate(Map<Id,DRDW_Cap_Request__c> newMap,Map<Id,DRDW_Cap_Request__c> oldMap){

        /*Id recordTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId();
        leventInsertFinal = new List<DRDW_Event__c>();
        leventDeleteFinal = new List<DRDW_Event__c>();
        mReqActivityId = new Map<Id,Id>();
        List<DRDW_Capability__c> lActivity = new List<DRDW_Capability__c>([Select id,DRDW_Request__c from DRDW_Capability__c where DRDW_Request__c IN:newMap.keyset() and RecordType.Name = 'Study Activity']);
         
        for(DRDW_Capability__c oactivity : lActivity){
            mReqActivityId.put(oactivity.DRDW_Request__c,oactivity.Id);
        }
                
        for(Id reqId : newMap.keyset()){
            DRDW_Cap_Request__c newReq = newMap.get(reqId);
            DRDW_Cap_Request__c oldReq = oldMap.get(reqId);
            if((recordTypeId == newReq.recordTypeId) && (newReq.Lab_Testing_Required__c != oldReq.Lab_Testing_Required__c || newReq.Samples_to_collect_new__c != oldReq.Samples_to_collect_new__c)){
                generateEvents(newReq,oldReq);
            }
        }
        
        if(leventInsertFinal.size() > 0 ){
            insert leventInsertFinal;
        }
        if(leventDeleteFinal.size() > 0 ){
            delete leventDeleteFinal;
        }*/
        
    }
    
    /* Public void generateEvents(DRDW_Cap_Request__c newReq,DRDW_Cap_Request__c oldReq) {
        
        List<DRDW_Event__c> leventInsert = new List<DRDW_Event__c>();
        List<DRDW_Event__c> leventDelete = new List<DRDW_Event__c>();
        Set<String> setLabTestingReqOld = new Set<String>();
        Set<String> setLabTestingReqNew = new Set<String>();
        Set<String> setSamplesToCollectNew = new Set<String>();
        Set<String> setSamplesToCollectOld = new Set<String>();
        Set<String> setEventReqDelete = new Set<String>();
        DRDW_Event__c oevent;
        if(newReq.Lab_Testing_Required__c != oldReq.Lab_Testing_Required__c && mReqActivityId.containskey(newReq.Id)){
            if(newReq.Lab_Testing_Required__c != null){
                setLabTestingReqNew.addAll(newReq.Lab_Testing_Required__c.split(';'));
            }
            if(oldReq.Lab_Testing_Required__c != null){
                setLabTestingReqOld.addAll(oldReq.Lab_Testing_Required__c.split(';'));
            }
            for(String labtestingReq : setLabTestingReqNew){
                if(!setLabTestingReqOld.contains(labtestingReq)){
                    oevent = new DRDW_Event__c();
                    oevent.Event_Category__c = 'Lab';
                    oevent.Type__c = 'GO';
                    oevent.Study_Title__c = newReq.Study_Title__c;
                    oevent.Status__c = 'Unassigned';
                    oevent.Event_Type__c = labtestingReq;
                    oevent.DRDW_Activity__c = mReqActivityId.get(newReq.Id);
                    leventInsert.add(oevent);
                }
            }
            for(String labtestingReq : setLabTestingReqOld){
                if(!setLabTestingReqNew.contains(labtestingReq)){
                    //delete event
                    setEventReqDelete.add(labtestingReq);
                }
            }
        }
        if(newReq.Samples_to_collect_new__c != oldReq.Samples_to_collect_new__c && mReqActivityId.containskey(newReq.Id)){
            if(newReq.Samples_to_collect_new__c != null && newReq.Samples_to_collect_new__c != '[]'){
                setSamplesToCollectNew.addAll(newReq.Samples_to_collect_new__c.replace('[','').replace(']','').split(','));
            }
            if(oldReq.Samples_to_collect_new__c != null && oldReq.Samples_to_collect_new__c != '[]'){
                setSamplesToCollectOld.addAll(oldReq.Samples_to_collect_new__c.replace('[','').replace(']','').split(','));
            }

            for(String samplestocollect : setSamplesToCollectNew){
                if(!setSamplesToCollectOld.contains(samplestocollect)){
                    oevent = new DRDW_Event__c();
                    oevent.Event_Category__c = 'Sample';
                    oevent.Type__c = 'GO';
                    oevent.Study_Title__c = newReq.Study_Title__c;
                    oevent.Status__c = 'Unassigned';
                    oevent.Event_Type__c = samplestocollect;
                    oevent.DRDW_Activity__c = mReqActivityId.get(newReq.Id);
                    leventInsert.add(oevent);
                }
            }
            
            for(String samplestocollect : setSamplesToCollectOld){
                if(!setSamplesToCollectNew.contains(samplestocollect)){
                    //delete event
                    setEventReqDelete.add(samplestocollect);
                }
            }

        }
        
        if(setEventReqDelete.size() > 0 ){
            
            leventDelete = [Select Id from DRDW_Event__c where Event_Type__c in : setEventReqDelete and DRDW_Activity__r.DRDW_Request__c =: newReq.Id and DRDW_Activity__r.DRDW_Request__r.RecordType.Name = 'GO' ];
            
        }
        
        if(leventInsert.size() > 0 ){
            leventInsertFinal.addAll(leventInsert);
        }
        if(leventDelete.size() > 0 ){
            leventDeleteFinal.addAll(leventDelete);
        }
        
     } */
     
      Public void changePreferedDate(Map<Id,DRDW_Cap_Request__c> newMap,Map<Id,DRDW_Cap_Request__c> oldMap){
        Id recordTypeId = Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId();
                
        List<DRDW_Capability__c> lCaps = new List<DRDW_Capability__c>();
        lCaps = [select id,DRDW_Request__c,Proposed_Start_Date__c from DRDW_Capability__c where DRDW_Request__c in:newMap.keySet() and RecordType.Name = 'Study Activity']; 
        List<DRDW_Capability__c> updatedActivity = new List<DRDW_Capability__c>();          
        for(DRDW_Capability__c oCap:lCaps){
                    if(oCap.Proposed_Start_Date__c !=newMap.get(oCap.DRDW_Request__c).GO_Preferred_Start_Date__c){
                        oCap.Proposed_Start_Date__c = newMap.get(oCap.DRDW_Request__c).GO_Preferred_Start_Date__c;
                        updatedActivity.add(oCap);
                    }
            }       
        if(updatedActivity.size()>0){
            update updatedActivity;
        }             
     }

}