src/objects/DRDW_Budget_Master__c.object
<CustomObject>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Budget Master</label>
    <nameField>
        <displayFormat>BGT-{0000}</displayFormat>
        <label>DRDW Budget Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Samples_to_collect_new__c</fullName>
        <label>Study Schedule Activities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lab_Testing_Required__c</fullName>
        <label>Lab Testing Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <description>DTE date on the Project if an Evaluation Project, the DTG date on the Project if a Generation Project, the DTA date on the Project if an Assessment Project. It is editable</description>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Unassigned&quot;</defaultValue>
        <description>Stores status of request.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Partially Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <label>Study Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>ERL</fullName>
        <active>true</active>
        <label>ERL</label>
    </recordTypes>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>Related_Project_bck__c</fullName>
        <label>Related Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <inlineHelpText>Decision to Evaluate (DTE):</inlineHelpText>
        <label>Planned Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipName>Capabilities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>UniqueProjActTitle__c</fullName>
        <label>UniqueProjActTitle</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
</fields>
	 <fields>
        <fullName>Project_Business_Unit__c</fullName>
        <label>Project Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
  <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <description>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</description>
        <inlineHelpText>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</inlineHelpText>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>Related_Project__c</fullName>
        <formula>IF(DRDW_Activity__r.Related_Project__r.Idea_Name__c!=NULL,DRDW_Activity__r.Related_Project__r.Idea_Name__c,DRDW_Activity__r.Related_Project__r.Project_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Partially Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <label>Study Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Capturing Title for GO Request</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Commercial Operations</fullName>
                </value>
                <value>
                    <fullName>CMC</fullName>
                </value>
                <value>
                    <fullName>Legal &amp; Compliance</fullName>
                </value>
                <value>
                    <fullName>Regulatory</fullName>
                </value>
                <value>
                    <fullName>Corporate Finance</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                    <label>Corporate</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <isActive>false</isActive>
                    <label>Finance</label>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                    <label>Manufacturing</label>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                    <isActive>false</isActive>
                    <label>R&amp;D</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_ActivityTriggerHandler.cls
public class DRDW_ActivityTriggerHandler {
    public Static void OnBeforeInsert(List<DRDW_Capability__c> newObjects){
        // EXECUTE BEFORE INSERT LOGIC
        Set<Id> projIds = new Set<Id>();
        Id recordtype = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Request Activity').getRecordTypeId();
        for(DRDW_Capability__c c: newObjects){
            if(c.Related_Project__c != NULL && c.Title__c !=NULL && c.RecordTypeID == recordtype){
                c.UniqueProjActTitle__c = c.Related_Project__c + c.Title__c;
                c.Proposed_Start_Date__c = c.Planned_Start_Date__c;
            }
            if(c.Related_Project__c!=null){
                projIds.add(c.Related_Project__c);
            }
        }        
        List<DRDW_Project__c> lProjects = new List<DRDW_Project__c>();
        lProjects = [select id,Business_Unit__c,Name__c from DRDW_Project__c where id in:projIds];        
        Map<Id,String> mapProjectBU = new Map<Id,String>();  
        Map<Id,String> mapProjectName = new Map<Id,String>();     
        for(DRDW_Project__c oProject:lProjects){
            if(oProject.Business_Unit__c!=null){
                mapProjectBU.put(oProject.id,oProject.Business_Unit__c);
            }
            mapProjectName.put(oProject.id,oProject.Name__c);
        }        
        for(DRDW_Capability__c oCap:newObjects){
            if(oCap.Related_Project__c!=null){
                if(mapProjectBU.get(oCap.Related_Project__c)!=null){
                    oCap.Project_Business_Unit__c = mapProjectBU.get(oCap.Related_Project__c);
                    if(mapProjectName.get(oCap.Related_Project__c)!=null){
                        oCap.Related_Project_bck__c = mapProjectName.get(oCap.Related_Project__c);
                    }
                }
            }
        }
    }
    
    public Static void OnAfterInsert(List<DRDW_Capability__c> newObjects){
        // EXECUTE AFTER INSERT LOGIC
        // Request for which event needs to be created.
        Set<Id> reqId = new Set<Id>();
        List<DRDW_Cap_Request__c> lCapReq = new List<DRDW_Cap_Request__c>();
        Map<Id,Id> mReqActivityId = new Map<Id,Id>(); 
        Id studyRecordtype = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Study Activity').getRecordTypeId(); 
        Map<String,List<DRDW_Capability__c>> mapOfActivities = DRDW_ActivityERLFlow.getActivities(newObjects);        
        if(mapOfActivities!=null){            
            List<DRDW_Capability__c> erlActivities = mapOfActivities.get('ERL');            
            if(erlActivities!=null){
                try{                
                    List<DRDW_Event__c> lEvents = DRDW_ActivityERLFlow.createERLEvent(erlActivities);                
                }catch(Exception e){                   
                    System.debug('Error'+e);                   
                }                
            }                       
        }
        /*for(DRDW_Capability__c cap : newObjects){
            if(cap.RecordtypeId == studyRecordtype){ 
                reqId.add(cap.DRDW_Request__c);
                mReqActivityId.put(cap.DRDW_Request__c,cap.Id);
            }    
        }    
        //Querying to insert events 
        lCapReq = [select id,recordType.Name,Lab_Testing_Required__c,Samples_to_collect_new__c,Study_Title__c from DRDW_Cap_Request__c where id in : reqId];
        insertEvents(lCapReq,mReqActivityId);   
        system.debug('**lCapReq*'+lCapReq);  
        system.debug('**mReqActivityId*'+mReqActivityId);  */
    }
    
    public Static void OnAfterUpdate(List<DRDW_Capability__c> oldObjects,List<DRDW_Capability__c> updatedObjects,Map<id,DRDW_Capability__c> MapObjectMap){
        // AFTER UPDATE LOGIC                
        Id studyRecordtype = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Study Activity').getRecordTypeId();        
        Id requestRecordtype = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Request Activity').getRecordTypeId();
        Set<DRDW_Capability__c> actWithUpdatedPrefStartDate = new Set<DRDW_Capability__c>();
        Map<Id,List<DRDW_Capability__c>> reqActivitiesmap = new Map<Id,List<DRDW_Capability__c>>();
        for(DRDW_Capability__c cap:updatedObjects){ 
            // checking for both record types (study and request)
            if(cap.RecordTypeId == requestRecordtype || cap.RecordTypeId == studyRecordtype){
                if(cap.RecordTypeId == requestRecordtype){
                    if(!reqActivitiesmap.containsKey(cap.DRDW_Request__c)){
                        reqActivitiesmap.put(cap.DRDW_Request__c,new List<DRDW_Capability__c>());
                    }
                    reqActivitiesmap.get(cap.DRDW_Request__c).add(cap);   
                }          
                // only if the proposed start date is changed, we should shift the resource allocation
                if(cap.Proposed_Start_Date__c != MapObjectMap.get(cap.id).Proposed_Start_Date__c){
                    actWithUpdatedPrefStartDate.add(cap);
                }      
            }
        }
        //calling the function to shift the assign Resources records
        DRDW_EventDays_Utility.updateAssignedResources(actWithUpdatedPrefStartDate, MapObjectMap);
        //calling the function to shift the eventdays
        DRDW_EventDays_Utility.shiftEventDays(actWithUpdatedPrefStartDate, MapObjectMap);
        List<DRDW_Cap_Request__c> lRequests = new List<DRDW_Cap_Request__c>();
        lRequests = [select id,Status__c,recordtypeid from DRDW_Cap_Request__c where id in:reqActivitiesmap.keySet()];
        for(DRDW_Cap_Request__c r:lRequests){          
            Integer assigned = 0;
            Integer unassigned = 0;
            Integer total = 0;
            if(reqActivitiesmap.get(r.id)!=null){                
                for(DRDW_Capability__c c:reqActivitiesmap.get(r.id)){                    
                    if(c.Status__c == 'Unassigned')
                        unassigned++;                        
                    if(c.Status__c == 'Assigned')
                        assigned++;
                }                
                total = reqActivitiesmap.get(r.id).size();                                                  
                if(unassigned == total){               
                    r.Status__c = 'Unassigned';                    
                }else{
                    r.Status__c = 'Partially Assigned';
                }                   
                if(assigned == total)
                    r.Status__c = 'Assigned';                    
                System.debug('Assigned'+assigned+'Unassigned'+unassigned+'Total'+total);                
            }                                
        }        
        update lRequests;                
    }
    
    public  Static void OnBeforeDelete(List<DRDW_Capability__c> ObjectsToDelete,Map<id,DRDW_Capability__c> MapObjectMap){
        // BEFORE DELETE LOGIC        
        Id recordtype = Schema.SObjectType.DRDW_Capability__c.getRecordTypeInfosByName().get('Request Activity').getRecordTypeId();       
        List<DRDW_Capability__c> lActivities = new List<DRDW_Capability__c>();       
        for(DRDW_Capability__c c:ObjectsToDelete){            
            if(c.RecordTypeId == recordtype){               
                lActivities.add(c);                          
            }            
        }                 
        if(lActivities.size()>0){
            try{
                system.debug('+++++++++++'+lActivities);
                List<DRDW_Budget_Master__c> oBudget = new List<DRDW_Budget_Master__c>();
                oBudget.addAll([Select id from DRDW_Budget_Master__c where Activity__c IN:lActivities]);
                if(!oBudget.isEmpty()){
                    Delete oBudget;
                }
                DRDW_ActivityERLFlow.deleteERLEvent(lActivities);                
            }catch(Exception e){                    
                System.debug('Error'+e);                   
            }   
        }        
    }
    
    /*Public static void insertEvents(List<DRDW_Cap_Request__c> NewCapReqList,Map<Id,Id> mReqActivityId){      
        List<DRDW_Cap_Request__c> oCapreqList =  new List<DRDW_Cap_Request__c>();
        List<DRDW_Event__c> leventInsert = new List<DRDW_Event__c>();
        for(DRDW_Cap_Request__c req : NewCapReqList){           
            if(mReqActivityId.containskey(req.Id) && req.recordType.Name == 'GO' && (req.Lab_Testing_Required__c != NULL || req.Samples_to_collect_new__c != NULL)){
                DRDW_Event__c oevent;
                if(req.Lab_Testing_Required__c != NULL){
                    List<String> lLabTestingReq = req.Lab_Testing_Required__c.split(';');
                    for(String labtestingReq : lLabTestingReq){
                        oevent = new DRDW_Event__c();
                        oevent.Event_Category__c = 'Lab';
                        oevent.Type__c = 'GO';
                        oevent.Study_Title__c = req.Study_Title__c;
                        oevent.Status__c = 'Unassigned';
                        oevent.Event_Type__c = labtestingReq;
                        oevent.DRDW_Activity__c = mReqActivityId.get(req.Id);
                        leventInsert.add(oevent);
                    }
                }
                if(req.Samples_to_collect_new__c != NULL && req.Samples_to_collect_new__c != '[]'){
                    List<String> lSamplesToCollect = req.Samples_to_collect_new__c.replace('[','').replace(']','').split(',');
                    for(String samplestocollect : lSamplesToCollect){
                        oevent = new DRDW_Event__c();
                        oevent.Event_Category__c = 'Sample';
                        oevent.Type__c = 'GO';
                        oevent.Study_Title__c = req.Study_Title__c;
                        oevent.Status__c = 'Unassigned';
                        oevent.Event_Type__c = samplestocollect;
                        oevent.DRDW_Activity__c = mReqActivityId.get(req.Id);
                        leventInsert.add(oevent);
                    }
                }                               
            }           
        }
        if(leventInsert.size() > 0){
            insert leventInsert;
        }
    }*/
}