src/objects/DRDW_Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Posting_Date__c</fullName>
        <label>Posting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <formula>CASE(Month( Posting_Date__c ),1,&quot;1&quot;,2,&quot;1&quot;,3,&quot;1&quot;,4,&quot;2&quot;,5,&quot;2&quot;,6,&quot;2&quot;,7,&quot;3&quot;,8,&quot;3&quot;,9,&quot;3&quot;,10,&quot;4&quot;,11,&quot;4&quot;,12,&quot;4&quot;,&quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Line Items</relationshipLabel>
        <relationshipName>DRDW_Budget_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Master__c.object
<CustomObject>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Idea_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Assessment_Project</value>
            </filterItems>
            <filterItems>
                <field>DRDW_Project__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Generation_Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Budget Master</relationshipLabel>
        <relationshipName>DRDW_Budget_Master</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Actuals__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Business_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Business Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_F_X_Forecast__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total F&quot;X&quot; Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Rolling_Forecast__c</fullName>
        <label>Total Rolling Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>DRDW Budget Master</label>
    <nameField>
        <displayFormat>BGT-{0000}</displayFormat>
        <label>DRDW Budget Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Business_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Business Plan</description>
        <label>Business Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DRDW_Budget_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DRDW Budget Master</description>
        <label>DRDW Budget Master</label>
        <referenceTo>DRDW_Budget_Master__c</referenceTo>
        <relationshipLabel>DRDW Budget Summaries</relationshipLabel>
        <relationshipName>DRDW_Budget_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_X_Forecast__c</fullName>
        <defaultValue>0</defaultValue>
        <label>F&quot;X&quot; Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Total_Actuals__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Q Total Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rolling_Forecast__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Rolling Forecast</description>
        <label>Rolling Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Budget Summary</label>
    <nameField>
        <displayFormat>Summary-{0000}</displayFormat>
        <label>DRDW Budget Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Budget_Summary_Detail__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Budget_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Budget Summary</label>
        <referenceTo>DRDW_Budget_Summary__c</referenceTo>
        <relationshipLabel>DRDW Budget Summary Details</relationshipLabel>
        <relationshipName>DRDW_Budget_Summary_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sept</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Budget Summary Detail</label>
    <nameField>
        <displayFormat>BSD-{0000}</displayFormat>
        <label>DRDW Budget Summary Detail  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Budget Summary Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DRDW_BudgetSummaryTriggerHandler.cls
public class DRDW_BudgetSummaryTriggerHandler {
        
    
    public void OnAfterInsert(List<DRDW_Budget_Summary__c> newSummaries){
        
        List<DRDW_Budget_Summary_Detail__c> lDSummary = new List<DRDW_Budget_Summary_Detail__c>();
        
        Schema.DescribeFieldResult fieldResult = DRDW_Budget_Summary_Detail__c.Month__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                List<String> months = new List<String>();
                for( Schema.PicklistEntry f : ple)
                   {
                     months.add(f.getValue());
                   }    
                system.debug('picklist'+months);
                
                
        
        
        for(DRDW_Budget_Summary__c oSummary : newSummaries){
            List<String> qmonths = getCurrentMonths(oSummary.Quarter__c);
            for(String m:qmonths){
            
            DRDW_Budget_Summary_Detail__c oDetail = new DRDW_Budget_Summary_Detail__c();
            oDetail.DRDW_Budget_Summary__c = oSummary.Id;
            oDetail.Month__c=m;
            oDetail.Year__c = oSummary.Year__c;
            oDetail.Quarter__c = oSummary.Quarter__c;
            lDSummary.add(oDetail);
            }
        }
        
        insert lDSummary;
        
    }
    
    
    Public void OnAfterUpdate(List<DRDW_Budget_Summary__c> newSummaries,Map<Id,DRDW_Budget_Summary__c> oldMap){
        
        Set<ID> bIds = new Set<ID>();
        
         for(DRDW_Budget_Summary__c oSummary:newSummaries){                      
            bIds.add(oSummary.DRDW_Budget_Master__c);
        }
        
        Map<id,DRDW_Budget_Master__c> mapOfMasters = new Map<id,DRDW_Budget_Master__c>([select id,Total_Actuals__c,Total_Rolling_Forecast__c,Total_F_X_Forecast__c,Total_Business_Plan__c from DRDW_Budget_Master__c where id in:bIds]);
        
        if(!mapOfMasters.isEmpty()){
            
        List<DRDW_Budget_Master__c> lBudgets = new List<DRDW_Budget_Master__c>();
        
            for(DRDW_Budget_Summary__c oSummary:newSummaries){                      
            DRDW_Budget_Master__c oMaster = mapOfMasters.get(oSummary.DRDW_Budget_Master__c);
            
            if(oMaster.Total_Actuals__c==null){
                oMaster.Total_Actuals__c = 0;
                }
            if(oMaster.Total_Rolling_Forecast__c == null){
                oMaster.Total_Rolling_Forecast__c=0;
                }
                oMaster.Total_Actuals__c = oMaster.Total_Actuals__c - oldMap.get(oSummary.id).Q_Total_Actuals__c;
                oMaster.Total_Actuals__c = oMaster.Total_Actuals__c + oSummary.Q_Total_Actuals__c;
                system.debug('Total Actual'+oSummary.Q_Total_Actuals__c);
                oMaster.Total_Rolling_Forecast__c =  oMaster.Total_Rolling_Forecast__c - oldMap.get(oSummary.id).Rolling_Forecast__c;
                oMaster.Total_Rolling_Forecast__c =oMaster.Total_Rolling_Forecast__c + oSummary.Rolling_Forecast__c;
                
                  oMaster.Total_Business_Plan__c=  oMaster.Total_Business_Plan__c- oldMap.get(oSummary.id).Business_Plan__c;
                oMaster.Total_Business_Plan__c=oMaster.Total_Business_Plan__c+ oSummary.Business_Plan__c;
                
                  oMaster.Total_F_X_Forecast__c=  oMaster.Total_F_X_Forecast__c- oldMap.get(oSummary.id).F_X_Forecast__c;
                oMaster.Total_F_X_Forecast__c=oMaster.Total_F_X_Forecast__c+ oSummary.F_X_Forecast__c;
                
              system.debug('Total Forecast'+oSummary.Rolling_Forecast__c);
              oMaster.Total_Actuals__c = oMaster.Total_Actuals__c.round(System.RoundingMode.HALF_EVEN);
              lBudgets.add(oMaster);
            
        }
        
        Set<DRDW_Budget_Master__c> sBudgets = new Set<DRDW_Budget_Master__c>();
        sBudgets.addAll(lBudgets);
        lBudgets.clear();
        lBudgets.addAll(sBudgets);
        
        update lBudgets;
            
        }        
    }
    
     public void OnBeforeDelete(List<DRDW_Budget_Summary__c> oldMasters,Map<Id,DRDW_Budget_Summary__c> oldMap){
         
           updateBudgetMaster(oldMasters,oldMap);
         
     }
    
    
    public void OnAfterDelete(List<DRDW_Budget_Summary__c> oldMasters,Map<Id,DRDW_Budget_Summary__c> oldMap){
         
         
        Set<Id> bIds = new Set<Id>();
        //map of budget master and budget summary
        Map<Id,Id> summarybudget = new Map<Id,Id>();
        
        for(DRDW_Budget_Summary__c b:oldMasters){
            summarybudget.put(b.id,b.DRDW_Budget_Master__c);
        } 
        
        List<DRDW_Budget_Line_Item__c> blineitems = new List<DRDW_Budget_Line_Item__c>();
        
        blineitems = [select id,Related_To__c,Posting_Date__c,Quarter__c from DRDW_Budget_Line_Item__c where Related_To__c in : summarybudget.Values()];
        
        Map<Id,List<DRDW_Budget_Line_Item__c>> masterLines = new Map<Id,List<DRDW_Budget_Line_Item__c>>();
        
        for(DRDW_Budget_Line_Item__c b:blineitems){
        
            if(!masterLines.containsKey(b.Related_To__c)){
                List<DRDW_Budget_Line_Item__c> blines = new List<DRDW_Budget_Line_Item__c>();
                blines.add(b);
                masterLines.put(b.Related_To__c,blines);
            }else{
            List<DRDW_Budget_Line_Item__c> blines = masterLines.get(b.Related_To__c);
                blines.add(b);
                masterLines.put(b.Related_To__c,blines);
            
            }
        
        }
        
        List<DRDW_Budget_Line_Item__c> dbLines = new List<DRDW_Budget_Line_Item__c>();
        
        
         for(DRDW_Budget_Summary__c b:oldMasters){
            if(masterLines.get(summarybudget.get(b.id))!=null)
            for(DRDW_Budget_Line_Item__c line:masterLines.get(summarybudget.get(b.id))){
                 system.debug('******Year****'+b.Year__c);
                  system.debug('******lineYear****'+line.Posting_Date__c.Year());
                if(line.Quarter__c == b.Quarter__c && line.Posting_Date__c.Year() == Integer.valueOf(b.Year__c)){
                    dbLines.add(line);
                }
                    
            }
            
        } 
        
        
        system.debug(dbLines);
        
        
        
     
        List<DRDW_Budget_Summary_Detail__c> lBDetails = new List<DRDW_Budget_Summary_Detail__c>();      
        
         lBDetails = [select id from DRDW_Budget_Summary_Detail__c where DRDW_Budget_Summary__c in:oldMap.keySet()];
         
         try{
            
          
            
            delete lBDetails;
            delete dbLines;
           
            
          
        
        }catch(Exception e){
        
            system.debug('error'+e.getMessage());
            
        }
        
        
     }
    
    
    
    
    Public List<String> getCurrentMonths(String i){
    
        List<String> months = new List<String>();
        
        if(i=='1'){
        
          months.add('Jan');
               months.add('Feb');
                months.add('March');
        
        }else if(i=='2'){
        
             months.add('April');
               months.add('May');
                months.add('June');
            
        }else if(i=='3'){
        
             months.add('July');
               months.add('Aug');
                months.add('Sept');
         
        
        }else if(i=='4'){
        
             months.add('Oct');
               months.add('Nov');
                months.add('Dec');
            
        }
        
        return months;
        
    }
    
    public void onBeforeInsert(List<DRDW_Budget_Summary__c> NewSummaryList){
     List<DRDW_Budget_Summary__c> lSummary = new List<DRDW_Budget_Summary__c>();  
        //Changing the currency ISO for all Budget Master records getting inserted  
            for(DRDW_Budget_Summary__c oSummary : NewSummaryList){
                oSummary.CurrencyIsoCode = Label.DRDW_Currency_Label;
                lSummary.add(oSummary);
            }
        /* updating the records if not null
        if(!lSummary.isEmpty() && lSummary != null){
            update lSummary;
        }  */      
        
    }
    
    
    public void updateBudgetMaster(List<DRDW_Budget_Summary__c> oldMasters,Map<Id,DRDW_Budget_Summary__c> oldMap){

        Set<ID> bIds = new Set<ID>();
        
         for(DRDW_Budget_Summary__c oSummary:oldMasters){                      
            bIds.add(oSummary.DRDW_Budget_Master__c);
        }
        
        Map<id,DRDW_Budget_Master__c> mapOfMasters = new Map<id,DRDW_Budget_Master__c>([select id,Total_Actuals__c,Total_Rolling_Forecast__c,Total_F_X_Forecast__c,Total_Business_Plan__c from DRDW_Budget_Master__c where id in:bIds]);
        
       
        
        if(!mapOfMasters.isEmpty()){
            
        List<DRDW_Budget_Master__c> lBudgets = new List<DRDW_Budget_Master__c>();
        
            for(DRDW_Budget_Summary__c oSummary:oldMasters){                      
            DRDW_Budget_Master__c oMaster = mapOfMasters.get(oSummary.DRDW_Budget_Master__c);
            
            if(oMaster.Total_Actuals__c==null){
                oMaster.Total_Actuals__c = 0;
                }
            if(oMaster.Total_Rolling_Forecast__c == null){
                oMaster.Total_Rolling_Forecast__c=0;
                }
                
                oMaster.Total_Actuals__c = oMaster.Total_Actuals__c - oSummary.Q_Total_Actuals__c;
                system.debug('Total Actual'+oSummary.Q_Total_Actuals__c);
                
                oMaster.Total_Rolling_Forecast__c =oMaster.Total_Rolling_Forecast__c - oSummary.Rolling_Forecast__c;
                
                 
                oMaster.Total_Business_Plan__c=oMaster.Total_Business_Plan__c- oSummary.Business_Plan__c;
                
                  
                oMaster.Total_F_X_Forecast__c=oMaster.Total_F_X_Forecast__c- oSummary.F_X_Forecast__c;
                
              system.debug('Total Forecast'+oSummary.Rolling_Forecast__c);
              oMaster.Total_Actuals__c = oMaster.Total_Actuals__c.round(System.RoundingMode.HALF_EVEN);
              lBudgets.add(oMaster);
            
        }
        
        Set<DRDW_Budget_Master__c> sBudgets = new Set<DRDW_Budget_Master__c>();
        sBudgets.addAll(lBudgets);
        lBudgets.clear();
        lBudgets.addAll(sBudgets);
        
        update lBudgets;
            
        }        

}
    
}