src/objects/DRDW_Assign_Resource__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Assign Resources</relationshipLabel>
        <relationshipName>DRDW_Assign_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DRDW Assign Resource</label>
    <nameField>
        <displayFormat>AssRes-{0000}</displayFormat>
        <label>DRDW Assign Res</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Assign Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Cap_Request__c.object
<CustomObject>
    <fields>
        <fullName>Samples_to_collect_new__c</fullName>
        <label>Study Schedule Activities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lab_Testing_Required__c</fullName>
        <label>Lab Testing Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lab Challenge Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination Preparation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood Serum Neutralization</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Pre-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Post-Challenge Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Challenge: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Pre-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Post-Vaccination Titrations</fullName>
                </value>
                <value>
                    <fullName>Lab Vaccination: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: ELISA</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Western Blot</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Hematology</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Plasma Separation</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Blood: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Swabs: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Isolations</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Fecal: Other</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Process for shipment/retention</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Isolation</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: PCR</fullName>
                </value>
                <value>
                    <fullName>Lab Necropsy: Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related project</description>
        <label>Project</label>
        <referenceTo>DRDW_Project__c</referenceTo>
        <relationshipLabel>DRDW Requests</relationshipLabel>
        <relationshipName>DRDW_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Unassigned&quot;</defaultValue>
        <description>Stores status of request.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Partially Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>DRDW Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Requests</pluralLabel>
    <recordTypes>
        <fullName>ERL</fullName>
        <active>true</active>
        <label>ERL</label>
    </recordTypes>
    <recordTypes>
        <fullName>GO</fullName>
        <active>true</active>
        <label>GO</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <description>Actual End Date</description>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
	 <fields>
        <fullName>DRDW_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ERL Request</label>
        <referenceTo>DRDW_Cap_Request__c</referenceTo>
        <relationshipLabel>DRDW Activities</relationshipLabel>
        <relationshipName>DRDW_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
  <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <description>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</description>
        <inlineHelpText>The proposed start date of the activity. If this date shifts forward or backward, the resource assignment also shifts accordingly.</inlineHelpText>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <label>DRDW Activity</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>Capability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Activities</pluralLabel>
	<sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DRDW_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Dates__c</fullName>
        <label>Event Dates</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Partially Assigned</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Capturing Title for GO Request</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>DRDW Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Event_Days__c.object
<CustomObject>
    <fields>
        <fullName>DRDW_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRDW Event</label>
        <referenceTo>DRDW_Event__c</referenceTo>
        <relationshipLabel>DRDW Event Days</relationshipLabel>
        <relationshipName>DRDW_Event_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Event Days</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>DRDW Event Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Event Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <label>Capability</label>
    <nameField>
        <label>DRDW Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DRDW_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DRDW_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ERL</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRDW Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRDW Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>Enter the date that effort begins on the research study/ research project.</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <label>Research</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_DRDW_ActivityTriggerHandler.cls
@isTest
private class Test_DRDW_ActivityTriggerHandler {
    static testMethod void testPositive() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
            lprojects[0].Project_Name__c='Test';
            lprojects[1].Idea_Name__c='Test';       
            insert lprojects;

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',Samples_to_Collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+5,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId());
            insert ocapReq;
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].Title__c='Test';           
            list<DRDW_Capability__c> lCapabStudy = DRDW_TestDataFactory.returnCapabilities(1, 'Study Activity',lprojects[0].id);
            lCapabStudy[0].Title__c='Test';
            lCapabStudy[0].DRDW_Request__c=ocapReq.id; 
            lcapabstudy[0].Proposed_Start_Date__c = system.today();
            lCapab.addAll(lCapabStudy);
            test.startTest();
            insert lCapab;

            lCapab[1].DRDW_Request__c=ocapReq.id; 
            lCapab[0].DRDW_Request__c=ocapReq.id;
            lcapabstudy[0].Proposed_Start_Date__c = system.today()-2;
            update lCapab;
            
            System.assert(lCapab.size()>0);
            DRDW_Event__c oEvent = new DRDW_Event__c(/*Event_Dates__c='04/26/2017,05/26,2017',*/Type__c='GO',Status__c='Partially Assigned',DRDW_Activity__c=lCapab[0].Id,Event_Category__c='Lab',Event_Type__c='Lab Work Required',Frequency__c='');
            insert oEvent;
            DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='DDS',Type__c='ERL',Role__c='Functional Head',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active',Days_Per_Week__c='7');
            insert oResource;
            
            DRDW_Event_Days__c oEvDay = new DRDW_Event_Days__c(Allocated_Hours__c=10.00,Date__c=System.today(),DRDW_Event__c=oEvent.Id,DRDW_Resource__c=oResource.Id,Type__c='GO');
            insert oEvDay;
            
            delete lCapab[0];
            test.stopTest();
        }
    } 

    static testMethod void testPositive1() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
            lprojects[0].Project_Name__c='Test';
            lprojects[1].Idea_Name__c='Test';       
            insert lprojects;

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',Samples_to_Collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+5,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId(), GO_Preferred_Start_Date__c=system.today());
            insert ocapReq;
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].Title__c='Test';           
            list<DRDW_Capability__c> lCapabStudy = DRDW_TestDataFactory.returnCapabilities(1, 'Study Activity',lprojects[0].id);
            lCapabStudy[0].Title__c='Test';
            lCapabStudy[0].DRDW_Request__c=ocapReq.id; 
            lcapabstudy[0].Proposed_Start_Date__c = system.today();
            //lCapab.addAll(lCapabStudy);
            test.startTest();
            insert lcapabstudy;
            
            DRDW_Event__c oEvent = new DRDW_Event__c(/*Event_Dates__c='04/26/2017,05/26,2017',*/Type__c='GO',Status__c='Partially Assigned',DRDW_Activity__c=lCapabStudy[0].Id,Event_Category__c='Lab',Event_Type__c='Lab Work Required',Frequency__c='');
            insert oEvent;
            DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='Animal Care',Type__c='GO',Role__c='Study Manager',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active',Days_Per_Week__c='5');
            insert oResource;
            
            DRDW_Assign_resource__c oAssignResource = new DRDW_Assign_resource__c();
            oAssignResource.DRDW_Resources__c = oResource.id;
            oAssignResource.Allocation_End_Date__c =system.today().adddays(1);
            oAssignResource.Allocation_Start_Date__c = system.today();
            oAssignResource.DRDW_Event__c = oEvent.id;
            oAssignResource.Group__c = 'Animal Care';
            oAssignResource.Task__c = 'Other';
            oAssignResource.DRDW_Activity__c = lCapabStudy[0].Id;
            oAssignResource.Hours_Per_Day__c = 6;
            
            DRDW_Event_Days__c oEvDay = new DRDW_Event_Days__c(Allocated_Hours__c=10.00,Date__c=System.today(),DRDW_Event__c=oEvent.Id,DRDW_Resource__c=oResource.Id,Type__c='GO');
            insert oEvDay;
            
            List<BusinessHours> lstBusHour = [Select id from BusinessHours where name = 'DRDW_ERL_Business_Hours' limit 1];
            System.debug('Business hours in test'+lstBusHour);
            
            DRDW_Capability__c lCapabStudyNew = [select Id,Proposed_Start_Date__c from DRDW_Capability__c limit 1];
            
            system.debug('lCapabStudy '+lCapabStudy );

            lCapabStudyNew.Proposed_Start_Date__c = system.today()+2;
            update lCapabStudyNew;
            
            System.assert(lCapab.size()>0);
            
            test.stopTest();
        }
    } 


    static testMethod void testPositive2() {        
        User busAdm = DRDW_TestDataFactory.getTestingUser();        
        DRDW_TestDataFactory.givePermissions(busAdm.id,'DRDW_Business_Admin');
        System.runAs(busAdm) {
            List<DRDW_Project__c> lprojects = DRDW_TestDataFactory.returnProjects(2,'Generation Project');  
            lprojects[0].Project_Name__c='Test';
            lprojects[1].Idea_Name__c='Test';       
            insert lprojects;

            DRDW_Cap_Request__c ocapReq = new DRDW_Cap_Request__c(Lab_Testing_Required__c='Lab Challenge Preparation;Lab Vaccination Preparation',Samples_to_Collect_new__c='[Tissue Sample,Oral Swabs]',Project__c=lprojects[0].Id,Actual_Start_Date__c=System.today(),Actual_End_Date__c=System.today()+5,RecordTypeId=Schema.SObjectType.DRDW_Cap_Request__c.getRecordTypeInfosByName().get('GO').getRecordTypeId(), GO_Preferred_Start_Date__c=system.today());
            insert ocapReq;
            list<DRDW_Capability__c> lCapab = DRDW_TestDataFactory.returnCapabilities(2, 'Request Activity',lprojects[0].id);
            lCapab[0].Title__c='Test';           
            list<DRDW_Capability__c> lCapabStudy = DRDW_TestDataFactory.returnCapabilities(1, 'Study Activity',lprojects[0].id);
            lCapabStudy[0].Title__c='Test';
            lCapabStudy[0].DRDW_Request__c=ocapReq.id; 
            lcapabstudy[0].Proposed_Start_Date__c = system.today();
            //lCapab.addAll(lCapabStudy);
            test.startTest();
            insert lcapabstudy;
            
            DRDW_Event__c oEvent = new DRDW_Event__c(/*Event_Dates__c='04/26/2017,05/26,2017',*/Type__c='GO',Go_Sub_Activities__c='[Animal Care - Misc.]',Status__c='Partially Assigned',DRDW_Activity__c=lCapabStudy[0].Id,Event_Category__c='Lab',Event_Type__c='Lab Work Required',Frequency__c='2');
            insert oEvent;
            DRDW_Resource__c oResource = new DRDW_Resource__c(Name__c=busAdm.Id,Department__c='Animal Care',Type__c='GO',Role__c='Study Manager',Hours_Available_Per_Day__c=10.00,Hours_per_Week__c=50.00,Status__c='Active',Days_Per_Week__c='7');
            insert oResource;
            
            DRDW_Assign_resource__c oAssignResource = new DRDW_Assign_resource__c();
            oAssignResource.DRDW_Resources__c = oResource.id;
            oAssignResource.Allocation_End_Date__c =system.today().adddays(1);
            oAssignResource.Allocation_Start_Date__c = system.today();
            oAssignResource.DRDW_Event__c = oEvent.id;
            oAssignResource.Group__c = 'Animal Care';
            oAssignResource.Task__c = 'Other';
            oAssignResource.DRDW_Activity__c = lCapabStudy[0].Id;
            oAssignResource.Hours_Per_Day__c = 6;
            
            insert oAssignResource;
            
            DRDW_Event_Days__c oEvDay = new DRDW_Event_Days__c(Allocated_Hours__c=10.00,Date__c=System.today(),DRDW_Event__c=oEvent.Id,DRDW_Resource__c=oResource.Id,Type__c='GO');
            insert oEvDay;
            
            List<BusinessHours> lstBusHour = [Select id from BusinessHours where name = 'DRDW_ERL_Business_Hours' limit 1];
            System.debug('Business hours in test'+lstBusHour);
            
            DRDW_Capability__c lCapabStudyNew = [select Id,Proposed_Start_Date__c from DRDW_Capability__c limit 1];
            
            system.debug('lCapabStudy '+lCapabStudy );

            lCapabStudyNew.Proposed_Start_Date__c = system.today()+2;
            update lCapabStudyNew;
            
            System.assert(lCapab.size()>0);
            
            test.stopTest();
        }
    } 



}